### ISSUE TITLE
Неверно вставилась подпись к таблице

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#100]
diplom_rudko.docx

![image](https://user-images.githubusercontent.com/18662965/52562941-1b5e5700-2e11-11e9-9bda-fa52689adb69.png)

![image](https://user-images.githubusercontent.com/18662965/52563082-755f1c80-2e11-11e9-86eb-9e4333210a2e.png)

**Comment by GloomlySeth** [comment]
diplom_rudko.docx
учесть и такой нюанс. + В исходном файле в номере таблицы может быть 5-6 точек

![default](https://user-images.githubusercontent.com/18662965/52798426-f3792880-3088-11e9-85ae-292696d5c6d9.png)

**Comment by GloomlySeth** [comment]
obschiy.docx

![default](https://user-images.githubusercontent.com/18662965/52799458-eeb57400-308a-11e9-939e-a37e62d61ae3.png)

**Comment by Lyzgarik** [comment]
Добавили удаление любых символов в конце. Ситуации с различными подписями пока допиливается.

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/53270288-65421980-36fc-11e9-95c7-ceff10fda116.png)

Косяк аналогичный первому в этом баге. Вроде как нет изменений
![image](https://user-images.githubusercontent.com/18662965/53270368-a2a6a700-36fc-11e9-9d62-5b2c47ec2564.png)


средний с номером таблицы из трёх цифр не проверял.

**Comment by GloomlySeth** [comment]
**ниже не смог проверить. Проверить позже!!!**

вдогонку. Файл - Мазур

![image](https://user-images.githubusercontent.com/18662965/53271896-d08dea80-3700-11e9-85b1-bbb0fdc50e40.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/53271941-f4513080-3700-11e9-8302-c01bc4901277.png)

**Comment by GloomlySeth** [comment]
Всё поправлено кроме одного момента.  Пробельные строки не в том порядке в этом случае

![default](https://user-images.githubusercontent.com/18662965/53979630-6d984c80-411f-11e9-9924-4a2c5e8c4d8c.png)
