### ISSUE TITLE
Обработка формул. Непонятка

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#105]
obschiy.docx

![default](https://user-images.githubusercontent.com/18662965/52799943-e3af1380-308b-11e9-8fcc-434abb4d2de5.png)

**Comment by GloomlySeth** [comment]
ещё такое появилось. документ тот же. Формула набрана в MathType
+ нет пробельных строк до и после формулы. 

![image](https://user-images.githubusercontent.com/18662965/52896240-d9009580-31d5-11e9-8094-521c1b46dcab.png)

**Comment by GloomlySeth** [comment]
чую связь скрина с фиксом этого бага, поэтому пишу в комментах

В таблице 8.4. ниже по тексту тоже пропали границы

![image](https://user-images.githubusercontent.com/18662965/53207463-d2927380-3644-11e9-8aca-341f35fdceed.png)

**Comment by freedom00000** [comment]
Пробел был внутри формулы-буквы, а мы все лишнее оттуда удаляем
