### ISSUE TITLE
Списки изменяют стиль

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#11]
тестовый документ - "2_razdela_1510736019.docx"

![image](https://user-images.githubusercontent.com/18662965/32827183-4bdff62e-c9fc-11e7-969d-8450a56c7226.png)

**Comment by Lyzgarik** [comment]
И чего они должны замениться на тире, если это нум.список?

**Comment by GloomlySeth** [comment]
Раднёнок ставил задачу нумерованные списки оставлять как есть? Не менять на тире?

**Comment by Lyzgarik** [comment]
ну.. вообще да.. они же специально и нумеруются там.
нумерованные на цифру+большая буква в начале
маркированные на тире+маленькая

**Comment by GloomlySeth** [comment]
Хорошо. Тогда оставляем, как есть. Только шрифт ровняем.
