### ISSUE TITLE
Пропали маркеры в списках

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#118]
mazur_for_s_2-3.docx

![image](https://user-images.githubusercontent.com/18662965/53271808-902e6c80-3700-11e9-9a25-e221665ef1b7.png)

**Comment by GloomlySeth** [comment]
Маркеры появились, зато стили поехали

![image](https://user-images.githubusercontent.com/18662965/53389820-e2da8380-39a1-11e9-9574-cd1953d45ed8.png)




![image](https://user-images.githubusercontent.com/18662965/53389848-0998ba00-39a2-11e9-9cf2-a034c3265b16.png)


![image](https://user-images.githubusercontent.com/18662965/53390106-22ee3600-39a3-11e9-9b8d-e79ed9dda46e.png)

**Comment by freedom00000** [comment]
цифры теперь в TNR
