### ISSUE TITLE
Изменять размеры таблиц

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#12]
тестовый документ - "2_razdela_1510736019.docx"

![image](https://user-images.githubusercontent.com/18662965/32827787-5bf11e38-c9fe-11e7-9edd-53f2c11c0d33.png)

Предлагаю уменьшать ширину всех ячеек которые больше 1 см таблицы на равные части.

**Comment by freedom00000** [comment]
![default](https://user-images.githubusercontent.com/10418363/32839251-e8583aac-ca24-11e7-985c-251b0c9b8f86.JPG)
Правильно я понял?

**Comment by GloomlySeth** [comment]
да

**Comment by freedom00000** [comment]
Просто есть вариант сохранить пропорции и сделать, чтобы таблица не выходила за поля. Не подойдет?

**Comment by GloomlySeth** [comment]
Пойдёт. Но нужно смотреть как результат покосит надписи в узких я ячейках.

**Comment by freedom00000** [comment]
До/После
![default](https://user-images.githubusercontent.com/10418363/32850960-bbfa48e0-ca44-11e7-9996-730ffa3c6af2.JPG)
Про узкие ячейки не понял

**Comment by GloomlySeth** [comment]
нармуль

**Comment by GloomlySeth** [comment]
Как Ты уменьшаешь таблицы?   
  В общих параметрах таблицы меняешь размер, а остальное ворд делает? 
  Или как?

**Comment by freedom00000** [comment]
Да, общую ширину таблицы меняю только

**Comment by GloomlySeth** [comment]
Хорошо. пусть пока так будет

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/33044603-910535ea-ce5a-11e7-8c55-1968dac996b5.png)

1)  Таблица 1.2 не стала уже. Хорошо бы знать почему.  И заставить их вписаться в размер страницы
2) Жёлтый фон остаётся у таблиц и рисунков. Это потому, что они были помечены примечаниями?

**Comment by freedom00000** [comment]
1 похоже она по ширине меньше чем ширина страницы - (отступ левого края+ отступ правого края)
2 кто-то сделал заливку в ячейках желтой, можно на любой цвет поменять
