### ISSUE TITLE
Расшифровка формул. Неадекватности

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#123]
mazur_for_s_2-3.docx

![default](https://user-images.githubusercontent.com/18662965/53577193-47563800-3b86-11e9-9542-19a89240932a.png)

**Comment by freedom00000** [comment]
не удалось получить баг, при обработке на сайте все хорошо
![image](https://user-images.githubusercontent.com/10418363/53626207-305f2680-3c16-11e9-9c3b-b4168d6c4304.png)

**Comment by GloomlySeth** [comment]
А можно ещё пробелы до тире вставить?

**Comment by GloomlySeth** [comment]
obschiy.docx

  формулы Mathtype не распознались по всему документу. Допустим старый MathType. закроем глаза. 
   Но почему абзацы между формулами не обработались? 
   И почему в этом месте (в исходном файле формулы здесь в таблицах), если формулы MathType не распознаются как формулы, не появилась надпись вставьте название таблицы. 

 
![image](https://user-images.githubusercontent.com/18662965/53667144-2cb4b980-3c81-11e9-806d-b4c80ce66125.png)

**Comment by freedom00000** [comment]
почему не распознались? перенумерация прошла, элемент "где" выставился с выступом 2 см, а между формулами абзацы не обработались по другой, совсем не связанной с формулами, причине

**Comment by GloomlySeth** [comment]
Тогда почему эти не распознались? 
Тоже MathType.

![default](https://user-images.githubusercontent.com/18662965/53747478-67526800-3eb4-11e9-9e15-7634a64136b0.png)

**Comment by freedom00000** [comment]
проблема в том, что я не вижу разницы в них когда они в тексте как элементы "где" и когда это формула из-за того, что там используется система с ссылками на бинарный файл, который понимает сама MathType. Пока сделал по ~~длине (если длиннее 1000 значит формула, на скриншоте длинна 2500)~~ тексту возле формулы (если номер (1.1) или пробелы, то формула, иначе вставка в текст)

**Comment by GloomlySeth** [comment]
Продолжаем эпопею. 
obschiy.docx

Формулв набраны в редакторе ворда. Вроде даже не древнем.

![image](https://user-images.githubusercontent.com/18662965/53936743-f9788d00-40bb-11e9-9683-3b4038c65f37.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/53936910-83285a80-40bc-11e9-864f-bc2bb616cd8d.png)

**Comment by GloomlySeth** [comment]
почти, но есть такой момент 

![default](https://user-images.githubusercontent.com/18662965/53978853-42146280-411d-11e9-988b-211a459588f7.png)



![default](https://user-images.githubusercontent.com/18662965/53979091-e1395a00-411d-11e9-9dc6-c8e568903857.png)



![default](https://user-images.githubusercontent.com/18662965/53979170-180f7000-411e-11e9-84f4-7503a4e61c19.png)

**Comment by freedom00000** [comment]
В этом моменте "мин" и "шт" распознаются как переменные
![image](https://user-images.githubusercontent.com/10418363/54116699-61064380-4400-11e9-85c2-08d0319edd8e.png)

**Comment by GloomlySeth** [comment]
Понятно.  Вопрос.
Если единицы измерения будут прописаны после формулы в одной с ней строке. Что будет?

**Comment by freedom00000** [comment]
Будет считаться что формула находится внутри текста, пропуск.

**Comment by GloomlySeth** [comment]
тогда впишу это в возможности. Оставляем как есть. Не трогаем этот косяк

**Comment by freedom00000** [comment]
**Формулой считается объект _OfficeMath_ или _EmbeddedObject_, который находится отдельно от других слов/символов (исключение '(1.2)' и подобное), при этом игнорируются пробелы и табуляции**
