### ISSUE TITLE
Загловки переносятся ?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#124]
mazur_for_s_2-3.docx

![default](https://user-images.githubusercontent.com/18662965/53577383-9d2ae000-3b86-11e9-97d1-652fe1d93548.png)

**Comment by freedom00000** [comment]
не удалось получить баг, при обработке на сайте все хорошо
![image](https://user-images.githubusercontent.com/10418363/53626188-23423780-3c16-11e9-8635-cc55cd51dbcf.png)
