### ISSUE TITLE
Убрать колонку в таблице 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#125]
Если в таблице есть колонка с номером по порядку, то её нужно удалить. 
  Название в шапке такой колонки может быть - 
  -  №
  -  № п/п
  -  № по порядку
  -  Порядковый номер
  - Номер попорядку
  Учесть то, что в таблицах, как на скрине, удаление  колонки номер один повлечёт за собой удаление ячеек (в данном случае трёх нижних). А их удалять не нужно.  

![default](https://user-images.githubusercontent.com/18662965/53578185-33133a80-3b88-11e9-8e68-ab82e7d0818b.png)

**Comment by GloomlySeth** [comment]
![изображение](https://user-images.githubusercontent.com/18662965/54288440-8342c180-45b8-11e9-9b20-104dbba3dd06.png)

**Comment by GloomlySeth** [comment]
![изображение](https://user-images.githubusercontent.com/18662965/54293761-9d34d200-45c1-11e9-85cd-b203b3f84f1a.png)

**Comment by GloomlySeth** [comment]
На домашнем компе  у меня  таблица не изменилась

**Comment by freedom00000** [comment]
Нужно чтобы были цифры в колонке с номером
