### ISSUE TITLE
Что-то с определением формул сломалось

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#128]
![изображение](https://user-images.githubusercontent.com/18662965/54288137-fd267b00-45b7-11e9-8dbc-d3f8d7dcd679.png)

**Comment by GloomlySeth** [comment]
не работает на мазуре

![изображение](https://user-images.githubusercontent.com/18662965/54411153-5a791400-46ff-11e9-85e8-cadbf9e85ad9.png)

**Comment by GloomlySeth** [comment]
shitik.docx
1) 
![изображение](https://user-images.githubusercontent.com/18662965/54413254-163d4200-4706-11e9-86e9-775efc63404c.png)

2)  
В файле shitik.docx много таких ситуаций

![изображение](https://user-images.githubusercontent.com/18662965/54413461-cd39bd80-4706-11e9-8469-ebca2d40d4d5.png)


3) файле shitik.docx 
![image](https://user-images.githubusercontent.com/18662965/54432641-d3499180-473a-11e9-821f-7e9aa1d940b1.png)

**Comment by GloomlySeth** [comment]
перепроверить с изменением исходного документа

![image](https://user-images.githubusercontent.com/18662965/54561204-29396600-49d5-11e9-9f03-1c158bff9a6d.png)

**Comment by freedom00000** [comment]
А я ведь говорил про это, “;” у криворуких юзеров где не должно быть
