### ISSUE TITLE
Подписи  к таблицам и рисункам. Неадекватности

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#129]
Тире не пропало.

**Comment by GloomlySeth** [comment]
Удаляем нумерацию любого формата

![image](https://user-images.githubusercontent.com/18662965/54336701-d743b980-463d-11e9-8440-8ff2b039baa7.png)


Документ  shitik.docx

![image](https://user-images.githubusercontent.com/18662965/54431766-54ebf000-4738-11e9-8382-5e9a8d05b7cd.png)

**Comment by GloomlySeth** [comment]
Исправлено

**Comment by freedom00000** [comment]
тире и точку сделал

**Comment by GloomlySeth** [comment]
ну хрен его знает... Пока не работает

**Comment by GloomlySeth** [comment]
ещё нашёл 
sodyl.docx

В исходном файле рисунок подписан как "График 3 -". Думаю нужно учесть этот момент при переписывании метода обработки рисунков. 

![изображение](https://user-images.githubusercontent.com/18662965/54621845-81c23f00-4a79-11e9-82e7-f73d0c1d4580.png)

**Comment by GloomlySeth** [comment]
1) sodyl.docx


![image](https://user-images.githubusercontent.com/18662965/54872315-1eb30e00-4dd3-11e9-9444-b7a5b3f25b3d.png)

2)  obschiy.docx

![image](https://user-images.githubusercontent.com/18662965/54872539-9afb2080-4dd6-11e9-94b8-b9a868cf8485.png)

![image](https://user-images.githubusercontent.com/18662965/54872589-499f6100-4dd7-11e9-9651-030fbec97fc8.png)

**Comment by GloomlySeth** [comment]
Осталось только этот момент пофиксить

![изображение](https://user-images.githubusercontent.com/18662965/55133360-77b5d580-5136-11e9-90cb-2227d3fb952a.png)
