### ISSUE TITLE
Неверная вставка номера рисунка

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#134]
diplom1m.docx

В квадратные скобки ссылку на рисунок не вставляем. Вставляем до квадратных скобок. 

![image](https://user-images.githubusercontent.com/18662965/54336427-1a515d00-463d-11e9-89ea-3335d3091261.png)

**Comment by freedom00000** [comment]
#133 косвено поправил в этом месте
В местах, где нет ссылки на рисунок в такой ситуации, будет вставлено перед скобками
![image](https://user-images.githubusercontent.com/10418363/54350491-84c6c500-465e-11e9-9264-a8528ef72325.png)
