### ISSUE TITLE
Список третьего уровня? 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#138]
![image](https://user-images.githubusercontent.com/18662965/54408080-68c03380-46f1-11e9-9356-a2aad27c7087.png)

**Comment by freedom00000** [comment]
в оригинале он третьего, тут тоже
![image](https://user-images.githubusercontent.com/10418363/54418959-5d7ffe80-4717-11e9-91d2-c1c26a828192.png)

**Comment by GloomlySeth** [comment]
вопрос закрыт
