### ISSUE TITLE
Абзац по центру

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#139]
mazur_for_s_2-3-4.docx 

![изображение](https://user-images.githubusercontent.com/18662965/54412423-a0d07200-4703-11e9-8743-7be849d03b6b.png)

**Comment by freedom00000** [comment]
Все из-за начинающегося на "Рис" абзаца

**Comment by GloomlySeth** [comment]
ну не может же быть у рисунка 2 подписи одна за одной. Что-нибудь с этим можно сделать?

**Comment by freedom00000** [comment]
Уже сделал, просто не обновил
