### ISSUE TITLE
Заголовки второго уровня неверно определились

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#140]
shitik.docx

![изображение](https://user-images.githubusercontent.com/18662965/54412593-61565580-4704-11e9-8bad-4ea422cff134.png)

**Comment by freedom00000** [comment]
Криворукие юзеры делают нумерацию подразделов элементами списка?

**Comment by GloomlySeth** [comment]
Нужно отменить у разделов первого и второго уровня, если они элементы списка, эту настройку. Достаточно ли используемых нами критериев поиска заголовков для реализации такой плюшки?

**Comment by freedom00000** [comment]
уже сделано, если текст полностью В ВЕРХНЕМ РЕГИСТРЕ или **полностью жирный** , то убираю свойства списка и он становится заголовком
