### ISSUE TITLE
Послестрочный отступ поплыл

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#142]
shitik.docx

![image](https://user-images.githubusercontent.com/18662965/54432130-5d90f600-4739-11e9-919d-ffd827f4d5d1.png)

**Comment by freedom00000** [comment]
shitik.docx пока с ошибкой обрабатывается

**Comment by freedom00000** [comment]
в этом месте проблем нет
