### ISSUE TITLE
Соотнесение номера таблиц  и рисунков не работает

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#147]
shitik.docx
несовпадуха есть и ниже в таблицах 6.7-6.11. В исходном файле нумерация совпадает 

![image](https://user-images.githubusercontent.com/18662965/54562876-f09b8b80-49d8-11e9-807c-52f568645829.png)

![image](https://user-images.githubusercontent.com/18662965/54563262-cac2b680-49d9-11e9-8f2f-d1ce50057c40.png)

**Comment by freedom00000** [comment]
Проблема в совсем чуть-чуть кривых руках юзера, т.к. до обработки есть 2 рисунка с одинаковым номером, а после они уже нумеруются правильно , происходит следующее:
5.4 остается 5.4 и ссылки не изменяются, после этого дубликат бывший 5.4 (теперь 5.5) заменяет все ссылки с 5.4 на 5.5, затем все нормализуется и дубликатов нет. Но 5.5 был следующий рисунок, который теперь 5.6 => 5.5 заменяется на 5.6 и так далее
![image](https://user-images.githubusercontent.com/10418363/54611044-4454b600-4a67-11e9-8a96-204fea71ec5d.png)
