### ISSUE TITLE
Подписи к таблицам покривели

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#15]
![image](https://user-images.githubusercontent.com/18662965/32972296-9ded76f0-cc02-11e7-964c-ed48c5b4f916.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/33045365-9a58f994-ce5d-11e7-902c-5f33ec1f7327.png)


Подпись к таблице должна быть  по левому краю без абзацного отступа

**Comment by Lyzgarik** [comment]
up
