### ISSUE TITLE
До обработки формул не дошло? 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#150]
mazur_for_s_2-3-4.docx

**Comment by freedom00000** [comment]
А что за файл?

**Comment by GloomlySeth** [comment]
А Ты ещё не выучил эти формулы наизусть?  :)

**Comment by freedom00000** [comment]
Это экономический раздел, они везде одинаковые там:)

**Comment by GloomlySeth** [comment]
Я дописал название файла. Вверху до картинки

**Comment by GloomlySeth** [comment]
документ тот же.

![изображение](https://user-images.githubusercontent.com/18662965/54701606-65d89f00-4b46-11e9-9b58-50827fe53077.png)

**Comment by GloomlySeth** [comment]
shitik_attach.docx
mazur_for_s_2-3-4.docx

в обоих файлах картина в этом месте не изменилась. Как проверял или почему ставишь зелёную метку?

**Comment by freedom00000** [comment]
теперь все меняется
