### ISSUE TITLE
Расположение текста в шапке таблицы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#152]
В шапке таблицы располагаем содержимое ячеек по центру и по центру (по вертикали и по горизонтали, соответственно).

**Comment by GloomlySeth** [comment]
shitik_attach.docx

не все ячейки в шапке стали по центру. Пример в скриншоте

![изображение](https://user-images.githubusercontent.com/18662965/54801740-5d34b580-4c79-11e9-97d9-6dd20a09a345.png)

**Comment by freedom00000** [comment]
поправил

**Comment by GloomlySeth** [comment]
1) sodyl.docx


![image](https://user-images.githubusercontent.com/18662965/54872339-8bc6a380-4dd3-11e9-835b-c5ebf107a244.png)

2) obschiy.docx

![image](https://user-images.githubusercontent.com/18662965/54872570-034a0200-4dd7-11e9-8a9b-9ed734e7f34c.png)

**Comment by GloomlySeth** [comment]
А мы тут таблицу ужимаем? Почему переносы стали такие 

![изображение](https://user-images.githubusercontent.com/18662965/54940894-b5e7a500-4f3c-11e9-9625-9344e1aabbb2.png)

**Comment by freedom00000** [comment]
Не ужимаем, размер шрифта в исходном файле 10, а по СТП требованиям нашим 12
