### ISSUE TITLE
Есть документы, которые не обрабатываются. 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#16]
![image](https://user-images.githubusercontent.com/18662965/32972539-f9c996f6-cc03-11e7-8a0f-ca1c280ca0b2.png)

**Comment by GloomlySeth** [comment]
к стати документ с широкими таблицами "2_razdela_1510739133.docx" пишет "ошибка обработки". Ранише обрабатывался нормально.

Выясни кто из Вас скривил и совместно поровняйте.

**Comment by freedom00000** [comment]
Моя вина, поправлю сейчас

**Comment by GloomlySeth** [comment]
документы
kr_eis_lebed_v_10_brs_1510351599.docx
diplom_1_1510735837.docx
пишет ошибка обработки

**Comment by Lyzgarik** [comment]
up

**Comment by GloomlySeth** [comment]
Контрольная работа от Лебедева и диплом 1 по прежнему пишет "Ошибка обработки"

**Comment by GloomlySeth** [comment]
Документы на текущий момент обработались все!!!

Однако в контрольной лебедева (kr_eis_lebed_v_10_1510351270.docx) все подписи к рисункам сделаны шрифтом не по стандарту (см. скрин). 

![image](https://user-images.githubusercontent.com/18662965/33688375-3908b558-daec-11e7-8b26-77d5889eb778.png)

**Comment by Lyzgarik** [comment]
ну очень обширно вышло, может в отдельную? Если сама проблема по теме решена
