### ISSUE TITLE
Выступ для рисунков делаем 0

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#162]
![Uploading image.png…]()

**Comment by Lyzgarik** [comment]
пикча не прикрепилась нормально, вроде как 
![image](https://user-images.githubusercontent.com/18488089/55036860-f3c3f680-502c-11e9-9735-75bd967e5434.png)

**Comment by GloomlySeth** [comment]
Да она тут и не нужна. Просто нужно сделать убери выступ 0  для подписи к рисункам
