### ISSUE TITLE
Почему метод не сработал? 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#167]
У нас должен быть метод, который все дефисы с пробелом до дефиса и после дефиса должен менять на тире. Почему он в этом случае не сработал. 

![image](https://user-images.githubusercontent.com/18662965/55167778-a78aca80-5182-11e9-94e0-1d5393a8501c.png)

Или я ошибаюсь и у нас нет такого метода?

**Comment by freedom00000** [comment]
кривоват малость тот метод 😄

**Comment by GloomlySeth** [comment]
ставлю метку красную?

**Comment by freedom00000** [comment]
вроде поправил, позже проверю все, как сервер доступен будет
