### ISSUE TITLE
Расшифровка формул. Вопрос. 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#169]
shitik_attach.docx

![image](https://user-images.githubusercontent.com/18662965/55262708-b1debe80-527f-11e9-8e33-66a6453c4a5b.png)

Просто, чтоб понимать и закрепить в мозгу причины

**Comment by freedom00000** [comment]
из-за цифр. предполагалось, что их не будет

**Comment by GloomlySeth** [comment]
но возможны же формулы с цифрами в индексах. Типа а0, С1 и проч. Что-то нужно с этим сделать. В формула поленомов точно постоянные будут с индексом в виде цифр: А1, А2, .... Аn

**Comment by freedom00000** [comment]
ок, добавил еще и цифры
