### ISSUE TITLE
а мы точку после руб. дорисовываем?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#175]
kovalevich.docx

![image](https://user-images.githubusercontent.com/18662965/55305342-aabed880-5458-11e9-9e35-b13f5c766a4d.png)

**Comment by freedom00000** [comment]
да, только почему-то не перенесли когда переделывали подписи к рисункам

**Comment by Lyzgarik** [comment]
Страшные люди..
