### ISSUE TITLE
Перенумерация рисунков и замена тире. Неадекватности

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#176]
kovalevich.docx

![image](https://user-images.githubusercontent.com/18662965/55305635-f32ac600-5459-11e9-907b-a7b82980f25b.png)

**Comment by GloomlySeth** [comment]
kurstip_ser.docx

![image](https://user-images.githubusercontent.com/18662965/55318945-8ecd2e00-547c-11e9-85d4-e680557cdb2c.png)

**Comment by GloomlySeth** [comment]
shitik_attach.docx

До этого рисунка тоже всё не очень гладко. Нумерация не повторяется и совпадает.  С таблицами тоже самое.

### Этот рисунок стал в тексте 5.12!!!

![image](https://user-images.githubusercontent.com/18662965/55454741-a118aa80-55e9-11e9-9515-535ef905ce10.png)

**Comment by GloomlySeth** [comment]
shitik_attach.docx

А это видал?  В разделе 3 все остальные рисунки стали 3.9

![image](https://user-images.githubusercontent.com/18662965/55512718-77549780-566c-11e9-87bd-348a31de7969.png)

### Таблицы в разделе становятся 6.12 в момент перенумерации таблицы номер 9.

**Comment by freedom00000** [comment]
Если появились варианты обхода, то можно попробовать, но...
уже ведь обсуждали этот вопрос
3 раздел, рисунки начинают повторятся на 3.5 (2 штуки одинаковых)
![image](https://user-images.githubusercontent.com/10418363/55554549-ba098480-56eb-11e9-8c50-82209d119519.png)
в 6 разделе похожая ситуация, только там "хитрая формула", которая набрана просто от руки, но находящаяся в таблице, она становится таким же номером, как следующая
![image](https://user-images.githubusercontent.com/10418363/55554766-43b95200-56ec-11e9-965c-7c2f0695cbcd.png)
вот еще похожее #151 и #147
