### ISSUE TITLE
Внутренности формул пропадают

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#180]
shitik_attach.docx

Из-за смены шрифта? 

![image](https://user-images.githubusercontent.com/18662965/55455489-7d0a9880-55ec-11e9-8243-5331eb36ed1d.png)

**Comment by Lyzgarik** [comment]
Это из-за смены шрифта, не помогает в некоторых случаях "нормализация" (галочка в ворде, типа преобразовать в нормальный текст)
