### ISSUE TITLE
Приложения не обработались

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#181]
shitik_attach.docx

![image](https://user-images.githubusercontent.com/18662965/55455647-16d24580-55ed-11e9-9099-1493751d934d.png)

**Comment by freedom00000** [comment]
Не совпадение по требованиям, если про заголовок (только 2 строки смотрю после слова приложение и меняю их местами если надо)

**Comment by GloomlySeth** [comment]
А остальной текст тогда игнорируешь?  Там всё ниже как было так и осталось.
Я понимаю при несовпадении по требованиям если слова "Перечень элементов" не попадут в содержание. Но текст с рисунками, таблицами и формулами можно же поровнять. Тем более что номер приложения у Тебя уже есть из первой строки.

**Comment by freedom00000** [comment]
Тогда я может не вижу в чем баг. Подразделы А.1, таблица тоже...

**Comment by GloomlySeth** [comment]
shitik_attach.docx


![image](https://user-images.githubusercontent.com/18662965/55513292-07471100-566e-11e9-8da3-256d686b9665.png)

Проверяешь меня?
