### ISSUE TITLE
Кавычки, тире и расшифровка формул

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#187]
kovalevich.docx

![image](https://user-images.githubusercontent.com/18662965/55547266-9ccbba80-56d9-11e9-8e51-b2a715f4986c.png)

**Comment by freedom00000** [comment]
Конкретно такое "тире" у нас теперь будет заменятся на нормальное, но...могут быть и с другими символами похожие случаи, потому что тире, которые здесь есть, набраны с помощью встроенной в ворд утилиты "символы", на деле это не текст, а код какой-то (`w:char="F02D"`), который только ворд понимает как тире (интернет вообще говорит, что это иероглиф)
![image](https://user-images.githubusercontent.com/10418363/55556230-b5df6600-56ef-11e9-83d3-899ecf02e775.png)
что переводится с китайского, как "полагаться"

**Comment by GloomlySeth** [comment]
А с дефисом и кавычками пофиксил?

**Comment by freedom00000** [comment]
Да

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/55658307-db5e9380-5805-11e9-9a04-2c755317b563.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/55659099-ca635180-5808-11e9-96dd-257faaa4fdec.png)

**Comment by freedom00000** [comment]
Кавычки в исходном файле открывающие...юзеры

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/55757605-08f14a00-5a5d-11e9-97eb-f06f046bc90b.png)
