### ISSUE TITLE
Перенос заголовка не сработал

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#192]
shitik_attach.docx

хотя пункт 5.5 в этом же документе сработал

![image](https://user-images.githubusercontent.com/18662965/55665527-17b3e300-584a-11e9-9e83-509d2bfb1f2e.png)

**Comment by GloomlySeth** [comment]
Неа. 
Ещё и таблицы перестали переноситься и разбиваться

**Comment by Lyzgarik** [comment]
увеличил время для рендера ( и обработки дока соответственно), теперь работает. Лучше не обрабатывать 2 файла вместе, особенно "тяжелых"
