### ISSUE TITLE
Использовать другой алгоритм строки для временного сохранения размеров картинок

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#193]
Сейчас добавились примечания к рисункам, которые оформляются без пробельной строки между ними, в формате 

СТРОКА
РИСУНОК
ПРИМЕЧАНИЕ К РИСУНКУ
СТРОКА
ПОДПИСЬ К РИСУНКУ 
СТРОКА

![image](https://user-images.githubusercontent.com/18488089/55670949-f2979280-5892-11e9-8f34-2d71214f3a50.png)
![image](https://user-images.githubusercontent.com/18488089/55670954-fdeabe00-5892-11e9-9f02-6307ec600103.png)
Сейчас пихает в эту строку после рисунка размеры (Проверка на текст и создание временной-затем удаляемой?).
![image](https://user-images.githubusercontent.com/18488089/55670958-07742600-5893-11e9-8907-d4f2037221b0.png)
P.S. фиксанул бы, но вдруг чего полетит

**Comment by pavel-moroz** [comment]
ооо, много что полетит

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/55870604-a057b980-5b91-11e9-9860-98fa387170bf.png)
ни одно из условий if не прошло

**Comment by pavel-moroz** [comment]
какой файл?
