### ISSUE TITLE
Добавить пробельную строку после заголовка СОДЕРЖАНИЕ

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#198]
![image](https://user-images.githubusercontent.com/18662965/55942693-a27f4e00-5c4d-11e9-87be-4e2da412ab06.png)

**Comment by GloomlySeth** [comment]
Шрифт и размер не тот, но пока сгодится

**Comment by freedom00000** [comment]
поправил размер, а шрифт пустой строки важен?

**Comment by GloomlySeth** [comment]
Шрифт не сльно Важен, а вот интервал до и после должен быть 0. А то, что я видел там "после" - 10

**Comment by GloomlySeth** [comment]
Абзацный отступ у СОДЕРЖАНИЕ тоже нужно убрать. Сейчас 1,25 см
