### ISSUE TITLE
Шрифт в ячейках

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#20]
![image](https://user-images.githubusercontent.com/18662965/33044951-0caf00d0-ce5c-11e7-87c8-376f08cb80f3.png)

Или Ты оставляешь размер шрифта как в исходном файле? 

Нужно делать 12м шрифтом всё наполнение таблицы.

**Comment by freedom00000** [comment]
Я почему-то думал, что в шапку 14,а в остальном 12. Сделаю везде один.
Шапка то умная, но двойная не всегда следует той логике и иногда ячеек становится другое количество в середине, поэтому отмечается как шапка не совсем корректно. Трудно объяснить. Слишком много таблиц бывает с не стандартными шапками

**Comment by Lyzgarik** [comment]
залью в пн.

**Comment by Lyzgarik** [comment]
up
