### ISSUE TITLE
Чудеса с текстом

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#204]
2_ergonomicheskiy_razdel_1522993714.docx

Обычный абзац стал заголовком (и попал в содержание, но без номера раздела)
Поменялись местами два коротких предложения
Пропали списки

![image](https://user-images.githubusercontent.com/18662965/56054530-c29f3200-5d5f-11e9-9280-6885d795b7d7.png)

**Comment by freedom00000** [comment]
там было слово "приложение" 😆
