### ISSUE TITLE
Раздел появился внутри приложения

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#209]
sakovich.docx

![image](https://user-images.githubusercontent.com/18662965/56358189-96176a00-61e6-11e9-832a-69e02b57f13d.png)

**Comment by freedom00000** [comment]
это только если юзер нормально оформил это название приложения...

**Comment by GloomlySeth** [comment]
это понятно. Судя по скрину у Сакович всё верно оформлено и моё предложение должно сработать.

Всё остальное оставим на совесть пользователя
