### ISSUE TITLE
При формировании содержания сбой

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#210]
sakovich.docx

Не жирные абзацы стали заголовками второго уровня. 

![image](https://user-images.githubusercontent.com/18662965/56358716-2a360100-61e8-11e9-9487-d0ed860920a3.png)

**Comment by freedom00000** [comment]
они жирные, только это спрятано немного. в стилях.
![image](https://user-images.githubusercontent.com/10418363/56365066-b4866100-61f8-11e9-9c6f-c9ee30f93259.png)
В приоритете не стиль у ворда, а значения в самом параграфе (то что можно на вкладке шрифт менять), поэтому выглядит не жирным.
Иногда заголовки делают жирными как раз через стиль, если я уберу возможность просмотра стиля, тоже будут проблемы с определением

**Comment by GloomlySeth** [comment]
Добавил в ограничение. 

Давай хотя бы очистим стили в абзацах
 - где несколько предложений 
 - распознанных, как подпись к рисунку, таблице 
 - распознанных, как элемент списка 
 - распознанных, как элемент расшифровки формулы
