### ISSUE TITLE
Кавычки не заменились

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#212]
sakovich.docx

![image](https://user-images.githubusercontent.com/18662965/56454185-a3069b80-6355-11e9-97ea-780f1c03a869.png)

**Comment by GloomlySeth** [comment]
В следующем абзаце такое твориться!!!

![image](https://user-images.githubusercontent.com/18662965/56530831-b420f980-655b-11e9-9cad-e18893fecd0d.png)

**Comment by freedom00000** [comment]
Тут нужно подумать как определить скобки внутри скобок ( а может и скобки внутри скобок внутри скобок внутри......). Чтобы ёлочки в правильную сторону смотрели...
