### ISSUE TITLE
Страницы с альбомной ориентацией

### ISSUE THREAD

**Issue by freedom00000** [GloomlySeth/Bugtreking-SGOST#218]

**Comment by freedom00000** [comment]
Размеры полей и прочее для альбомной ориентации под вопросом. Пока сделал чтобы ориентация сохранялась

**Comment by GloomlySeth** [comment]
При альбомной ориентации верхнее поле = левому полю при книжной ориентации
При альбомной ориентации нижнее поле = правому полю при книжной ориентации
При альбомной ориентации левое поле = нижнему полю при книжной ориентации
При альбомной ориентации правое поле = верхнему полю при книжной ориентации

**Comment by GloomlySeth** [comment]
Фича не попала в обнову?  На документе  kurstip_ser.docx не работает....
--
не работает
