### ISSUE TITLE
Таблицы без подписей

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#22]
Доработать альгоритм. 

   Если таблица в исходном документе не имеет подписи, нужно  добавить подпись вида : 
   "Таблица 1.1 - Добавьте подпись к таблице"

    Номер таблицы присвоить в соответствии с разделам или по настройкам, установленным пользователем. После номера знак "тире". Слова "Добавьте подпись к таблице" красным жирным шрифтом. 

    При написании кода учитывать, что будут приходить настройки пользователя в соответствии со стариницей http://wz.argoosnet.by/node/add/demand-create
  
   В том числе шаблон подписи нумерации таблиц может измениться : 
   - вместо "Таблица" могутт быть слова "Табл." или "Т." или другое слово прописанное пользователем;
   - номера таблицы может не быть;
   - после номера таблицы может быть "пробел", или, "точка+пробел", или "пробел+тире+пробел", или "пробел+тире+пробел";
   - подпись к таблице может начинаться с большой или малой буквы;
   - вконце подписи к таблице точка может ставиться может не ставиться.

**Comment by Lyzgarik** [comment]
подписи есть.
 С сокращениями надо будет глянуть, разве что "Т" искать не будет на данном этапе

**Comment by GloomlySeth** [comment]
Обращаю внимание не просто "Т", а "Т." (Т большое с точкой)

**Comment by Lyzgarik** [comment]
Done
