### ISSUE TITLE
Пропали заголовки второго уровня

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#221]
kovalevich.docx

В содержание заголовки второго уровня в этом разделе тоже не попали. 

![image](https://user-images.githubusercontent.com/18662965/56717312-0b35f280-6745-11e9-8eb5-0b8764461324.png)

В мазур таже фигня. Раньше нашему приложению было пофигу, что заголовки были списками на входе.

**Comment by freedom00000** [comment]
> Раньше нашему приложению было пофигу, что заголовки были списками на входе.

после того, как мы начали удалять стили у абзацев с более чем 1 предложением, у подписей к рисункам и таблицам, а так же у **списков** , получается что оно без стиля не жирное, но все еще список

**Comment by freedom00000** [comment]
условие теперь такое: стили у списков с 1 элементом не будут удалятся, а так же списки, в которых есть первый элемент полностью написанный большими буквами (ситуации когда это заголовок второго уровня и как на скрине, там оба заголовка сделаны при помощи стилей)
