### ISSUE TITLE
Пропали формулы MathType и не только

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#224]
kovalevich.docx

![image](https://user-images.githubusercontent.com/18662965/56718624-cb243f00-6747-11e9-8bd6-7f142da2dd84.png)

**Comment by GloomlySeth** [comment]
В том же документе ещё и формула, набранная в редакторе ворда пропала 

![image](https://user-images.githubusercontent.com/18662965/56718910-62899200-6748-11e9-91b7-222fd329018d.png)

**Comment by GloomlySeth** [comment]
Два вопроса.

![image](https://user-images.githubusercontent.com/18662965/56848661-2f840180-68f4-11e9-86ae-3405bc6b86b2.png)


![image](https://user-images.githubusercontent.com/18662965/56848719-e1bbc900-68f4-11e9-9495-f4447543496b.png)

**Comment by freedom00000** [comment]
1. баг какой-то, почему-то ниже формула перескочила 
2. потому что удаляется все, кроме формулы, а там обычно мусор типа множества пробелов и номеров формул. Не стала абзацем, потому что она написана внутри параграфа формулы

**Comment by GloomlySeth** [comment]
1 - фиксим

2 - оставляем как сейчас
