### ISSUE TITLE
Пробел после точек нужно скорректировать

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#225]
mazur_for_s_2.docx

что-нибудь придумаем для таких ситуаций? Чтобы пробел после точек не ставился. Тима может если после точки "by", "com", "biz", "gov",  "ru" и проч, то пробел не ставим ...

![image](https://user-images.githubusercontent.com/18662965/56719651-dd06e180-6749-11e9-8af8-383a0b1ce258.png)

**Comment by GloomlySeth** [comment]
Как тут сделано? Ка я предлагал или по-другому?

**Comment by freedom00000** [comment]
Не совсем. Если английская маленькая буква с точкой склеена, то не ставлю пробел
