### ISSUE TITLE
Пропали буквы в подписи к формулам (продолжение с подписями в таблицах)

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#227]
obschiy.docx

![image](https://user-images.githubusercontent.com/18662965/56725132-f5c8c480-6754-11e9-8a71-8047491286a5.png)

**Comment by GloomlySeth** [comment]
Зато такой косяк вернулся.

![image](https://user-images.githubusercontent.com/18662965/56848969-1892de80-68f7-11e9-9e03-cca09cbf9701.png)

**Comment by freedom00000** [comment]
в методе SetTableLineSwastOne
