### ISSUE TITLE
Сделать пункты 

### ISSUE THREAD

**Issue by freedom00000** [GloomlySeth/Bugtreking-SGOST#228]
- Если первое предложение в абзаце курсивом, добавляем нумерацию в начало. 

- Если в абзаце уже есть нумерация, то перенумеровываем в соответствии с документом.

- Если встречается заголовок "третьего" уровня, которого по СТП быть не может, делаем из него пункт и склеиваем со следующим абзацем, а в начале добавляем его номер

**Comment by GloomlySeth** [comment]
не заливал? Пробовал прогнать shitik_attach.docx, не сработало

**Comment by freedom00000** [comment]
~~Еще не доделал~~
