### ISSUE TITLE
Зачем сделали разрыв страницы после заголовка второго уровня?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#229]
kovalevich.docx

Master
![image](https://user-images.githubusercontent.com/18662965/56848054-c77ded00-68ec-11e9-96b1-c3f8afbbb89b.png)

**Comment by freedom00000** [comment]
там ведь идут 2 заголовка 2 уровня подряд, без содержимого. Так ведь не бывает?
но у меня почему-то оно иначе обработалось. 
![image](https://user-images.githubusercontent.com/10418363/56852530-34ad7480-6925-11e9-8aef-69ceee79d10f.png)
