### ISSUE TITLE
Учесть при обработке рисунков

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#23]
Доработать альгоритм. 

   Если рисунок в исходном документе не имеет подписи, нужно  добавить подпись вида : 
   "Рисунок 1.1 - Добавьте подпись к рисунку"

    Номер рисунка присвоить в соответствии с разделам или по настройкам, установленным пользователем. После номера знак "тире". Слова "Добавьте подпись к рисунок" красным жирным шрифтом. 

    При написании кода учитывать, что будут приходить настройки пользователя в соответствии со стариницей
    http://wz.argoosnet.by/node/add/demand-create
  
   В том числе шаблон подписи нумерации рисунков может измениться : 
   - вместо "Рисунок" могутт быть слова "Рис." или "Р." или другое слово прописанное пользователем;
   - номера Рисунка может не быть;
   - после номера рисунка может быть "пробел", или, "точка+пробел", или "пробел+тире+пробел", или "пробел+тире+пробел";
   - подпись к рисунку может начинаться с большой или малой буквы;
   - вконце подписи к рисунку точка может ставиться может не ставиться.

**Comment by Lyzgarik** [comment]
пусть повисит, но вроде многое, как и с таблицей, учтено. (кроме пары моментов)
Потом нужно будет больше присмотреться к формированию из готовых вариантов, когда наберётся больше

> При написании кода учитывать, что будут приходить настройки пользователя в соответствии со стариницей
> http://wz.argoosnet.by/node/add/demand-create"

Это уже когда будут приходить
