### ISSUE TITLE
Замена кавычек. Вопрос?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#231]
obschiy.docx

Будем развивать алгоритм?

![image](https://user-images.githubusercontent.com/18662965/56849030-efbf1900-68f7-11e9-97fd-7c99dcdc1456.png)

**Comment by freedom00000** [comment]
Да, сначала пытался находить их парами, но бывают ситуации когда внутри кавычек есть еще другие. И вообще возможна ситуация, когда юзер забыл их закрыть. Поэтому если вначале слова, то открывающая. А тут ни там и не там
