### ISSUE TITLE
Подровнять шрифт продолжения таблицы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#232]
obschiy.docx

требования MASTER

![image](https://user-images.githubusercontent.com/18662965/57184408-bec88080-6ec3-11e9-9ede-585bad2e4855.png)

**Comment by GloomlySeth** [comment]
проверил на Сакович. Требования к Магистерским

**Comment by freedom00000** [comment]
не знаю в чем проблема, обработал оба саковича(на сервере) и все 14 шрифтом

**Comment by GloomlySeth** [comment]
магитерскими требованиями?

**Comment by freedom00000** [comment]
да
