### ISSUE TITLE
Рисунок не обработался

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#233]
kurstip_ser.docx

STP BSEU

![image](https://user-images.githubusercontent.com/18662965/56849387-4b8ba100-68fc-11e9-9084-12184a7ae0fc.png)

и ещё один 

![image](https://user-images.githubusercontent.com/18662965/56849432-cbb20680-68fc-11e9-9278-4a83d1ccea90.png)

**Comment by Lyzgarik** [comment]
Знаки около рисунков удалять или оставлять? В данном случае после рисунков, а именно с ними в абзаце, стоит по точке.
Сейчас сделал так, что если в абзаце с рисунком каким бы то ни было чудесным образом стоят ТОЛЬКО знаки, то он обрабатывается как обычный рисунок. При этом исходные знаки остаются.

**Comment by GloomlySeth** [comment]
Знаки убираем. С рисунком они не нужны.
