### ISSUE TITLE
Сложности в (не)списках 

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#235]
kurstip_ser.docx

знаки тусят
![image](https://user-images.githubusercontent.com/18488089/56888856-b87a7480-6a7d-11e9-8f43-2b13164c4729.png)

**Comment by GloomlySeth** [comment]
Молодца, а чего не пофиксил?

**Comment by freedom00000** [comment]
### это не список

**Comment by Lyzgarik** [comment]
Да, точно, не список.
повтор знаков смутил, пока листал другой баг, не глянул
