### ISSUE TITLE
Размер шрифта для "Продолжение таблицы ..."

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#241]
Сейчас при размере шрифта подписи к таблице = 14, размер шрифта к продолжения таблицы = 12. 

 

![image](https://user-images.githubusercontent.com/18662965/57009413-200bfd80-6bff-11e9-912e-24baff48cb2f.png)

**Comment by freedom00000** [comment]
Какой из 3 частей? У нас подпись может быть в 3 местах и жирной и 20 шрифтом и курсивом и тд
Вроде совпадает же размер со словом «таблица»

**Comment by GloomlySeth** [comment]
обработайте по STP BSUIR. Шрифт подписи к таблице и продолжения таблицы не совпадает. 
Это в каких это требованиях есть слово "Таблица" жирным цветом?

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/57164402-accfda80-6dfc-11e9-9b29-f92234cc190e.png)
имел в виду это. Какая цифра должна соответствовать вопросу?
обработано по STP BSUIR kurstip_ser.docx, там все совпадает (14 шрифт)

**Comment by GloomlySeth** [comment]
Согласен. Недоглядел
