### ISSUE TITLE
Обработка примечаний. Нужна корректировка

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#244]
shitik_attach.docx

При обработке по STP BSUIR не требуется оформлять прмеяания по требованиям STP BSEU

![image](https://user-images.githubusercontent.com/18662965/57010090-79762b80-6c03-11e9-9e18-d570bae82a37.png)

**Comment by freedom00000** [comment]
Такая фишка только у нархоза есть? Кажется нужна настройка на сайте
