### ISSUE TITLE
Поправить распознавание формул

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#248]

**Comment by GloomlySeth** [comment]
написал бы в какую сторону править
учти, что бывают таблицы с нессколькими столбцами, а в одноиз столбцов формулы. В остальных столбцах буквы и цифры

**Comment by freedom00000** [comment]
в сторону, если первая ячейка пустая, а вторая с формулой (раньше мы проверяли только первую ячейку, она пустая => не находили формулу)
