### ISSUE TITLE
В начале документа появляется подпись к рисунку

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#25]
![image](https://user-images.githubusercontent.com/18662965/33614931-c33f98b2-d9e9-11e7-99bb-eb0e946d6dab.png)

Документ  ruk.polz_its_tekst1_1512487492.docx
сделал  первой строкой "НАЗХНАЧЕНИЕ"  - второй обзац стал рисунком. (см. скрин) 

убрал пробельные строки до и после второго абзаца - результат обработки тот же (см. скрин)

**Comment by Lyzgarik** [comment]
up
