### ISSUE TITLE
Подпись к таблице, кривость

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#257]
kurstip_ser.docx

![image](https://user-images.githubusercontent.com/18662965/57201058-379b0b80-6f9c-11e9-852e-04b5a94154d0.png)

**Comment by GloomlySeth** [comment]
я ничего не понимаю... Вчера всё было нормально....

Даже шрифт в подписи к таблице стал непонятным.

![image](https://user-images.githubusercontent.com/18662965/57201085-8e084a00-6f9c-11e9-82ba-6abb63eb8558.png)

Если эта версия и на проде, то срочно вернуть вчерашнюю

**Comment by Lyzgarik** [comment]
Влэд
