### ISSUE TITLE
Лишние пробелы в абзацах

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#260]
фигачит в некоторых абзацах пробелы. В исходном доке их нет

![image](https://user-images.githubusercontent.com/18488089/57458143-82a56f00-7279-11e9-894f-a99142af95d8.png)

**Comment by GloomlySeth** [comment]
Скорее всего Влад знак табуляции меняет на пробел...

**Comment by freedom00000** [comment]
Так и было
