### ISSUE TITLE
Ссылка не перенумеровалась. Лишние точки в конце абзаца

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#261]
kurstip_ser.docx

  Вопрос в скрине, косяк тоже.

![image](https://user-images.githubusercontent.com/18662965/57570705-8a961800-740d-11e9-9e62-b7dc47e83799.png)

**Comment by freedom00000** [comment]
1. да, из-за точки. она может быть только в конце предложения по условию. если убрать точку из исключения, то будут находится такие как "**рисунок 5.** 3"(которые мы уже обработали) и меняться на 5.5.3
2. исправил
