### ISSUE TITLE
Лишняя пробельная строка при оформлении рисунков

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#265]
sakovich_1.docx

![image](https://user-images.githubusercontent.com/18662965/57571685-cfc04700-7419-11e9-88ba-4054e0c7bef1.png)

**Comment by GloomlySeth** [comment]
сакович залип в обработке на нуле....

**Comment by freedom00000** [comment]
какой-то баг с процентами, обработка была успешной
