### ISSUE TITLE
Изменение параметров ячеек таблицы после обработки

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#271]
sodyl.docx

![image](https://user-images.githubusercontent.com/18662965/57575248-90ace880-744f-11e9-8124-2ac14edfea96.png)

**Comment by GloomlySeth** [comment]
я так понимаю, что Теперь все ячейки равновеликие? 

А слабо столбцы с текстом делать шире чем столбцы с цифрами? Если в таблице есть столбцы с цифрами.

**Comment by freedom00000** [comment]
вообще или только когда удаляем что-то ?

**Comment by GloomlySeth** [comment]
1) Когда удаляем что-то, нужно сохранить размер столбца номер 2. Появившееся за счёт удаление место добавить к текстовому столбцу. 

2) про вообще я подумаю, но пока нет.
