### ISSUE TITLE
Подпись к рисунку пропала

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#273]
sodyl.docx

![image](https://user-images.githubusercontent.com/18662965/57575319-e1711100-7450-11e9-840d-66f2ae014663.png)

Рисунок 3.4 = тоже самое

**Comment by freedom00000** [comment]
нет трие = нет подписи

**Comment by GloomlySeth** [comment]
Это баг. Должно работать иначе. Оно и работало иначе.
