### ISSUE TITLE
Нет точки в конце предложения

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#274]
sodyl.docx

![image](https://user-images.githubusercontent.com/18662965/57575349-4f1d3d00-7451-11e9-86eb-37d6bf3d0031.png)

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/57617295-239d6e00-7589-11e9-8f09-cc0f6f47a62e.png)
как и в оригинале ее нет. мы разве когда-то доставляли точки за юзерами ? кроме как оформления, ошибки исправлялись где-то еще ? могу, конечно, сделать, но опять же казусы будут 100 % где-то :)

**Comment by GloomlySeth** [comment]
Типа если будет ссылка внутри предложения прога дорисует точку. И получиться точка посреди предложения. Верно?

**Comment by freedom00000** [comment]
не только со ссылками можно, а просто дописывать точки или еще какие знаки в предложениях. но 100 % будут случаи, когда точка не нужна, а она поставится.
вообще это косяк юзера, пунктуация, но можно что-то придумать и ставить точки если это последнее предложение в параграфе, а следующий с большой буквы...ну или по-другому как-нибудь
