### ISSUE TITLE
Обычный текст становится приложением 

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#276]
было
![image](https://user-images.githubusercontent.com/18488089/57584120-8b4bae80-74e0-11e9-8d18-c2ab8e37a522.png)
стало
![image](https://user-images.githubusercontent.com/18488089/57584123-9ef71500-74e0-11e9-9f62-40ed6ddb5566.png)
P.S 
![image](https://user-images.githubusercontent.com/18488089/57584141-bb934d00-74e0-11e9-980a-b3552b2cd188.png)

**Comment by GloomlySeth** [comment]
что за файл?

**Comment by freedom00000** [comment]
1-6razdel.docx (это от юзера фидбэк, добавил его на тест)
он заменил слово "приложение" и бага не возникает
![image](https://user-images.githubusercontent.com/10418363/57618547-6ca2f180-758c-11e9-87c3-4223263ccf30.png)

**Comment by GloomlySeth** [comment]
Зато кавычки не заменились, если это скрин выходного файла.

**Comment by freedom00000** [comment]
нет, это оригинал

**Comment by GloomlySeth** [comment]
Пробовал прогонять абзацы начинающиеся со слова приложение? 

как то мы это сможем поровнять?

**Comment by freedom00000** [comment]
заставить людей писать капсом "приложение", точно так же как заголовки первого уровня. трудно отличить, когда оно оформлено "правильно"

**Comment by GloomlySeth** [comment]
А зачем мы ищем приложение в тексте.? Давай искать его только после того как Список литературы был. То есть игнорировать слово "Приложение", если оно встречается до списка использованных источников.

**Comment by freedom00000** [comment]
все в одном цикле, и не известно, будет ли что-то дальше найдено. получается надо еще раз пробегать по всему документу в поисках списка литературы и в дальнейшем приложений ( ++ время обработки)
