### ISSUE TITLE
Номер страницы с альбомной ориентацией

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#277]
Можно ли сделать так, чтобы номер страницы на листах с альбомной ориентацией не проставлялся? .( Или сделать его шрифтом белого цвета) 

![image](https://user-images.githubusercontent.com/18662965/57656367-d4832780-75e0-11e9-9393-bccb22190e05.png)

**Comment by freedom00000** [comment]
а в ворде это можно сделать? я не нашел (всегда ко всей сразу нумерации применяется)

**Comment by GloomlySeth** [comment]
Можно. Мотри скрин.

![image](https://user-images.githubusercontent.com/18662965/57980224-ff320d80-7a30-11e9-9a72-3d4f431263a3.png)

**Comment by GloomlySeth** [comment]
obschiy.docx

не сработало

![image](https://user-images.githubusercontent.com/18662965/58211179-e311c300-7cf3-11e9-8ac9-3f626cae2a88.png)

**Comment by GloomlySeth** [comment]
промахнулся

**Comment by GloomlySeth** [comment]
Работает. Это круто.
Теперь вопрос на засыпку. Номер страницы вставить как на скрине сможем?

![image](https://user-images.githubusercontent.com/18662965/58590137-17ddc700-826c-11e9-8adc-970990d28795.png)

**Comment by GloomlySeth** [comment]
Во какую штуку нашёл. Цифру можно повернуть.... 


![image](https://user-images.githubusercontent.com/18662965/61334761-a2d24b00-a833-11e9-9223-4efea7b200a5.png)

**Comment by GloomlySeth** [comment]
получиться применить хитрую функцию ворда из сообщения от 17 июля?

**Comment by GloomlySeth** [comment]
В каких требованиях работает?  По STP BSUIP на файле  obschiy_automag.docx не  сработало

![image](https://user-images.githubusercontent.com/18662965/64375290-3eab5680-d02e-11e9-89c8-066eb59b990e.png)

**Comment by freedom00000** [comment]
Оно не по требованиям работает, а просто везде в зависимости от расположения номера на нормальных станицах. Не проверил при работе с методом по переносу таблиц/рисунков и тд. Нашел другой баг, а с этим даже не знаю что
![image](https://user-images.githubusercontent.com/10418363/64379284-40c5e300-d037-11e9-96fc-349d9d985436.png)

**Comment by GloomlySeth** [comment]
Если Ты про слово "Глава" в заголовках первого уровня, то не парься. Этот документ я сначала обработал магистерскими требованиями, а потом снова затолкал в систему. Поэтому в заголовках это слово осталось. Не думаю, что кто-то будет это повторять. 


а Ты точно метод расстановки номера страниц включил в нужной версии - предыдущее замечание сохраняется
