### ISSUE TITLE
Таблицу сжало после обработки

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#278]
kurstip_ser.docx

БЫЛО
![image](https://user-images.githubusercontent.com/18662965/57657170-30e74680-75e3-11e9-8b20-ca731674de3d.png)

СТАЛО
![image](https://user-images.githubusercontent.com/18662965/57657220-4f4d4200-75e3-11e9-9bc4-6c1a13918938.png)

Почему её сплющило?

**Comment by freedom00000** [comment]
слишком широкая была 😄 
ну вообще страницы альбомные сделал, а вот все остальное затачивалось под книжные, поэтому ее сравняло к книжной

**Comment by GloomlySeth** [comment]
похоже пришло время  доравзвить этот метод.
