### ISSUE TITLE
Перенумерация рисунков. Неадекватность

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#279]
sodyl.docx

сверху есть рисунки, которые так же криво пронумеровались

![image](https://user-images.githubusercontent.com/18662965/57657758-fda5b700-75e4-11e9-857e-b88779c4a36f.png)

**Comment by freedom00000** [comment]
криво - это про руки юзеров. мало того, что рисунка 4.7 два, так еще и все слитно написал, и будто мало было, в конце предложения точку не поставил 🤦‍♂

**Comment by freedom00000** [comment]
#274 оказалась жизненно необходимой фичей, теперь есть (вроде все варианты предусмотрел, но всякое может быть)

**Comment by GloomlySeth** [comment]
1-6razdel.docx

![image](https://user-images.githubusercontent.com/18662965/57730765-d9f47680-76a1-11e9-9c7f-25050f995ced.png)

**Comment by freedom00000** [comment]
в слове "рис" буква 'p' - английская 
~~takaya vot norma~~ 🤦‍♂

**Comment by GloomlySeth** [comment]
тогда претензий нет
