### ISSUE TITLE
Время рендеринга. Вопрос. 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#280]
Можно ли увеличивать и уменьшать время на открытие и закрытие документа при обработке в зависимости от количества параллельных потоков?

**Comment by freedom00000** [comment]
нет ничего невозможного :)
нужен какой-то коэффициент или что-то в этом роде.

**Comment by GloomlySeth** [comment]
Каждый новый поток добавляет одну треть времени. То есть текущее время, выделенное на открытие и закрытие, должно увеличиться на одну треть.

**Comment by freedom00000** [comment]
формула такая: кол-во потоков * (6000 * 0.33)
6000 - время в мс, которое мы задали

**Comment by GloomlySeth** [comment]
Ты уменьшишь таки образом время 
6000*формула такая: кол-во потоков * (6000 * 0.33) - будет правильно, если упростить то

формула такая: кол-во потоков * (6000 * 1.33)

**Comment by freedom00000** [comment]
вообще я не уточнил, да.
это формула для добавочного времени. т.е. 6000 + формула
