### ISSUE TITLE
Удалить точку после цифры в начале абзаца

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#281]
![image](https://user-images.githubusercontent.com/18662965/57658398-77d73b00-75e7-11e9-90ab-92d2b12b3970.png)

**Comment by freedom00000** [comment]
может еще и списками делать их? и "-" тоже (сделал так)

**Comment by GloomlySeth** [comment]
Нет списком не делаем. Отдаём на откуп пользователю.  Цифры могут быть выставвленны через несколько абзацев. Если Ты захочешь сделать нумерованный список, то получишь неслабые проблемы. Просто мелкий приятный штрих. 

как Ты сделал с "-" я не понял.

**Comment by freedom00000** [comment]
если тире или дефис вначале параграфа(при условии что это обычный параграф с текстом, не заголовки и прочее), то делаю его списком

**Comment by freedom00000** [comment]
Поправил.
Теперь если идут хотя бы 2 подряд параграфа, начинающихся с цифр или тире/дефиса, они становятся списком.
Если это просто одиночный параграф с цифрой и точкой, убирается точка. Если параграф одиночный с цифрой и без точки, тогда он игнорируется
