### ISSUE TITLE
Сделать возможность размещения нумерации таблицы в отдельной строке

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#285]
ОБРАЗЕЦ:
![изображение](https://user-images.githubusercontent.com/18662965/57789227-2773f080-7741-11e9-889b-2f3160e5cb0f.png)

Считаем, что в Json будет приходить настройка в виде птички.

**Comment by freedom00000** [comment]
1 параграф выравнивание по правому краю, а 2 по центру?
Когда будет птичка? Там нужно все перелопатить в коде, чтобы нормально работало с "двухэтажной" подписью. Пока только железно могу сделать чтобы было...

**Comment by GloomlySeth** [comment]
Давай пока железно сделаем. 
1 параграф по правому краю 
2  по центру.

**Comment by GloomlySeth** [comment]
Создал требования - IZDAT

сейчас прикручено к MASTER
