### ISSUE TITLE
Приложение с листингом. Неадекватность

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#286]
kurstol2.docx

![изображение](https://user-images.githubusercontent.com/18662965/57789779-41fa9980-7742-11e9-9e5b-349c4dda785d.png)

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/57790057-b33a4c80-7742-11e9-9711-5bd0a8177a82.png)

**Comment by GloomlySeth** [comment]
так они подряд и идут. Или я ошибаюсь? Нет же между ними пробельных строк. И Ты их обработал - о чём значки говорят
