### ISSUE TITLE
Кусок таблицы пропал

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#290]
karakulko.docx

+ см. косяк на скрине. 

![image](https://user-images.githubusercontent.com/18662965/57999105-dbc49c80-7adc-11e9-937a-6f7d6efe865e.png)

**Comment by freedom00000** [comment]
#262 
сделал так, чтобы если две подряд с цифрами не удалялись, только когда одна среди текста
