### ISSUE TITLE
Нумерация таблиц и рисунков в приложении съехала

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#306]
shitik_attach.docx

В приложении таблицы и рисунки нумеруем в привязке к приложению - таблица А.1. + на скрине первая таблица в приложении

![image](https://user-images.githubusercontent.com/18662965/58303239-eee6ad80-7df7-11e9-8315-a5a56a39c0f5.png)

**Comment by GloomlySeth** [comment]
обработал магистерскими требованиями - тожесамое

**Comment by freedom00000** [comment]
Точно? Только что скачал с сайта документ, не обрабатывал заново
![image](https://user-images.githubusercontent.com/10418363/58357727-9f01f800-7e84-11e9-8655-880150aa0e33.png)
