### ISSUE TITLE
титульник не удалился

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#308]
puhova.docx

Удаляем всё до заголовков, которые есть в наших регулярных выражениях: "общая характеристика", "перечень условных обозначений", "введение"

![image](https://user-images.githubusercontent.com/18662965/58304495-2a37ab00-7dfd-11e9-95c9-cf6aa1136023.png)

**Comment by freedom00000** [comment]
в #259 не было таких слов, добавил
