### ISSUE TITLE
Почему рисунок пропал после обработки?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#309]
puhova.docx

  Он пропал не один в этом файле

![image](https://user-images.githubusercontent.com/18662965/58304818-8fd86700-7dfe-11e9-8fa7-cb62c8e8dc41.png)

**Comment by freedom00000** [comment]
1. ситуация на скриншоте
Там полностью жирная подпись, по этой же причине она стала заголовком (у нас же так и работает). Добавил проверку на подписи, чтобы они никогда не попадали в заголовки.
2. ситуация с рисунками, у которых внутри есть текст. 
Тут я не совсем понимаю что делать. В один объект вставлена подпись к рисунку и сам рисунок с обтеканием текста. Если изменить обтекание, то оно съезжает все, подпись остается вдалеке от рисунка

**Comment by GloomlySeth** [comment]
В новом положении по оформлению магистерских оказывается вся подпись к рисунку должна быть жирной.
   В  связи с этим нужно сделать, чтоб при  обработке заголовки второго уровня к строкам, которые начинаются с фразы "Рисунок Х.Х" не применялись свойства заголовка второго уровня. Ты так сделал?

  Даже если рисунок отрывается от подписи он исчезать не должен

**Comment by freedom00000** [comment]
Да, если начинается с "Рисунок Х.Х", то игнорируется.

**Comment by GloomlySeth** [comment]
а этот чего исчез?
![image](https://user-images.githubusercontent.com/18662965/58356624-b5a65000-7e80-11e9-8765-fd0a7340e55c.png)

**Comment by freedom00000** [comment]
Немного не стандартный рисунок, происхождение не ясно. Пропал на методах Павла(судя по его метке), я сегодня с ним возился, чтобы он не пропадал у меня.

**Comment by GloomlySeth** [comment]
спросить из какой проги она его вставила? Это оле объект?

**Comment by freedom00000** [comment]
не оле, до этого он вообще не распознавался как рисунок. внутри него есть текст (подпись), просто склееный рисунок + текст в одном контейнере. будто в предложении просто вставлено, как формула.
ну можно спросить, ради общего развития, но это не особо важно

**Comment by GloomlySeth** [comment]
Рисунки с якорем специально оставляешь? С умыслом? 

![image](https://user-images.githubusercontent.com/18662965/58440537-56944580-80e3-11e9-97d8-3f1fed879413.png)

**Comment by GloomlySeth** [comment]
Пухова Полина говорит, что это jpg...

**Comment by GloomlySeth** [comment]
Мы что-то можем сделать с якорем?

**Comment by GloomlySeth** [comment]
Или ничего не будем с якорем делать?

**Comment by freedom00000** [comment]
теперь такие картинки будут без якорей. ну и вообще они приводятся к одному виду (drawing, а было picture)
