### ISSUE TITLE
Уточнить алгоритм нумерации Рисунков и Таблиц

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#31]
Документ - ruk.polz_its_1514319363.docx

Нумерация рисунков и таблиц выполняется не так как ожидалось. Проверить как работает и либо исправить, либо оставить как есть и прописать в инструкции.

**Comment by Lyzgarik** [comment]
Что ожидалось, и что нужно проверять на данном этапе.
Если можно конкретики

**Comment by GloomlySeth** [comment]
Допилим индексы, шлифанём формулы. Будет конкретика. Эта таска для меня. Чтобы не забыть.

**Comment by Lyzgarik** [comment]
ок.
Я проверил, алгоритм там обычный, если смотреть на прошлые требования.
Позже разберём
