### ISSUE TITLE
Пустая глава почему появилась?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#311]
puhova.docx

![image](https://user-images.githubusercontent.com/18662965/58356319-d3bf8080-7e7f-11e9-81c6-3e2f755c3c82.png)

**Comment by freedom00000** [comment]
Потому что там структура не 1 за 1

Глава 1
*пустая строка*
Название

**Comment by GloomlySeth** [comment]
предлагаю в таких случаях приклеивать слово "Глава" к следующему за ним заголовку

**Comment by freedom00000** [comment]
Это здесь пустая строка, но что если будет целый раздел после слова этого? Юзер забыл назвать главу просто

**Comment by GloomlySeth** [comment]
если есть текст после этого слова - значит забыл назвать
если строка набранная большими буквами, значит вставил лишнюю строку
