### ISSUE TITLE
Подписи к таблицам. Неадекватность

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#315]
sakovich_1.docx

Явно была подпись к таблице и добавился в неё ещё один абзац

![image](https://user-images.githubusercontent.com/18662965/58358651-81cf2880-7e88-11e9-8fdc-4ee3dfeeac2c.png)

**Comment by freedom00000** [comment]
Тут явно какие-то уроды писали
![image](https://user-images.githubusercontent.com/10418363/58423318-79037000-809d-11e9-950d-8736e7f37b6f.png)
Красным - один элемент. По сути, это так и написано, как обработалось. Только как и обсуждали, заменил знаки эти на пробелы, т.к. они в середине текста

**Comment by freedom00000** [comment]
Пока так:
Если 2 раза подряд знак перехода на новую строку (в простонародье break), то считаем это символом конца параграфа.
