### ISSUE TITLE
Буквы означающие номер приложения в содержании оставляем большими

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#317]
![image](https://user-images.githubusercontent.com/18662965/58440079-58a8d500-80e0-11e9-82d7-6b92394afae5.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/58508542-ec3fdb80-819c-11e9-93a6-086756bbe08d.png)

**Comment by GloomlySeth** [comment]
не сработало

![image](https://user-images.githubusercontent.com/18662965/58590818-a272f600-826d-11e9-95cd-269ef76a3064.png)

**Comment by freedom00000** [comment]
hotfix
