### ISSUE TITLE
Непечатаемые пробелы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#32]
До начала запуска всех алгоритмов сделать замену всех неразрывных (фиксированных) пробелов на обычные пробелы. 

![image](https://user-images.githubusercontent.com/18662965/34407993-5887d002-ebd2-11e7-9e58-5d7f1ff930cd.png)

**Comment by freedom00000** [comment]
проверить, когда зальем на сервак

**Comment by freedom00000** [comment]
\+ удаление 2 и более пробелов по доку
