### ISSUE TITLE
Буквы в формулах становятся меньше

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#323]
pochti_horoshiy_fayl.docx

![image](https://user-images.githubusercontent.com/18662965/58508819-9fa8d000-819d-11e9-8369-c996306b9bf9.png)

**Comment by freedom00000** [comment]
Не знаю почему так, обработал только что и в этой формуле все буквы размера 14

**Comment by GloomlySeth** [comment]
он то рисует, что они 14 шрифта. Но Ты посмотри  внимательно. О ниж реально меньше

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/58556596-1046ff80-8225-11e9-9178-4abbbadf607e.png)
ну не знаю, вроде одинаковые (только курсивом отличаются)

**Comment by GloomlySeth** [comment]
pochti_horoshiy_fayl.docx

![image](https://user-images.githubusercontent.com/18662965/58665173-f4348280-8338-11e9-8943-fe876c4374c6.png)

аналогичная ситуация

![image](https://user-images.githubusercontent.com/18662965/58665231-175f3200-8339-11e9-9572-fa5c6c8db4c1.png)

**Comment by GloomlySeth** [comment]
Может разберёмся, что тут с формулами твориться?

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/61138749-aa5ec080-a4d0-11e9-8684-8661f6fe1670.png)
