### ISSUE TITLE
Таблицу при переносе на другую страницу перекосило

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#324]
pochti_horoshiy_fayl.docx

Чего её так покоробило? 

![image](https://user-images.githubusercontent.com/18662965/58509316-f1058f00-819e-11e9-939d-a88376766e91.png)

**Comment by pavel-moroz** [comment]
исправлена потеря строки
её принимало за шапку второй таблицы

не исправлено косое соединение.
Видимо из-за того что таблицы создавались отдельно их некорректно соединяет.
