### ISSUE TITLE
Буквы стали квадратиками

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#325]
pochti_horoshiy_fayl.docx

1) Вроде как обыкновенные буквы. В других шрифтах тоже есть такие же... 

![image](https://user-images.githubusercontent.com/18662965/58509586-8a34a580-819f-11e9-9eb9-cd1719a412a9.png)

2) На крайний случай. Можно ли сделать проверку и, если обработка преобразовала букву в квадратик, вернуть назад исходную букву.

**Comment by freedom00000** [comment]
это Cambria Math, специальный шрифт с такими вот буквами, которые используются по мнению создателей, в математике. При попытке заменить их на другой шрифт в ворде, ничего не выйдет и шрифт останется

**Comment by GloomlySeth** [comment]
а можем оставить без изменений?

**Comment by freedom00000** [comment]
теперь шрифт Cambria Math не заменяется на другой, если он был изначально в элементе
