### ISSUE TITLE
Неадекватная подпись к рисунку

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#328]
obschiy.docx
MASTER

Подпись к рисунку появилась в расшифровке формулы

![image](https://user-images.githubusercontent.com/18662965/58579303-6763c900-8253-11e9-8e14-9cd1ff74d5f0.png)

**Comment by Lyzgarik** [comment]
это ппц

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/58627211-4f398b80-82df-11e9-870e-2455720bf29a.png)
Такого я не видел еще...Раньше мы не определяли как рисунок его, и она была для нас что-то вроде пустой строки, которая удалялась. На фоне последних событий научились определять такие рисунки и вот результат
P.S. рисунок, сделанный средствами ворда

**Comment by Lyzgarik** [comment]
можно ещё добавить, для точного вида, что этой фигурой хотели нумеровать формулу, в игнор вбить сложно, мало ли что там может быть
![image](https://user-images.githubusercontent.com/18488089/58637563-69816280-82fb-11e9-92ea-e0e581e6442b.png)
(немного продублированная инфа, но всёж) 
P.S. интересный костыль для нумерации

**Comment by GloomlySeth** [comment]
Предлагаю вернуть как было. 
Все рисунки нарисованные средствами ворда, размещённые не в специальном поле для рисунка от Ворда, удалять нафиг
Либо второй вариант - не вставлять подпись к рисунку для рисунков сделанных в ворде, для которых пользователь не создал подписи к рисунку.  Типа если автор не назвал это рисунком, значит это не рисунок для нас.  Касается это объектов созданных средствами ворда

**Comment by GloomlySeth** [comment]
как сделали в итоге?

**Comment by Lyzgarik** [comment]
"Либо второй вариант - не вставлять подпись к рисунку для рисунков сделанных в ворде, для которых пользователь не создал подписи к рисунку. Типа если автор не назвал это рисунком, значит это не рисунок для нас. Касается это объектов созданных средствами ворда"
