### ISSUE TITLE
Интересный заголовок

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#329]
obschiy.docx

![image](https://user-images.githubusercontent.com/18662965/58579456-c32e5200-8253-11e9-914d-9a67b381419c.png)

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/58580240-5025db00-8255-11e9-9bde-82e865437470.png)
И как быть?

**Comment by GloomlySeth** [comment]
а Ты моешь их не склеивать? У Тебя ж между ними пробельная строка

**Comment by freedom00000** [comment]
так она почти всегда есть, если люди делают "третий уровень". мне кажется тут адекватный человек не будет делать такое, оно не логично пихать перед заголовком второго уровня третий
