### ISSUE TITLE
Вопрос о новом режиме работы сервера

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#331]
Можем ли мы сделать таким образом, чтобы сервер ничего в файле не трогал, только изменил заданные настройки?

Например: 
- Обработал только рисунки
- Обработал только таблицы
- только заменил тире
- только заменил кавычки
- только перенумеровал литературу

**Comment by freedom00000** [comment]
Можно, нужно только чтобы с сайта приходило это, что нужно и что не нужно
