### ISSUE TITLE
Настройка нумерации списка литературы не применилась

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#336]
требования IZDAT

![image](https://user-images.githubusercontent.com/18662965/59150839-6c363300-8a32-11e9-88b9-145bcc17c099.png)

**Comment by freedom00000** [comment]
в квадратных скобках вообще нет в списке,а у нас для стп и магистрской делается  в скобках :) 
(по поводу своего формата, я даже не знаю как это реализовать. допустим я хочу "@#33" формат, а кто-то еще просто "#", как мне это все распознать?)

**Comment by GloomlySeth** [comment]
Как Вариант. Если требования не СТП и приходит настройка с сайта, преобразуем весь список литературы в вордовский список и назначаем тип маркера, который запросил пользователь.  Вс это делаем на финальной стадии работы с литературой.

**Comment by freedom00000** [comment]
получается, что "свой вариант" это не нумерованный всегда?

**Comment by GloomlySeth** [comment]
Не совсем понял вопрос. 
применительно к нумерации в СТП БГУИР списка использованных источников у нас как раз свой вариант нумерации. Он должен был быть прописан в поле "Свой вариант" следующим образом - "[1]".

**Comment by freedom00000** [comment]
а как понять, что цифра должна становится на 1 больше? если указано [3] начинать с 3 должно или все 40 источников вначале с "[3]" ? этот вариант стандартный, лучше бы его добавить в стандартные, а вот римские думаю мало кому нужны....да и как я определю что там не римская, а просто символ или наоборот?
P.S. https://github.com/GloomlySeth/GOST/issues/199#issuecomment-495143784

**Comment by GloomlySeth** [comment]
про P.S. я понял.  Продолжаю пинать друпалистов. 

Про всё остальное не понял. У тебя полюбому список литературы будет начинаться с "1" и заканчиваться последним источником...

**Comment by freedom00000** [comment]
нет, не полюбому. сейчас же начинается с "[" потом цифра, потом "]". так же вместо цифры может быть буква, и может быть римская цифра (она же буква). Если это не нумерованый (каждый маркер повторяется просто), тогда понятно всё, но если он должен автоматически увеличиваться на +1 или следующая буква или вообще римская цифра, то я не понимаю как я должен всё распознать это.  допустим "а1l", что тут важнее?
