### ISSUE TITLE
Обработка формул. Неадекватность

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#337]
shitik_attach.docx

![image](https://user-images.githubusercontent.com/18662965/59387084-f18e5000-8d70-11e9-9732-c377e8901369.png)

**Comment by GloomlySeth** [comment]
второй пункт сохранился

puhova.docx

![image](https://user-images.githubusercontent.com/18662965/59635898-eebda180-915a-11e9-9a7d-d295ee35aafc.png)

**Comment by Lyzgarik** [comment]
дублируется с таской #344
