### ISSUE TITLE
Нумерацию ссылки на таблицу перекосило

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#343]
tushinski_soarce_2.docx

![image](https://user-images.githubusercontent.com/18662965/59389096-2a7cf380-8d76-11e9-9459-a1bc3070ed50.png)

  Вообще в этом документе на выходе  четыре таблицы с номером 2.1 и более шести таблиц с номером 4.1

В файле obschiy.docx подобная ситуация

**Comment by GloomlySeth** [comment]
1) Как видно из скрина сверху, нумерация таблицы в исходном файле по тексту и в подписи к таблице совпадает. Зачем мы тогда на выходе добавляем ещё одну ссылку на таблицу?

![image](https://user-images.githubusercontent.com/18662965/59636269-c71b0900-915b-11e9-9a93-cee9e5e5adb1.png)

**Comment by freedom00000** [comment]
документ просто ужасен для этой функции. и повторные номера, и рисунок за рисунком с 1 единственной подписью (а мы проверяем подпись следующего элемента или через один) я вообще не вижу смысла что-то фиксить в эту сторону, всё равно ведь не правильно будет. даже если нормально обработаются те, что единственные в своем роде, всё равно не факт что номер будет совпадать из-за дублированных 
>нормальные люди так не делают

**Comment by GloomlySeth** [comment]
Уговорил
