### ISSUE TITLE
Размер шрифта формул не применился

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#350]
obschiy_automag.docx

IZDAT

![изображение](https://user-images.githubusercontent.com/18662965/60337880-e8c28e80-99ac-11e9-93c0-631fab019a69.png)

**Comment by GloomlySeth** [comment]
а ещё такой есть косяк

![image](https://user-images.githubusercontent.com/18662965/60467120-534e2580-9c5e-11e9-8995-db8313644f83.png)

**Comment by freedom00000** [comment]
Ок, не заметил с таблицами просто)

**Comment by GloomlySeth** [comment]
внутри формулы с  последнего скрина по прежнему 14 шрифт
документ - shitik_attach_a5.docx

**Comment by freedom00000** [comment]
В оригинале эта формула в таблице с 1 ячейкой, которые мы не трогаем
