### ISSUE TITLE
Шрифт пояснений к рисунку поровнять

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#351]
shitik_attach_a5.docx

![image](https://user-images.githubusercontent.com/18662965/60466560-a58e4700-9c5c-11e9-9f31-f10febac5f57.png)

**Comment by Lyzgarik** [comment]
Раньше оно строго 12 выставляло, теперь привязал по типу "шрифт **САМОЙ ПОДПИСИ** (текст после тире) - 2"
