### ISSUE TITLE
Рисунок не вписался в поля

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#352]
shitik_attach_a5.docx

IZDAT

![image](https://user-images.githubusercontent.com/18662965/60466982-ee92cb00-9c5d-11e9-8943-b979dcadffd9.png)

Рисунок 5.12 тоже самое...

**Comment by GloomlySeth** [comment]
Павел, расписался в собственной беспомощности. 

 Можем ли мы все картинки такого вида конвертировать в jpg например. А потом уже пытаться вписывать в страницы?

**Comment by freedom00000** [comment]
~~Не понимаю какая разница будет jpg рисунок или bmp, png...~~
~~Велика вероятность, что и я распишусь в том же...~~

**Comment by GloomlySeth** [comment]
Сейчас это Оле объёкты. Павел не может ими управлять, поэтому и появилась такая задачка. 

Нужно погуглить конверторы из оле в jpg, png, bmp. Любой формат, который Пашин метод сможет масштабировать. 

Предлагаю Игорю с Ильёй подключиться и посодействовать.

**Comment by GloomlySeth** [comment]
Как сделал?

**Comment by pavel-moroz** [comment]
хмм, я ж уменьшал тоже эти параметры и не помогало

**Comment by pavel-moroz** [comment]
похоже я как-то по криворукому уменьшал
вродь работает

**Comment by freedom00000** [comment]
Я просто посмотрел как ворд это делает и сделал так же, единственное что не очень уверен с коэффициентом для уменьшения, время покажет:)

**Comment by pavel-moroz** [comment]
там коофициэтн от ширины и высоты пикселя зависит похоже как-то

**Comment by pavel-moroz** [comment]
поэтому я не привязывал величину в EMU к величине в пикселях
но в принципе это думаю прокатит.
Сейчас он чуток с запасом уменьшает, так что если пиксели(если я не ошибаюсь, то именно от них зависит коэффициент) не будут слишком отличатся то должно быть норм.
Потому что от ширины в пикселях, как я пробовал, высчитать это довольно проблематично в этих объектах.
