### ISSUE TITLE
Шрифт внутри таблиц поровнять

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#353]
obschiy_automag.docx

STP BSUIR

Должен быть 12, а по факту 14

![image](https://user-images.githubusercontent.com/18662965/60467452-5bf32b80-9c5f-11e9-885e-3a74dd5853e3.png)

**Comment by freedom00000** [comment]
в json приходят настройки 14 шрифта для таблиц, вот они и не 12
