### ISSUE TITLE
Настройка текста номеров страниц

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#355]
shitik_attach_a5.docx

В требованиях заказывал размер шрифта 10. На выходе имеем - 11. Что пиходит в json?

![image](https://user-images.githubusercontent.com/18662965/60468458-5a773280-9c62-11e9-82b2-03c98e069ce6.png)

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/60507833-baf18880-9cd1-11e9-83a3-e0e1dea4a98c.png)

я не знаю в чем проблема, но везде 10 стоит, в документе если открыть xml стоит 20 (нужно делить всегда на 2)
