### ISSUE TITLE
Вернём то, что пропало в формулах? 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#356]
shitik_attach_a5.docx

![image](https://user-images.githubusercontent.com/18662965/60468624-e7ba8700-9c62-11e9-8736-c12f0b804cee.png)

**Comment by GloomlySeth** [comment]
Так может назначить такой шрифт, чтобы старые ворды тоже его понимали?

**Comment by freedom00000** [comment]
Так там же times new roman

**Comment by GloomlySeth** [comment]
и что в шрифте изменилось, что ворд перестал распознавать буквы и символы этого шрифта в формулах набранных в ворде?  
Скорее всего русские символы. Ходя формулв набранные русскими буквами вроде распознаёт...

**Comment by freedom00000** [comment]
Это одному майкрософту известно, но факт есть. С 2016 ворда все нормально этим шоифтом. Искал инфу по версиям tnr , но не нашёл ничего. Скорее всего доработали отображение квадратов(если они есть, просто заменой на нормально отображаемый символ из другого шрифта, ну как вариант...это не открытое по, не известно как там)

**Comment by GloomlySeth** [comment]
а чего раньше было всё ок?

**Comment by freedom00000** [comment]
Ну в формулах ничего не менял в последнее время, кроме размера шрифта(теперь он просто не железно задан, а из настроек цифра берется. Маловероятна причина). Может и раньше был косяк тут?

**Comment by GloomlySeth** [comment]
Да. Этот косяк был и раньше
