### ISSUE TITLE
Заголовок второго уровня начат с новой страницы. А не должен был

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#359]
tushinski_soarce_2.docx

  Почему заголово второго уровня перенесен на новую страницу? Место-то есть. 

![image](https://user-images.githubusercontent.com/18662965/60706524-540ee200-9f12-11e9-86ad-40ce39a7c767.png)

**Comment by GloomlySeth** [comment]
А что было?

**Comment by freedom00000** [comment]
Ну оно переносило правильно, но из-за темповых значений под картинками, которые выставлялись в 14 шрифте, все съезжало
