### ISSUE TITLE
Пропали некоторые символы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#361]
pochti_horoshiy_fayl.docx

На входе вс есть

![image](https://user-images.githubusercontent.com/18662965/61084171-150eee00-a436-11e9-920a-70089e8cc19e.png)

**Comment by freedom00000** [comment]
в ворде 2016 и новее всё нормально. Перед таблицей эти символы шрифтом Cambria Math, а в таблице Times New Roman. Сделал чтобы и в таблице оставались Cambria Math, если  в исходном они такие
