### ISSUE TITLE
Перенос слов и символов на предыдущую строку абзаца

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#362]
pochti_horoshiy_fayl.docx

Абзацы, которые заканчиваются таким образом, как показано на скринах, нужно апгрейдить.  

![image](https://user-images.githubusercontent.com/18662965/61084310-599a8980-a436-11e9-8361-b62c1536263d.png)

![image](https://user-images.githubusercontent.com/18662965/61084354-7767ee80-a436-11e9-9baa-941ecdce13c7.png)

![image](https://user-images.githubusercontent.com/18662965/61084412-9cf4f800-a436-11e9-9f8d-9e2ed2b5b4b4.png)

**Comment by freedom00000** [comment]
как?

**Comment by GloomlySeth** [comment]
1) Если в строке меньше четырёх знаков включительно уплотнить текст на 0,1 пт 
2) Проверить.
3) Если не помогло, повторить п.1. до достижения уплотнения до 0,4 пт
