### ISSUE TITLE
Обработка списка списка литературы. Неадекватности 3

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#365]
literatura3.docx

### **1)** ✔️ 

![image](https://user-images.githubusercontent.com/18662965/61176869-00b32880-a5d1-11e9-8f26-4a2e9263151a.png)

### **2)** ✔️ 

![image](https://user-images.githubusercontent.com/18662965/61176938-3efd1780-a5d2-11e9-81c3-4f8a0e2ccebf.png)

Уточнения
![image](https://user-images.githubusercontent.com/18662965/61251627-b3b38b80-a763-11e9-8b7b-a002606f9899.png)

![image](https://user-images.githubusercontent.com/18662965/61251809-2de41000-a764-11e9-9485-6a04baa57ea3.png)

### **3)** коррелирует с 1 ✔️ 

![image](https://user-images.githubusercontent.com/18662965/61177015-cc8d3700-a5d3-11e9-8a48-91547a6c4bf0.png)

### **4)** ✔️ 

![image](https://user-images.githubusercontent.com/18662965/61251126-3cc9c300-a762-11e9-9a90-a47858363647.png)

**Comment by GloomlySeth** [comment]
### **1)** Косяк с пунктом 3 остался

![image](https://user-images.githubusercontent.com/18662965/62322837-a827ca80-b4ae-11e9-957d-adc85f0876c1.png)

2) как Ты сделал распознавание журнала в ссылке пункта 4? С указанной ссылкой порядок, а вот с похожими ссылками выше и ниже не проканало...

**Comment by freedom00000** [comment]
2. похожи они по какому признаку? в журнале из пункта 4 просто не находили регулярные выражения то, что надо, я дописал еще одно, которое определяло в том порядке, что в указано в источнике. возможно не все предусмотрел, поэтому 

> _было бы хорошо хотя бы номера этих источников, в оригинале. ну а идеально если бы я видел как надо чтобы было оформлено, не всегда понятно что там журнал, а что название и т.д._
