### ISSUE TITLE
Перенумерация рисунков. Неадекватность 2

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#369]
tushinski_soarce_2.docx

![image](https://user-images.githubusercontent.com/18662965/61247972-cd9ca080-a75a-11e9-958e-ac3c6cc9dcc9.png)

![image](https://user-images.githubusercontent.com/18662965/61248457-c6c25d80-a75b-11e9-88a4-5421050f4695.png)

![image](https://user-images.githubusercontent.com/18662965/61248662-38021080-a75c-11e9-931d-f13b881f4e92.png)

Сделал номера рисунков в разделе 4 уникальными (см. входной файл). Нет повторений. Номера идут:  9, 10, 32, 11 .... и т.д. На выходе с перенумерацией всё не очень хорошо..

![image](https://user-images.githubusercontent.com/18662965/61250502-86191300-a760-11e9-8786-e983b656bf09.png)

**Comment by freedom00000** [comment]
Для картинки №2
![image](https://user-images.githubusercontent.com/10418363/61314053-62a7a400-a804-11e9-88b8-46f43620d4d3.png)

**Comment by freedom00000** [comment]
всё равно в этом файле перенумерация бесполезна с большего, но что мог фиксанул
