### ISSUE TITLE
Обработку таблиц нужно подровнять

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#37]
1 )
![image](https://user-images.githubusercontent.com/18662965/34628400-408c8dfe-f275-11e7-9a5b-36249622de25.png)

2 ) проверять, есть ли точка вконце подписи и удалять её. То же самое и для рисунков.

**Comment by Lyzgarik** [comment]
bump

**Comment by GloomlySeth** [comment]
Не могу проверить из-за ошибки обработки.

**Comment by GloomlySeth** [comment]
Пункт 1 сделан - работает. 

Пункт 2 не сделан не работает.  Точка в конце подписи к таблице и в конце подписи к рисунку остаётся.

**Comment by GloomlySeth** [comment]
Обработка "съела" часть подписи к таблице
![image](https://user-images.githubusercontent.com/18662965/39289140-8b876832-4933-11e8-8c69-5c3b662085e1.png)

**Comment by GloomlySeth** [comment]
Нужно перепроверить.

**Comment by GloomlySeth** [comment]
Проверил скрин от 26 апреля актуален. Баг остался.  
Проверено на файле  "a12-3.docx"

С подписью к рисунку тот  же результат. Если есть тире в подписи к рисунку, то текст до тире исчезает при обработке Проверено на файле "a12-3.docx"

Происходит такое, когда после слова "Рисунок" или "Таблица" нет тире. Можно видеть в том же файле. 

Пункт 2 бага тоже актуален: см. документ - a12-4.docx

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/51232530-1922ed00-1978-11e9-8595-3aef586df462.png)
