### ISSUE TITLE
Пропали рисунки из приложения

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#371]
testkudinova19.docx

требования STP BSEU

С приложением А такая же ситуация

![image](https://user-images.githubusercontent.com/18662965/61328087-00aa6700-a823-11e9-9cef-691fcb1c4fb5.png)

**Comment by freedom00000** [comment]
Интересный файл, откуда он? На тесте нету...

**Comment by GloomlySeth** [comment]
Жонка зарегалась. он под её учёткой. Последний обработанный на сервере. Или подожди чуток я загружу в тест чуть позже

**Comment by freedom00000** [comment]
Лучше на тестовом тестить, он свежее и баги актуальные будут всегда

**Comment by GloomlySeth** [comment]
Рисунки то венулись, но подписи к рисункам очень кривые какие-то

![image](https://user-images.githubusercontent.com/18662965/61407933-8f80b780-a8e7-11e9-806c-5667964c11e6.png)

**Comment by freedom00000** [comment]
Ну баг же был с пропаданием рисунков :)
P. S. Уже сообщил про это мастеру над подписями
