### ISSUE TITLE
Квадратики в тексте посреди слов отчего?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#373]
testkudinova19_1.docx

STP BSEU

![image](https://user-images.githubusercontent.com/18662965/61407745-1e410480-a8e7-11e9-95d9-80ede00495d5.png)

**Comment by freedom00000** [comment]
они и в оригинале есть, только сплющены (на жирном видно лучше, поэтому сделал верхнюю строку такой как и подпись к таблице)
![image](https://user-images.githubusercontent.com/10418363/61876315-3f13e600-aef5-11e9-8ff4-5e34896fe891.png)
Под лупой практически просматривать надо :)
![image](https://user-images.githubusercontent.com/10418363/61876404-771b2900-aef5-11e9-8085-191621e0d745.png)

ཾ - вот этот символ 
(![image](https://user-images.githubusercontent.com/10418363/61876554-cfeac180-aef5-11e9-8f0a-9a9b62e93f62.png))
называется TIBETAN SIGN RJES SU NGA RO
Относится к символам, вставляемым для комбинирования с другими символами (например акценты, умляуты, оборачивающие скобки)
### **У нас больше не будет такого...**
