### ISSUE TITLE
Лишнее тире в подписи к таблице

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#376]
otchet_na_obrabotku

![image](https://user-images.githubusercontent.com/18662965/61748547-24345b00-ada9-11e9-8aec-65960844170b.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/61909508-05fe6480-af3b-11e9-837c-a90d64f83d76.png)

**Comment by freedom00000** [comment]
А это настройка или железно?

**Comment by GloomlySeth** [comment]
это настройка. Но в браузее невозможно поставить разные тире. Поэтому с игорем был уговор, что если приходит "1.1 - " , вместо дефиса рисуем тире

**Comment by GloomlySeth** [comment]
STP BSUIR

![image](https://user-images.githubusercontent.com/18662965/61980596-dcf3d780-afff-11e9-9228-210ae611c127.png)

**Comment by freedom00000** [comment]
https://github.com/GloomlySeth/Bugtreking-SGOST/issues/376#issuecomment-515220418
всё правильно, не приходит "1.1 -", значит дефис
