### ISSUE TITLE
Рисунки неверно оформились

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#378]
tushinski_soarce_2.docx

требования - MAGISTER

![image](https://user-images.githubusercontent.com/18662965/61936574-b26d3480-af95-11e9-8107-362d547f52e3.png)

ещё косяк

![image](https://user-images.githubusercontent.com/18662965/61936992-8d2cf600-af96-11e9-929f-5c7d77bd72c7.png)

**Comment by GloomlySeth** [comment]
STP BSUIR - тире в подписи к рисунку. 

Переароверить по таблицам и рисункам во всех требованиях, которые у нас имеются. Потом ставить зелёную метку

![image](https://user-images.githubusercontent.com/18662965/61980717-38be6080-b000-11e9-8da8-a9a53af7869d.png)

**Comment by freedom00000** [comment]
https://github.com/GloomlySeth/Bugtreking-SGOST/issues/376#issuecomment-515220418
ситуация та же

**Comment by GloomlySeth** [comment]
С тире вопрос снят

а это нужно ровнять
tushinski_soarce_2.docx


![image](https://user-images.githubusercontent.com/18662965/61981858-90120000-b003-11e9-9dfe-e6c890b2fe7e.png)

**Comment by GloomlySeth** [comment]
изменил настройки 

![image](https://user-images.githubusercontent.com/18662965/61982374-3a3e5780-b005-11e9-9bf9-593755755346.png)

не помогло ни с таблицами ни с рисунками

![image](https://user-images.githubusercontent.com/18662965/61982407-517d4500-b005-11e9-892d-1d7058918f43.png)

**Comment by freedom00000** [comment]
https://github.com/GloomlySeth/Bugtreking-SGOST/issues/378#issuecomment-515604799
ну правильно, потому что я думал это настройка, а не юзер сам вводит в поле. после "-" был пробел, а в других настройках не было, с чем я и сравнивал. лучше чтобы настройка была одинаковой везде, а не в одних требованиях одна и та же настройка это "1.2 -", а в других это "1.3 - " и тд
(p.s обрезал строку с двух сторон при сравнении по пробелам, но всё же лучшее однообразно чтобы было)
(p.p.s но могу сделать чтобы было просто вида " х.х - " через регулярные выражения, но нужно ли?)

**Comment by GloomlySeth** [comment]
Буду стараться делать единобразно. Без пробела при формировании настроек
