### ISSUE TITLE
Что-то с кавычками

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#379]
tushinski_soarce_2.docx

![image](https://user-images.githubusercontent.com/18662965/61936886-4939f100-af96-11e9-817f-043573b4f2fd.png)

**Comment by freedom00000** [comment]
очень это редко, наверное, когда после  кавычек сразу восклицательный знак, ну да ладно.
добавил в регулярку любые виды пунктуационных символов, что не являются точками, скобками, кавычками или соединителями
