### ISSUE TITLE
Непонятка с авторами в патентах и нумерацией

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#393]
1) какой-то странный номер у источника литературы между источниками 146 и 148. И почему-то 148 раньше чем 146. Там всё в порядке с нумерацией? 

2) ![image](https://user-images.githubusercontent.com/18662965/63466714-83e75a00-c46c-11e9-9112-8dc48f0fbed4.png)

**Comment by freedom00000** [comment]
Честно говоря, там с авторами типа Максим Иванович(и подобными, в т.ч. англ) проблемы будут...Ну просто это не похоже на имя только, еще может быть и контора какая в 2 слова с большой буквы, ну типа Google Corporation. Почему-то они так пишутся, каждое с большой буквы.
![image](https://user-images.githubusercontent.com/10418363/63504858-19b9ce00-c4db-11e9-9a70-7f15d9669df6.png)

> А нумерацию + сортировку просто выключил, чтобы не искать среди кучи источников и забыл обратно  включить :)


Поправил "слипание", имя автора в названии, нумерацию и сортировку.

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/63641759-5c86cc00-c6bc-11e9-8856-6c583a913c33.png)
