### ISSUE TITLE
Перенумерация и добавка ссылки на рисунок в тесте сломалась

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#396]
shitik_attach.docx

![image](https://user-images.githubusercontent.com/18662965/63470862-628b6b80-c476-11e9-8545-7c0f6870f79d.png)

**Comment by freedom00000** [comment]
Не знаю что было, но оно само исправилось

**Comment by Lyzgarik** [comment]
@freedom00000 классика
