### ISSUE TITLE
Перенос таблиц. Ещё один вариант

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#399]
Сейчас перенос таблиц у нас реализован с применением "умной" шапки. Нужно реализовать ещё и такой вариант переноса таблиц, как на картинке. То есть не умной шапкой а строкой с номерами столбцов

![image](https://user-images.githubusercontent.com/18662965/63641476-cd77b500-c6b7-11e9-8270-3e65c3d11e45.png)

Для меня - учесть в настройках Формирования требований

**Comment by freedom00000** [comment]
Поставил шапку такую пока по умолчанию

**Comment by GloomlySeth** [comment]
Можно чтобы было только в требованиях IZDAT BSUIR

**Comment by freedom00000** [comment]
Любыми, потом исправлю для конкретных

**Comment by GloomlySeth** [comment]
нужно шлифовать...


![image](https://user-images.githubusercontent.com/18662965/63888690-2a40db80-c9e8-11e9-89c5-e6b2c902bfdb.png)

**Comment by freedom00000** [comment]
В двойных не совсем знал как делать. Тоже двойную или по последней строчке?

**Comment by GloomlySeth** [comment]
по последней строчке тоже может быт косяк. Нужно по последней строчке на странице до переносимой части

**Comment by freedom00000** [comment]
А это будет правильно? Допустим в гапке 8 ячеек, но в середине как-то итог начался, там просто две ячейки. Это нормально или в любом случае ошибка изначально?

**Comment by GloomlySeth** [comment]
Это экзотический случай. Как правило итоги в самом конце таблицы бывают. 

По хорошему нужно по шапке ориентироваться. Сколько в шапке подписанных колонок, столько цифр и делать.

**Comment by freedom00000** [comment]
По шапке сейчас и есть
