### ISSUE TITLE
Ссылки на таблицы в тексте. Всё в порядке? 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#408]
obschiy_automag.docx

![image](https://user-images.githubusercontent.com/18662965/64404671-52ce7280-d085-11e9-9ca6-74a412ac8f7a.png)

**Comment by freedom00000** [comment]
Долго не мог понять в чем проблема, пока не заглянул в оригинал
![image](https://user-images.githubusercontent.com/10418363/64431891-05252a80-d0c4-11e9-977a-a0be79092230.png)
А что ожидать, когда там эта ссылка есть? Ну и таблица 6.3 ниже тоже присутствует, всё в порядке.

**Comment by GloomlySeth** [comment]
Тогда где добавка ссылки на таблицу 6.2?

**Comment by freedom00000** [comment]
Она есть и без меня в тексте до таблицы
