### ISSUE TITLE
Часть названия книги попало в авторы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#409]
kurstip_ser.docx

![image](https://user-images.githubusercontent.com/18662965/64485110-c65ab600-d224-11e9-8b3a-b9301810bb57.png)

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/64516183-b8756580-d2f6-11e9-9471-87a3026512e9.png)
ну, судя по всему, тут И.Г. Теория больше на автора похож, чем просто Шупейко. Инициалы от него отделены запятой и никакого отношения к нему не имеют 😄 
Если серьезно, то если добавить запятую как вариант точки(что вообще не логично, после фамилии вообще хоть какой-то знак препинания), то несколько фамилий _"М. К. Пупкин, И. Г. Шупейко, С. С. Петров "_ в таком стиле, будут иметь не правильные инициалы (хотя вроде оформлено верно)

**Comment by GloomlySeth** [comment]
Ты когда на выходе комплектуешь книгу, ты должен оформить таким дебильным способом, как на этом скрине. И соответственно на входе она, книга, тоже может быть оформлена по этому способу. 

Кто, когда и как это придумал я не знаю. Но мы Теперь вынуждены поэ этот дебилизм подстраиваться

**Comment by freedom00000** [comment]
Действительно, ума ему не занимать, кто это придумал. Разделять имя человека хоть как-то было лучшим решением в его жизни.
Но если честно у меня идей не много, не факт что будет работать везде хорошо
