### ISSUE TITLE
Перенос символов на предыдущую строку не работает

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#412]
tushinski_soarce_2.docx

![изображение](https://user-images.githubusercontent.com/18662965/64805116-fa253b00-d598-11e9-880c-9cfc19cbc2e5.png)

**Comment by freedom00000** [comment]
У меня это выглядит так (пробовал и у себя и через сервер), не знаю в чем была проблема. Я обновил на всякий еще раз сервер
![image](https://user-images.githubusercontent.com/10418363/64852371-eeca2200-d621-11e9-85eb-22640514e815.png)
