### ISSUE TITLE
Нет пробельной строки до подписи к таблице

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#413]
tushinski_soarce_2.docx

![изображение](https://user-images.githubusercontent.com/18662965/64805218-3789c880-d599-11e9-8873-0208735d4775.png)

**Comment by freedom00000** [comment]
У меня это выглядит так (пробовал и у себя и через сервер), не знаю в чем была проблема. Я обновил на всякий еще раз сервер
![image](https://user-images.githubusercontent.com/10418363/64852324-d2c68080-d621-11e9-8588-a76ef30faafb.png)
