### ISSUE TITLE
Что-то с обработкой рисунков и переносом таблиц

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#414]
tushinski_soarce_2.docx

![изображение](https://user-images.githubusercontent.com/18662965/64805280-6142ef80-d599-11e9-811e-4eb78901e14e.png)

![изображение](https://user-images.githubusercontent.com/18662965/64805362-94857e80-d599-11e9-8f38-4f35fcb851dd.png)

**Comment by freedom00000** [comment]
У меня это выглядит так (пробовал и у себя и через сервер), не знаю в чем была проблема. Я обновил на всякий еще раз сервер
1
![image](https://user-images.githubusercontent.com/10418363/64852428-099c9680-d622-11e9-9599-86499c52041b.png)
2
![image](https://user-images.githubusercontent.com/10418363/64852537-3b156200-d622-11e9-8fd3-a73a413d1949.png)

**Comment by GloomlySeth** [comment]
а такая таблица у тебя как выглядит? 

![image](https://user-images.githubusercontent.com/18662965/64883807-e0ebbf80-d668-11e9-8593-d0df5d549f76.png)

**Comment by freedom00000** [comment]
точно так же
