### ISSUE TITLE
Мониторинг активности пользователей

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#415]
Нужно сделать .csv или эксель файл с информацией о пользователях и обрабатываемых файлах. В таблицу попадают файлы более 50 страниц, файлы которые привели к ошибке. 

  Поля в таблице:
  -  Имя пользователя
  -  ID пользователя
  -  название файла 
  -  количество страниц в файле
  -  сколько раз был обработан файл

**Comment by GloomlySeth** [comment]
куда файл складываешь?

**Comment by freedom00000** [comment]
Рядом с .ехе приложения, report.csv
