### ISSUE TITLE
Оформление таблиц в англоязычной версии подправить

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#417]
1_td3do.docx

![image](https://user-images.githubusercontent.com/18662965/66718977-9dfd4300-edf2-11e9-9a2e-2e7e5c40d369.png)

Ссылка на таблицу не добавилась

**Comment by freedom00000** [comment]
https://github.com/GloomlySeth/Bugtreking-SGOST/issues/376#issuecomment-515220418
в настройках дефис вообще не указан, если что :)
