### ISSUE TITLE
Оформление рисунков в англоязычной версии поправить

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#418]
1_td3do.docx

![image](https://user-images.githubusercontent.com/18662965/66719033-57f4af00-edf3-11e9-9323-8b686092f1c1.png)

Проверить как работает добавление ссылок на таблицы

**Comment by freedom00000** [comment]
1 "рис" теперь берется из настроек

**Comment by freedom00000** [comment]
1 "рис" теперь берется из настроек
2 тире - https://github.com/GloomlySeth/Bugtreking-SGOST/issues/376#issuecomment-515220418
3 ссылки на рисунок добавляются
4 "содержание" так и приходит в настройках, я его только в верхний регистр перевел
5 "введение" у нас добавляется, если нет его в доке, но никаких настроек нет для этого. Тут либо делать настройку на каком языке документ оформлен, либо сразу присылать как должно быть, хоть на китайском
6 для таблиц тоже работает
P/s пока в ссылках сокращения делаются так : для рисунков берется 3 первых символа из настроек, а для таблиц 4 (например приходит: "таблица" - будет "табл", "table" = "tabl", "figure" = "fig"). Будут настройки может когда-нибудь приходить нормально, тогда можно будет прямо оттуда брать. (вариант с языком документа в настройках или полностью настройки для всего)

**Comment by GloomlySeth** [comment]
Что мне писать в настройках, чтобы сервак понимал, что нужно ставить тире, а не дефис?

**Comment by freedom00000** [comment]
"1.1 -" - дефис
"-" (минус)  - это минус/тире
все без кавычек

**Comment by GloomlySeth** [comment]
ещё раз. что бы было тире я пишу в строке 
1.1 - - минус

так ?

**Comment by freedom00000** [comment]
ну в 1ой строке то что в кавычках это дефис (длинный)
если что то другое, то будет минус (короткое тире)

**Comment by GloomlySeth** [comment]
запутал меня. Я в этом окошке могу написать только так "1.1 - ". В этом окошке ничего кроме дефиса (минуса) поставить нельзя.
   "1.1 - " вот такая запись, что будет означать в настройках?

**Comment by GloomlySeth** [comment]
Чтобы сервер везде в номерах рисунков сделал тире нужно в настройках сделать такую запись
 "1.1 -" 
Верно?
