### ISSUE TITLE
Нужны предложения

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#419]
Может быть есть предложения по фронту для этой вкладки настроек?  Или может быть прототипы? 

![изображение](https://user-images.githubusercontent.com/18662965/66748075-e4a07b00-ee8e-11e9-9887-a7884f3ab13d.png)

**Comment by freedom00000** [comment]
Могу предложить интерактивный конструктор с переменными:

{%!(Xxx)...%} - переменная, если !, то обязательная (при отсутствии сообщение об ошибке).
       Переменные: Author1FIO, Author1IOF, AuthorsFIO, AuthorsIOF - авторы первый и список
     Аналогично: Editor1FIO, Editor1IOF, EditorsFIO, EditorsIOF,
          Translator1FIO, Translator1IOF, TranslatorsFIO, TranslatorsIOF.
          Caption, Annotate, Other, URL - текстовые строки названия,
             PubName, PubCity, PubYear - название, город и год издателя,
          VolCurr, VolCnt, VolNF, VolNB - номер тома, всего томов и обозначение тома (т.|ч.|v.) полное и сокращённое,
                 Counter - счётчик,
            PagesCnt - страниц всего,
              DiskType, DiskName, DiskCnt - тип и количество дисков,
          Edition, ISBN - № издания, ISBN,
              AccessDate - дата доступа,
                  ArticlePages - номера и страницы в журналах,
               MagazineName - название журнала.
        {?(XXX)...?} - условие. Вложенные допускаются, но работа полностью не отлажена.
    Если условие истинно, то обрабатывается содержимое строки до ограничителя, иначе оно игнорируется.
 Условия: ([E|N] XXX) - переменная определена (E) или нет (N)
          (XXX op <число>) больше, меньше, равно и т.д., число только натуральное. Только для числовых значений.
 op: == != < > <= >=
 Переменные для проверки: выше перечисленные плюс:
           AuthorsCnt, EditorsCnt, TranslatorsCnt - количество определённых авторов, редакторов и т.д.,
           AuthorsM3, EditorsM3, TranslatorsM3 - для авторов, редакторов и переводчиков было [и др.],
           UnderEdition - было [под ред.],
MagazinesCnt - число журналов.

Пример:

> "[{%Counter%}] {?(N AuthorsM3) {%!Author1FIO%}?} {%!Caption%}{?(E Annotate) : {%!Annotate%}?}. {?(VolCnt>0) В {%VolCnt%} т.?} / {?(AuthorsCnt <= 3){%!AuthorsIOF%}?}{?(AuthorsCnt > 3){%!Author1IOF%} [и др.]?}.{%EditorsIOF%}. – {%!PubCity%} : {%!PubName%}, {%!PubYear%}.{?(VolCnt>0) {?(VolCurr > 0) – Т. {%VolCurr%}.?}?}{?(N VolCnt) {?(N VolCurr) – {%!PagesCnt%} с.?}?}"

Как это реализуют графически на фронтенде зависит от фантазии и опыта, наверное...

**Comment by GloomlySeth** [comment]
Твоё предложение учитывает, что нужно управлять расстановкой пробелов, запятых слешей и других  символов? В одном требовании их нужно расставлять так в другом иначе

**Comment by freedom00000** [comment]
Да, все что вне фигурных скобок - статическое. В примере видно, что там есть запятые, слеши. По желанию их можно убрать или поставить любые символы
