### ISSUE TITLE
Длинные тире не стали тире обыкновенными

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#426]
1_td3do.docx

![image](https://user-images.githubusercontent.com/18662965/72204638-55096900-348b-11ea-95cc-5e2cbde61694.png)

**Comment by freedom00000** [comment]
из-за поиска исходного кода, там были ключевые слова if/for/is и т.д.
для English STP выключил, там не будет работать так как задумывалось в русском языке
