### ISSUE TITLE
По сборникам и общим докам

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#431]
1) Если выпадает такая таблица с авторами, не трогаем. 
Кидают ещё иногда с пустыми ячейками вначале.

![image](https://user-images.githubusercontent.com/18488089/74645530-32085e00-5189-11ea-9b56-269157fe1baa.png)
![image](https://user-images.githubusercontent.com/18488089/74646280-92e46600-518a-11ea-8167-a0ac3ade636e.png)

@freedom00000 перекинь плез Мержер доков к нам, не могу его норм из того транка подтянуть на пеке

2) больше вопрос, прога же могёт обрабатывать англ список литературы?

**Comment by Lyzgarik** [comment]
@Hehalf по первому через шапку статьи решили обойти. 
Т.Е. Параграфы между *УДК* параграфом и параграфом ключевые слова/Аннотации - шапка статьи

**Comment by Lyzgarik** [comment]
@freedom00000 как оно?
P.S. добавь в телеге..

**Comment by GloomlySeth** [comment]
На Влада пока не рассчитывайте. Делайте сами по максимуму. Он сейчас доводит до ума глазницы.

**Comment by Lyzgarik** [comment]
ок

**Comment by Lyzgarik** [comment]
Job Done
