### ISSUE TITLE
SetTitles - Непонятный выход за пределы массива

### ISSUE THREAD

**Issue by ghost** [GloomlySeth/Bugtreking-SGOST#432]
![image](https://user-images.githubusercontent.com/33635031/74649090-f4f39a00-518f-11ea-8568-3d63893c372f.png)

**Comment by ghost** [comment]
Был пойман при полной загрузке с нуля из SVN

**Comment by freedom00000** [comment]
очевидно, в настройках нет настроек (ага) для тайтлов 2го уровня

**Comment by Lyzgarik** [comment]
Закинул настройки, должно быть норм
