### ISSUE TITLE
Таски по сборникам УДК

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#437]
1) Склейка параграфов названия 
2) Сами параграфы названия находятся между строкой "УДК" и таблицей ФИО 
3) Поправить нынешние регулярки для поиска подписей рисунков

**Comment by GloomlySeth** [comment]
Игорь - позакрывай неактуальные задачки, которые созданы Тобой

**Comment by Lyzgarik** [comment]
Done
