### ISSUE TITLE
Дополнения в обработку документов

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#438]
Добавляем распознавание и оформление разделов документа отмеченных зелёным на скрине

![image](https://user-images.githubusercontent.com/18662965/77680350-e37a8a80-6fa4-11ea-8ad7-51a70e9386bc.png)

   Заголовки этих разделов оформляем, как оформлено "Введение". Сервер должен адекватно обрабатывать эти элементы, если они поданы на вход.

**Comment by freedom00000** [comment]
Содержание удаляется у нас в самом начале

**Comment by GloomlySeth** [comment]
Это я помню. Потом-то вставляется.

**Comment by GloomlySeth** [comment]
Где проверять? На проде?  или в тесте?

**Comment by freedom00000** [comment]
Прод

**Comment by GloomlySeth** [comment]
1) Пропала автоматическая вставка структурного элемента "ВВЕДЕНИЕ" и слов "Пропишите введение" красными буками. 

2)  Можно ли вставлять содержние после "Списка исполнителей" и "Реферата". Эти структурные элементы в содержание не пихаем. Содержание начинается с  "Термины и определения"

**Comment by GloomlySeth** [comment]
sakovich_1.docx

![image](https://user-images.githubusercontent.com/18662965/78752083-1563f780-797c-11ea-9fe8-eb37f5844c49.png)

Реферат до содержания размещаем. Возможно?
