### ISSUE TITLE
Ошибка при обработке таблицы с рисунком в первой ячейке

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#439]
По алгоритму, который я помню, если встречается таблица с рисунком в ячейке номер 1, то мы эту таблицу не считаем таблицей. Не присваиваем ей номер, а содержимое таблицы не форматируем. 
   Почему не сработало в этом случае? 

![image](https://user-images.githubusercontent.com/18662965/78264874-643d0780-750c-11ea-85b7-f0d95abc8fd9.png)

**Comment by freedom00000** [comment]
что за документ?

**Comment by GloomlySeth** [comment]
Его нет нигде. Это работа над сборниками. 
Это к Игорю таска. Он там много чего комментировал. Поэтому возможно просто нужно включить где-то что-то
