### ISSUE TITLE
Ситуация, когда нужно переносить всю таблицу с подписью

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#451]
Пухова

![image](https://user-images.githubusercontent.com/18662965/78898939-4f68f280-7a7d-11ea-859b-b348fd9ce657.png)

У нас вообще есть настройка при переносе, шапку делать или номера колонок?

**Comment by freedom00000** [comment]
Настройка есть. Там что-то типа полная шапка или нет. Не полная - с номерами

**Comment by GloomlySeth** [comment]
И какая настройка сейчас приходит по STP BSUIR?
