### ISSUE TITLE
4 символа в предыдущую строку работает?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#453]
mazur_for_s_2.docx

![image](https://user-images.githubusercontent.com/18662965/79018687-1a43c980-7b7d-11ea-8b29-d625194dde5d.png)

Или мы его выключили?

**Comment by freedom00000** [comment]
выключен, потому что много багов вызывает

**Comment by GloomlySeth** [comment]
может попросить автора пофиксить?

**Comment by GloomlySeth** [comment]
Можешь расписать какие он баги вызывает?

**Comment by freedom00000** [comment]
я не помню какие именно и в каких документах, но часто он просто зацикливается на одном месте

**Comment by GloomlySeth** [comment]
Содыль

![image](https://user-images.githubusercontent.com/18662965/86116345-ede17e80-bad5-11ea-84a3-99bacbbe29a6.png)

**Comment by freedom00000** [comment]
я не включал

**Comment by GloomlySeth** [comment]
включай. На тесте вроде норм было. Ничего не ломалось и лишнего не ужималось
