### ISSUE TITLE
Распознавание книг развить в источниках литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#455]
mazur_for_s_2.docx

Если имеются слова под "общей редакцией" перед фамилией автора, не требовать фамилию автора в начале ссылки

![image](https://user-images.githubusercontent.com/18662965/79019767-bd95de00-7b7f-11ea-9357-65355c711ffb.png)

**Comment by GloomlySeth** [comment]
дополняем ситуацией, когда написано "под редакцией"

![image](https://user-images.githubusercontent.com/18662965/79129040-2e6e0d80-7dad-11ea-83ef-4c60ba501007.png)

**Comment by freedom00000** [comment]
да, было условие только для "под общей редакцией" 😄

**Comment by GloomlySeth** [comment]
Растём... В том числе и над собой. :)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/79309752-7bfc8e80-7f03-11ea-8f7a-f28196e19b8a.png)
