### ISSUE TITLE
Перенос таблицы и не только не произошёл

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#458]
shitik_attach.docx

![image](https://user-images.githubusercontent.com/18662965/79132977-f28a7680-7db3-11ea-8900-70d0b10fa1a4.png)

![image](https://user-images.githubusercontent.com/18662965/79133136-30879a80-7db4-11ea-8528-6cd6babd7382.png)

**Comment by GloomlySeth** [comment]
Бага актуальна. Только что проверил. Раздел 6 - таблицы не перенеслись!

**Comment by freedom00000** [comment]
Скорее всего времени не хватает, я там уменьшал чтобы не так долго ждать. Совпадает по месту в документе(конец)
