### ISSUE TITLE
Лажа при повторной обработке

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#461]
obschiy_automag.docx

Мы хотим, чтобы пользователь видел это при повторной прогонке фала? 

![image](https://user-images.githubusercontent.com/18662965/79334080-52099300-7f28-11ea-800a-15bcd4350c67.png)

**И таблицы в этом файле не перенеслись как положено**

**Comment by freedom00000** [comment]
была ошибка, флаги остались, тут просто должна была быть "-1"
