### ISSUE TITLE
Реально сделать, чтоб таблицу не перекосило после обработки?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#466]
pochti_horoshiy_fayl.docx

![image](https://user-images.githubusercontent.com/18662965/79773879-ab176380-833a-11ea-81e9-5a25e1de19e9.png)

**Comment by freedom00000** [comment]
Конкретно в этом случае кривой кусок от другой таблицы - 3.5 (это часть бага, когда формулы склеивались)

**Comment by freedom00000** [comment]
Сделал. Вроде работает, но может где-то не сработать, в каких-то специфических таблицах
