### ISSUE TITLE
Лишние Главы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#468]
tushinski_soarce.docx

Если всё большими буквами, это элемент списка, то заголовком первого уровня его не делаем. 

![image](https://user-images.githubusercontent.com/18662965/79979456-36633700-84aa-11ea-8a0d-7c8e1025a54d.png)

Раньше такого косяка небыло. Похожая ситуация как и с "где" в формулах

**Comment by freedom00000** [comment]
всегда было, если целый параграф большими буквами = заголовок первого уровня

**Comment by GloomlySeth** [comment]
Неа. Что-то у меня в памяти загвоздка,  что мы с ИГорем как-то ээтот косяк решали. Возможно даже так же как я сейчас предложил
