### ISSUE TITLE
Введение вставилось после раздела 1

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#472]
kovalevich.docx

STP BSEU

![image](https://user-images.githubusercontent.com/18662965/80084171-2ce7d680-855f-11ea-8946-9193ff625653.png)

**Comment by GloomlySeth** [comment]
В STP BSUIR то же самое + в обоих случаях нет пробельных строк у заголовков 


![image](https://user-images.githubusercontent.com/18662965/80084406-805a2480-855f-11ea-91e7-b127fddf880f.png)


STP BSEU
1-6razdel.docx

![image](https://user-images.githubusercontent.com/18662965/80084492-9d8ef300-855f-11ea-8b43-4c6277185e9c.png)

**Comment by GloomlySeth** [comment]
puhova.docx


![image](https://user-images.githubusercontent.com/18662965/80147517-49fec280-85bc-11ea-88b1-5c6fe0a0b0ec.png)

**Comment by GloomlySeth** [comment]
Или в настройках магистерских приходит "Содержание? "

![image](https://user-images.githubusercontent.com/18662965/80209305-7822e780-863a-11ea-887c-1162279c86da.png)

**Comment by freedom00000** [comment]
так приходит в настройках
![image](https://user-images.githubusercontent.com/10418363/80209545-f41d2f80-863a-11ea-8052-f4c5bddce41f.png)
