### ISSUE TITLE
Лишние цифры в заголовках второго уровня

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#475]
diplom_sukora_ispr.docx

![image](https://user-images.githubusercontent.com/18662965/80182309-46485b80-860f-11ea-8ad0-001b22abc996.png)

**Comment by freedom00000** [comment]
они есть в оригинале
![image](https://user-images.githubusercontent.com/10418363/80207569-0b5a1e00-8637-11ea-9c2c-5a6d23e48177.png)
