### ISSUE TITLE
Лишние элементы в содержании

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#486]
obschiy.docx

Слева было справа стало

![image](https://user-images.githubusercontent.com/18662965/81904881-99894a80-95cc-11ea-9d31-3a85d31f9e9e.png)

**Comment by GloomlySeth** [comment]
Содыль. 

не было такого в содыль

![image](https://user-images.githubusercontent.com/18662965/86115805-19179e00-bad5-11ea-8d13-077f75ad8f55.png)

**Comment by freedom00000** [comment]
если раньше не было - это был баг
а почему не должно быть ? полностью жирные абзацы = заголовок второго уровня
![image](https://user-images.githubusercontent.com/10418363/86135262-3ce9dc80-baf3-11ea-86ac-b2711fe52a4c.png)
