### ISSUE TITLE
Знак умножения в виде точки, чтоб не ломался в квадратик

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#491]
Можно так сделать?

**Comment by freedom00000** [comment]
А в каком это документе?

**Comment by GloomlySeth** [comment]
в документе описанном в таске 490 точно есть такой момент

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/83505245-2f2e4080-a4ce-11ea-8328-cbfe112b29f8.png)
Они и не ломаются ведь...
###### P.S. Кому-то срочно нужно обновлять ворд 😄
