### ISSUE TITLE
Лишняя пробельная строка при оформлении рисунков

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#494]
файл - ful_karakulko.docx
пользователь - 25

![image](https://user-images.githubusercontent.com/18662965/84234424-e2192280-aafc-11ea-8686-b99255bcfe5f.png)

**Comment by freedom00000** [comment]
2 рисунка = 2 пробельные строки (они просто рядом расположены)

**Comment by GloomlySeth** [comment]
тогда претензия снимается
