### ISSUE TITLE
Чего у нас нет

### ISSUE THREAD

**Issue by freedom00000** [GloomlySeth/Bugtreking-SGOST#495]
- [x] 1 Параметры страницы

![image](https://user-images.githubusercontent.com/10418363/84498403-47197780-acb9-11ea-803e-24bfb9bbe5d5.png)

- [x] 2 Колонтитулы

![image](https://user-images.githubusercontent.com/10418363/84498496-703a0800-acb9-11ea-9616-06e36ade4a86.png)

- [x] 3 Текст

![image](https://user-images.githubusercontent.com/10418363/84498574-9364b780-acb9-11ea-9600-14d477722870.png)

- [x] 4 Заголовки

![image](https://user-images.githubusercontent.com/10418363/84498650-ba22ee00-acb9-11ea-878a-0677874bd333.png)

- [x] 5 ~~Содержание~~ (не актуально, планируется ввод другой настройки)

![image](https://user-images.githubusercontent.com/10418363/84498694-d32b9f00-acb9-11ea-90d8-0f0d54d0804c.png)

- [x] 6 ~~Рисунки~~ (убираем)

![image](https://user-images.githubusercontent.com/10418363/84498841-0f5eff80-acba-11ea-80f6-dbf1aca6cd1b.png)

- [x] 7 Таблицы

![image](https://user-images.githubusercontent.com/10418363/84498884-1dad1b80-acba-11ea-88ef-a99c4663e938.png)
![image](https://user-images.githubusercontent.com/10418363/84498910-2b62a100-acba-11ea-9b35-21d97d8bb40d.png)

- [x] 8 Формулы 

 -------вроде всё есть---------

- [x] 9 Списки

 -------вроде всё есть---------

- [ ] 10 Литература

![image](https://user-images.githubusercontent.com/10418363/84499037-6bc21f00-acba-11ea-8084-b0822da29fff.png)

- [x] 11 Примечания

 Всё есть, но разграничения "к рисункам" и "к таблицам" нет

- [x] 12 Приложения

-------вроде всё есть---------

- [ ] 13 Конструктор источников 

![image](https://user-images.githubusercontent.com/10418363/84500336-015eae00-acbd-11ea-9943-6018dd78b6ef.png)
-------------

- [x] 14 Сборник 

Тут я не знаю, дополнять надо тому, кто писал сборники: @Lyzgarik

**Comment by Lyzgarik** [comment]
В аннотациях можно добавить, в каком она будет формате:
1) В один абзац
2) На разных строках слова Аннотация и сам текст её.

 Сключевыми словами возможно также, но этого случая не встречал пока

этого тоже пока не понял/не видел, вернее в своём модуле не делал такие настройки интервалов
![image](https://user-images.githubusercontent.com/18488089/84553782-b45ef400-ad1d-11ea-94b7-65f0d36250eb.png)

**Comment by GloomlySeth** [comment]
может отметить, что уже появилось?

**Comment by freedom00000** [comment]
ничего?)

**Comment by GloomlySeth** [comment]
Практикант филонит? Подёргай его.

**Comment by GloomlySeth** [comment]
закрываем таску?

**Comment by freedom00000** [comment]
Ну тогда в уме про литературу
