### ISSUE TITLE
Сломалась обработка заголовков второго уровня

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#496]
документ - sodyl.docx

Смотри скрни + в главе 1 и 2 есть заголовки выделенные жирным...

![image](https://user-images.githubusercontent.com/18662965/85280530-f829ca00-b490-11ea-9af2-f501062ab5cc.png)

ковалевич и шитик тоже покривели

**Comment by freedom00000** [comment]
в новой версии починил
