### ISSUE TITLE
Таблица разбило неверно

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#498]
вроде было в этом месте получше

![image](https://user-images.githubusercontent.com/18662965/85958646-9b05ab00-b99f-11ea-85c0-6dbfcb6b911a.png)

**Comment by freedom00000** [comment]
видимо предыдущие баги вызывали и этот, сейчас всё нормально 
![image](https://user-images.githubusercontent.com/10418363/85992784-0aaa8300-b9fe-11ea-9b52-2b820826efe8.png)
