### ISSUE TITLE
Строка с требованиями по оформлению документа

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#50]
В приложении строка, которую я сделал (файл docx).
 1) Она требует добавлений (помечено маркером). 
 2) Не понял, что за настройки: division, width, margins, page, page2. Если знаешь, что за они, добавь их значения для требований к дипломам БГУИР. 
3) Птички. Если птичка отмечена, то рисовал в значение параметра "1". Если птичка не отмечена, оставлял пустое значение параметра: "".  Если есть иные предложения, вноси изменения в файл. 
4) На днях ещё раз пересмотрю настройки для таблиц и рисунков - будут изменения и дополнения  в файле. Но Ты меня не жди - вноси свои правки в мою строку. Как Ты хочешь её видеть. 

[Образец настроек.docx](https://github.com/GloomlySeth/Bugtreking/files/2303903/default.docx)

**Comment by GloomlySeth** [comment]
Чистовая версия файлов настроек требований для ДП и магистерских диссертаций в СВН SGOST

**Comment by Lyzgarik** [comment]
Отредактировал, залью как будет сервак

**Comment by Lyzgarik** [comment]
[NazvPoley.docx](https://github.com/GloomlySeth/Bugtreking/files/2433783/NazvPoley.docx)

**Comment by Lyzgarik** [comment]
диплом - [default.docx](https://github.com/GloomlySeth/Bugtreking/files/2433791/default.docx)
магистерские - [Magistr default.docx](https://github.com/GloomlySeth/Bugtreking/files/2433792/Magistr.default.docx)

**Comment by GloomlySeth** [comment]
Добавил и удалил настройки в раздел  СОДЕРЖАНИЕ
[default.docx](https://github.com/GloomlySeth/Bugtreking/files/2434282/default.docx)
[Magistr.default.docx](https://github.com/GloomlySeth/Bugtreking/files/2434283/Magistr.default.docx)
[NazvPoley-1.docx](https://github.com/GloomlySeth/Bugtreking/files/2434284/NazvPoley-1.docx)
