### ISSUE TITLE
Обработка спискв неадекактна

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#501]
Шитик

![image](https://user-images.githubusercontent.com/18662965/86104954-64c34b00-bac7-11ea-9b84-8db56048d041.png)

![image](https://user-images.githubusercontent.com/18662965/86108800-4f045480-bacc-11ea-947c-323a5013e744.png)

**Comment by freedom00000** [comment]
это же не списки, так просто тире человек поставил и всё
