### ISSUE TITLE
Много формульных символов "оквадратились"

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#502]
Шитик

Не было такого ранее

![image](https://user-images.githubusercontent.com/18662965/86109072-a4d8fc80-bacc-11ea-96d6-80efc5658de5.png)

![image](https://user-images.githubusercontent.com/18662965/86109353-f71a1d80-bacc-11ea-8b96-64e40ac51ea5.png)

**Comment by freedom00000** [comment]
пора обновить уже ворд, 2020 год на дворе :)
![image](https://user-images.githubusercontent.com/10418363/86109389-0305df80-bacd-11ea-915c-a60f72957cf2.png)
![image](https://user-images.githubusercontent.com/10418363/86109497-1e70ea80-bacd-11ea-9a4d-fdadae784dd6.png)

**Comment by GloomlySeth** [comment]
то есть мой ворд виноват. Лады
