### ISSUE TITLE
Лишняя запятая в расшифровках формул

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#503]
Нитик

![image](https://user-images.githubusercontent.com/18662965/86109915-93dcbb00-bacd-11ea-81bb-728405b21fe6.png)

**Comment by freedom00000** [comment]
так они и в оригинале есть, мы же вроде никогда не исправляли ошибки грамматические
![image](https://user-images.githubusercontent.com/10418363/86111646-ae179880-bacf-11ea-98d7-eb3ee3fb22f5.png)

**Comment by GloomlySeth** [comment]
Ты хочешь сказать, что это исходный документ?

**Comment by freedom00000** [comment]
ну да, скрин из оригинала я скинул

**Comment by GloomlySeth** [comment]
почему я их не помню, может мы всё же удаляли знаки препинания между символом и словом "где" в расшифровке формулы?

**Comment by freedom00000** [comment]
никогда такого не было, там даже настроек не используется, я перенес как было
