### ISSUE TITLE
Таблица, содержащая таблицу

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#511]
Является ли это таблицей с одной ячейкой, если внутри таблицы таблица?
![image](https://user-images.githubusercontent.com/18488089/89157112-a63a9080-d574-11ea-94bc-61b7b66eccf0.png)

И требуется ли ей данная подпись?
![image](https://user-images.githubusercontent.com/18488089/89157192-c66a4f80-d574-11ea-9816-ac592065606d.png)

Надо поправить этот момент, я думаю

**Comment by GloomlySeth** [comment]
Вроде порешали. Закрываю?

**Comment by Lyzgarik** [comment]
Done
