### ISSUE TITLE
Шлифануть обработку источников литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#512]
![image](https://user-images.githubusercontent.com/18662965/92270490-d320f100-eeee-11ea-8501-1aaa1bf9782d.png)

**Comment by GloomlySeth** [comment]
- [x] что-то ещё осталось

![image](https://user-images.githubusercontent.com/18662965/92702363-c3bffe80-f359-11ea-9128-434c281436c2.png)

**Comment by GloomlySeth** [comment]
- [x] и ещё

![image](https://user-images.githubusercontent.com/18662965/92703174-aa6b8200-f35a-11ea-936b-eb6455d655a8.png)

**Comment by freedom00000** [comment]
на счет повторов (это оригинал):
![image](https://user-images.githubusercontent.com/10418363/94439070-99b76a80-01a8-11eb-86f7-11f967612397.png)

**Comment by GloomlySeth** [comment]
этот косяк снимается с повестки

**Comment by GloomlySeth** [comment]
что-то ещё осталось

ниже там в исходном документе ещё есть [52], она тоже превратилась в [0]

![image](https://user-images.githubusercontent.com/18662965/94670524-58939780-031b-11eb-9eec-2528a6f32610.png)

**Comment by GloomlySeth** [comment]
и ниже, когда после 3 тыщ снова продолжается нумерация с 2 тыщ такое - 

![image](https://user-images.githubusercontent.com/18662965/94671382-79a8b800-031c-11eb-8945-9d0a25507256.png)

**Comment by GloomlySeth** [comment]
файл - test2


![image](https://user-images.githubusercontent.com/18662965/94699847-77a61f80-0343-11eb-9e72-35e3e0f7af67.png)

**Comment by GloomlySeth** [comment]
в предыдущем пункте ссылки на литературу заканчивались на 155. По мере встречания в тексте дальше должны быть цифры 156 и дальше (в исходном файле эьл номера 2051 - 2055). 


  Тест 2 отличается от тест тем, что я источники 2051-2055 разместил в списке литературы до источников 3001 и дальше. 

![image](https://user-images.githubusercontent.com/18662965/94700716-788b8100-0344-11eb-9fb9-e04a7e7d86a4.png)
