### ISSUE TITLE
Нумерация заголовков второго уровня сломалась

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#513]
Настройки сохранял, но отображается, что нет настройки. Правда в окошке "Свой вариант" рисует, как должно быть на выходе.

![image](https://user-images.githubusercontent.com/18662965/92725378-bebc7880-f374-11ea-9807-debde5c743f9.png)

**Comment by GloomlySeth** [comment]
В требованиях забит свой вариант нумерации в виде: "1.1", а по факту номер как на скрине. И цифры размером 16 пт. (в требованиях 14 пт.)

![image](https://user-images.githubusercontent.com/18662965/94550764-f5dbc680-025c-11eb-92bb-23f12783d21c.png)

**Comment by GloomlySeth** [comment]
"s" между цифрами пропало, но и точки не появились. 

![image](https://user-images.githubusercontent.com/18662965/94550935-3afff880-025d-11eb-8758-e2d8e671dc19.png)

**Comment by freedom00000** [comment]
нужно вообще удалить "свой вариант", там в настройках можно сделать арабскую цифру с точкой как разделитель. мы об этом говорили уже, но "свой вариант" почему-то не убрали :)

**Comment by GloomlySeth** [comment]
Разделитель имеется ввиду знак между нумерацией и текстом. Между цифрами номера по умолчанию точка....

**Comment by freedom00000** [comment]
нет, я всегда считал это разделителем между номером раздела и подраздела. иначе для чего он в **каждом** уровне может указываться?
[номер_1][разделитель_1][номер_2][разделитель_2].... в самом последнем разделитель не учитывается
пример 2.V/А , 
где 2 - арабский номер,
"." - разделитель точка,
V - римская 5, номер 2 раздела,
/ - разделитель второго раздела,
А - номер в виде буквы

**Comment by GloomlySeth** [comment]
Указывается разделитель для единообразия. В рисунках и таблицах разделитель между номером и текстом - тире, а между цифрами точка (она всегда и везде точка). В заголовках - разделитель между номером и текстом - пробел., а между цифрами точка.   Это в нашем случае, а между номером и текстом может быть точка, скобка и проч. 
   И только между двумя цифрами всегда точка - поэтому эта настройка не нужна. Она по умолчанию точка. Никто не рисует там запятые и подчёркивания или пробелы

**Comment by freedom00000** [comment]
единообразие очень путает. зачем 10 раз указывать одно и то же? 
в любом случае, "свой вариант" оттуда надо убрать, что такого в "1.1" я должен усмотреть в рамках одного раздела? Там должна быть арабская цифра и всё, ее выбрать из меню нужно. А точка у нас "по-умолчанию". Запись "1.1" вообще не понятно что должна давать...

**Comment by GloomlySeth** [comment]
там пробел ещё после 1.1 :)

**Comment by freedom00000** [comment]
ну так у нас же есть "разделитель", вот туда и надо "пробел" вставить. но 10 раз выбирать "пробел" - маразм, нужно как-то учесть
Сам факт наличия настройки запутывает. Я могу брать только из первого, например, но мы тогда придем к тому, что только 2 человека во всем мире понимают как работают эти настройки

**Comment by GloomlySeth** [comment]
из "своего варианта" убираю эту хрень.. А Ты точку верни в номера

**Comment by GloomlySeth** [comment]
В требованиях заложен шрифт номера заголовка -  14 пт, а после обработки имеем - 16 пт.

![image](https://user-images.githubusercontent.com/18662965/94988451-f08cbd80-0575-11eb-85d1-ecfef30fde1b.png)

**Comment by GloomlySeth** [comment]
пОПРОБУЙ ПОДКЛЮЧИТЬСЯ К БИРКЕ 4
