### ISSUE TITLE
Таблица, часть которой переносится на другую страницу

### ISSUE THREAD

**Issue by Xonskij** [GloomlySeth/Bugtreking-SGOST#515]
12) Таблица, часть которой переносится на другую страницу, будет разбита. Перенесённая на другую страницу часть получает шапку таблицы (или нумерацию колонок) и надпись **слева сверху** «Продолжение таблицы 2.1».

При переносе надпись «Продолжение таблицы...» появляется не слева сверху, а ровно по центру

![Screenshot_1](https://user-images.githubusercontent.com/11047296/92989795-86857900-f4df-11ea-9bfc-0daaa123633e.png)

И шрифт номера страницы не таймз как мне кажется...

**Comment by GloomlySeth** [comment]
или шрифт таймзнью роман?

**Comment by Xonskij** [comment]
> или шрифт таймзнью роман?

Не шрифт нормальный, таймзнью, 14 у заголовка и 12 у текста в таблице
