### ISSUE TITLE
Примечания к рисунку можно обработать?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#522]
Было время у нас примечания к рисунку обрабатывались вместе с подписью к рисунку. Реально ли починить? 

![image](https://user-images.githubusercontent.com/18662965/98261937-10a90580-1f96-11eb-9554-da62eec82c59.png)

**Comment by freedom00000** [comment]
Будет работать, главное, чтобы в примечании не было "Рисунок 1.1" и подобное, иначе будет считать это подписью.
Сейчас в оригинале как на скриншоте.

**Comment by GloomlySeth** [comment]
хочешь сказать во входном документе есть слово рисунок ?

**Comment by freedom00000** [comment]
можно скачать оригинал и проверить )

**Comment by GloomlySeth** [comment]
требования к тексту берутся из требований основного текста?

**Comment by freedom00000** [comment]
Да

**Comment by GloomlySeth** [comment]
давай сделаем из вкладки "примечания" - "К рисункам"

**Comment by GloomlySeth** [comment]
и похоже запятая куда-то пропала 

![image](https://user-images.githubusercontent.com/18662965/98810522-6f57fe80-2430-11eb-91e7-92880682572b.png)
