### ISSUE TITLE
Перенумерация ссылок на рисунки не дорабатывает

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#530]
"Образец (template)"

Требования БГУИР

- [x]  зачем два раза ссылаемся на рисунок в тексте

![image](https://user-images.githubusercontent.com/18662965/99993879-54d73b00-2dc9-11eb-98bd-53bd371e4b6f.png)

- [x]  Почему ссылка на рисунок не перенумеровалась в тексте после рисунка? 

![image](https://user-images.githubusercontent.com/18662965/99994316-e34bbc80-2dc9-11eb-8a59-1bc40377b583.png)

**Comment by freedom00000** [comment]
Ответ: Потому что так было задумано когда-то. Видимо у нас были проблемы или просто так было нужно. Специально только то, что выше брал.

**Comment by GloomlySeth** [comment]
пункт 2 не сработал. Или сервер не обновлён?

**Comment by freedom00000** [comment]
ответ не смутил?) это специально так, что я должен был пофиксить? 
я не помню почему мы решили именно так сделать, но была причина

**Comment by GloomlySeth** [comment]
Это не очень правильно. Если будет ссылка ниже рисунка ,она не перенумеруется и будет косяк.  Такое не часто но бывает. Может быть реализуем при каких-то допущениях?. Допустим, чтоб перенумерация сработала только до следующего заголовка второго уровня
