### ISSUE TITLE
Что не прочиталась при считывании требований 2

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#531]
- [x] 1 УДК. Не все параметры считались и заполнились. - Вкладка УДК

![image](https://user-images.githubusercontent.com/18662965/100223912-2a05f780-2f2d-11eb-8af7-a072bbf6a180.png)

**неверно занесён параметр. Сейчас попал в "после". На скрине "перед"**

- [x] 2 - вкладка авторы

![image](https://user-images.githubusercontent.com/18662965/100225033-ad741880-2f2e-11eb-8604-f4b8983c2481.png)

**Смотри п.1**

- [x] 3 - Заголовки

![image](https://user-images.githubusercontent.com/18662965/101609589-30f63500-3a18-11eb-8eb0-b51aa16b8ec0.png)

написание большими буквами не заполнилось

- [x] 4 - Аннотация 

![image](https://user-images.githubusercontent.com/18662965/100227763-afd87180-2f32-11eb-9cb0-48c6f1719b49.png)

  
- [x]  5 Ключевые слова. Проблема аналогичная пункту 4. Слово "клчевые слова имеер одну настройку, а сами ключевые слова другую ". И в дополнение интервалы (перед/после) не прочитались:

![image](https://user-images.githubusercontent.com/18662965/100228319-8ec45080-2f33-11eb-81c0-f955cb9a8be6.png)

- [x]  6 Информация об авторах. Интервалы перед/после

![image](https://user-images.githubusercontent.com/18662965/100228479-caf7b100-2f33-11eb-9b8d-df32d1d0f1ec.png)

- [x] 7 Ишью 529 не учтена при парсинге требований к заголовкум

- [x] 8  Требвания к основному тексту

![image](https://user-images.githubusercontent.com/18662965/100237373-e9fc4000-2f3f-11eb-8053-7bf27e1af126.png)

файл "Доклады БГУИР".docx

**Comment by GloomlySeth** [comment]
Проверка показала, что необходима работа над ошибками

**Comment by freedom00000** [comment]
Проверка проверки показала, что кто-то из фронтендеров не знает пару английских слов
![image](https://user-images.githubusercontent.com/10418363/100611431-5f8e5480-3322-11eb-88c3-38818cd6fb19.png)

**Comment by GloomlySeth** [comment]
Переводи на русский, что нужно сделать? 

Сейчас неправильно парсит. Птички негде ставить.  Обработка по спаршенным требованиям даёт ошибку
![image](https://user-images.githubusercontent.com/18662965/100668127-79548980-336c-11eb-9576-baea89511aa6.png)

**Comment by freedom00000** [comment]
ох, говорю же: фронтендеры просто перепутали "перед" и "после". Т.е. я правильно делаю, а у них before  = после, after = перед
_P.S. парсит правильно_

**Comment by GloomlySeth** [comment]
Напоминалка. Осталось две птички шлифануть.
