### ISSUE TITLE
Файл образец для пользователей

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#533]
Всем пользователям, которые зарегистрировались в таблицу с файлами отображаем этот файл

![image](https://user-images.githubusercontent.com/18662965/100277103-a3c0d400-2f73-11eb-8f0a-c09df156759f.png)

**Comment by freedom00000** [comment]
а что с обработкой?

**Comment by GloomlySeth** [comment]
результат обработки тоже можно положить и открыть возможность для скачивания его.

если я верно понял вопрос

**Comment by freedom00000** [comment]
Не верно. Нужно запретить обрабатывать этот документ или нет?

**Comment by GloomlySeth** [comment]
не нужно. Пусть обрабатывают всеми доступными требованиями. Это подарок для демонстрации результатов и образец, каким образом должен выглядеть файл на входе. 
 Сегодня постараюсь сделать текст для страницы, которая должна появляться при первом входе пользователя в систему после регистрации и пояснять, что за файлы в таблице у него лежат. Типа подсказка

**Comment by freedom00000** [comment]
если все будут обрабатывать 1 файл, будет странная ситуация. если кидать этот файл каждому юзеру при регистрации, то образец невозможно будет заменить + у нас будет куча копий одного файла у каждого юзера

**Comment by GloomlySeth** [comment]
Образец могут менять только суперадмины. 
Либо мы соглашаемся с этой странной ситуацией, либо исходный образец и результаты его обработки по имеющимся по умолчанию требованиям беруться без обработки (но с её иммитацией) из одного места, чтоб их не плодить каждому пользователю. 
Если пользователь обрабатывает этот файл своими требованиями, то, естественно результат гладём ему в папку. 

Суть концепта в том, чтобы юзер взял этот файл и в него пихал свой документ методом копипаста. То есть, чтобы не задумывался как заголовки правильно оформить для того, чтобы ошибку система не выдавала. + на примере можно посмотреть, что на входе и что на выходе.

**Comment by freedom00000** [comment]
Смысл то не в этом. 
Нет сейчас возможности сделать так, чтобы у юзера отображался файл, при этом отдельно статус был для каждого юзера. Т.е. фактически файл принадлежит аккаунту SETH , он владелец. У каждого файла есть статус (в обработке он или стадия), если начать обработку, то этот статус изменится, его увидят ВСЕ юзеры. Т.е. вариант - копировать всем один и тот же файл при регистрации, но тогда, у них будет версия, актуальная на момент регистрации и если что-то нужно будет поменять вдруг, то будет проблематично это сделать для вообще всех.
Вся соль не в результате, а в оригинале файла. Просто я даже не могу придумать пока, как это сделать, чтобы было нормально и без костылей всяких. 
Как я вижу нормальный вариант:
Файл могут скачать все, но обрабатывать раздельно и одновременно могут все (сейчас 1 файл нельзя обработать одновременно). При этом, оригинал бы у всех обновлялся, когда его обновляет владелец (вариант с копированием во время регистрации отпадает). Нужно подумать...

**Comment by GloomlySeth** [comment]
Ты сформулировал правильный вариант. Нужно на него ориентироваться

**Comment by GloomlySeth** [comment]
Как сделал по факту?

**Comment by freedom00000** [comment]
как написал.

**Comment by GloomlySeth** [comment]
Нужно выписать такску фронтендерам?

**Comment by freedom00000** [comment]
я уже исправил
