### ISSUE TITLE
Требования к номеру в списке литературы не применились

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#538]
при обработке по требованиям статьи

![image](https://user-images.githubusercontent.com/18662965/101535595-efc73c00-39a9-11eb-9809-d9f84eb28ad1.png)

**Comment by GloomlySeth** [comment]
А у нас нет такого метода который после точки всегда ставит пробел?
 Или добавить опцию "точка с пробелом"?

**Comment by GloomlySeth** [comment]
Добавляю новую опцию?

**Comment by freedom00000** [comment]
Если нужно, то да :)

**Comment by GloomlySeth** [comment]
Я тут подумал. Давай лучше сделаем полюбому пробел между текстом и любым разделителем кроме пробела

**Comment by GloomlySeth** [comment]
не смог извлечь пробел после точки в этом месте:
![image](https://user-images.githubusercontent.com/18662965/102829075-54958400-43f7-11eb-8742-1b2d4bc54fae.png)
прошу научить
