### ISSUE TITLE
После парсинга требований из файла не заполнилось новое требование

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#539]
Это кому задачка? 

![image](https://user-images.githubusercontent.com/18662965/101609104-9c8bd280-3a17-11eb-9d08-c29d2b18ee3f.png)

**Comment by freedom00000** [comment]
так в документе "Доклады БГУИР.docx" нет номеров страниц, вот оно и не заполнилось. Тут настройки из требования "Сборники БД"
Правда там в любом случае только цифры, у них нет регистра
(Я просто подправил в шаблоне, теперь поле заполнено)

**Comment by GloomlySeth** [comment]
Это скрин из вкладки "заголовки первого уровня"
