### ISSUE TITLE
Нужно распарсить требования к заголовкам второго уровня

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#541]
![image](https://user-images.githubusercontent.com/18662965/101677601-d12a7900-3a6d-11eb-96d3-00a6ab0925f1.png)

**Comment by freedom00000** [comment]
Как их определять? они будут жирным полностью?

**Comment by GloomlySeth** [comment]
Если Ты про обрабатываемы документ, то да они будут полностью жирным.

**Comment by GloomlySeth** [comment]
Если про документ для парсинга, то не обязательно.

**Comment by freedom00000** [comment]
Мне нужно знать как их находить. Что значит не обязательно? Чтобы обработать и вытащить требования нужно оформить как-то уникально. Я же говорил, с заголовками лажа будет

**Comment by GloomlySeth** [comment]
Не лажа а временные трубности. 

  1)  При обработке входной файл будет всегда иметь эти заголовки жирными, чтобы мы могли их однозначно найти и обработать. 

   2) При парсинге требований из файла делаем так. Если не находим жирных заголовков не парсим их. Считаме, что в образце нет заголовков второго уровня
