### ISSUE TITLE
Приложение перекосило после обработки

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#543]
файл от пользователя anzhelika1106@inbox.ru

требования   -   БГУИР

![изображение](https://user-images.githubusercontent.com/18662965/101923854-f8ee1e00-3be0-11eb-953b-bcee70f629aa.png)

**Comment by GloomlySeth** [comment]
а сервер обновил? Ибо я разницу не обнаружил

**Comment by freedom00000** [comment]
обновлял, вот результат
![image](https://user-images.githubusercontent.com/10418363/102191371-609ab680-3eca-11eb-87ba-28d40108f6c7.png)
