### ISSUE TITLE
Шрифт заголовка второго уровня не прочитался при парсинге из файла

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#544]
- [x] При парсинге требований всем элементам ставим "тип нумерации" - "Сквозная" автоматически. 

![image](https://user-images.githubusercontent.com/18662965/102132485-bfc5e000-3e64-11eb-9192-48c10e7f6b0e.png)

касается рисунков, таблиц, формул. 

- [x]  Шрифт заголовка второго уровня не прочитался при парсинге из файла

![image](https://user-images.githubusercontent.com/18662965/101950912-2221a500-3c07-11eb-8df5-6f00b914add0.png)

- [x]  Интервалы до заголовка не заполнились 

![image](https://user-images.githubusercontent.com/18662965/101951048-61e88c80-3c07-11eb-8b72-03342c03d6d5.png)

- [x]  Параметры "Шрифт" заголовка "Список литературы " могут отличаться от заголовков второго уровня. Как и куда будем парсить в этом случае? Добавляем на фронт компонент шрифт?

**Comment by freedom00000** [comment]
где этот тип нумерации? я что-то не вижу...

про список литературы обсуждали же, это слово будет только в литературе, настройки для него только там. Заголовки второго уровня это то, что выделено жирным

**Comment by GloomlySeth** [comment]
Про список литературы. 
Сейчас в требованиях "Литература" можно задать требования к оформлению самого списка. Мой вопрос относиться к заголовку, - самому слову "Литература" или "Список литературы" в грёбаной бигдате это слово по оформлению отличается от остальных заголовков....

**Comment by freedom00000** [comment]
Так мы еще 2 недели назад обсудили, что для слова "литература" и прочим, нужно сделать настройки во вкладке, касающейся литературы. А уровни заголовков оставить как есть, без дополнительной логики, которая нигде даже не задокументирована и не очевидна. Т.е. как в самом ворде уровни.
