### ISSUE TITLE
Требования по оформлению рисунков не сработало

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#545]
В требованиях заложена пробельная строка между рисунком и подписью к нему. 

![image](https://user-images.githubusercontent.com/18662965/102061955-2c10f700-3e05-11eb-9b5f-b56ea7f4174f.png)

**Comment by freedom00000** [comment]
что за требования?

**Comment by GloomlySeth** [comment]
Доклады БГУИР версия 6
