### ISSUE TITLE
Требования к заголовкам второго уровня в статьях не применились

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#547]
Обрабатывал требованиями "Доклады БГУИР вер.7"

![image](https://user-images.githubusercontent.com/18662965/102276796-616a3180-3f38-11eb-8dc8-3850a164341b.png)

**Comment by Lyzgarik** [comment]
в процессе

**Comment by Lyzgarik** [comment]
Сделано
