### ISSUE TITLE
Развить распознавание элементов списка литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#550]
файл "Титул, реферат, содержание 2.docx". Пользователь - danilyuk@bsuir.by

- [x]  название журнала не нашлось

![image](https://user-images.githubusercontent.com/18662965/105693381-b3777d00-5f10-11eb-8e77-20c6970b36d7.png)

- [x] год издания номера журнала не нашло

![image](https://user-images.githubusercontent.com/18662965/105693649-094c2500-5f11-11eb-844d-c5fff47c8bf8.png)

- [x] Том (Vol) и № (No) не распознаны

![image](https://user-images.githubusercontent.com/18662965/105694056-8b3c4e00-5f11-11eb-8b99-a22352ddcdef.png)

**Comment by GloomlySeth** [comment]
В этом файле с поиском элементов проблема остаётся. Фактически из-за него мы пришли к пометке курсивом журналов. Если не ошибаюсь в данном случае как раз статьи оформлены по MLA Или APA 

![image](https://user-images.githubusercontent.com/18662965/122472721-9def1680-cfc9-11eb-9f6b-0b42e51bad3a.png)

**Comment by GloomlySeth** [comment]
там же

![image](https://user-images.githubusercontent.com/18662965/122473559-b3187500-cfca-11eb-9960-e1b6b8834a12.png)


немного изменил на входе строку. Нашло элементы ещё хуже.

![image](https://user-images.githubusercontent.com/18662965/122475492-697d5980-cfcd-11eb-8f87-fa676bb9b135.png)

**Comment by GloomlySeth** [comment]
Предлагается дополнить постк элементов таким алгоритмом. 

  Если не удалось причислить источник ни к одному из типов  (книга, статья, сборник, патент и проч.), делаем так. 
  1) ищем год. Если год прописан в скобках - имеем дело со статьёй оформленной по требованиям MLA или APA. 
  2)  Если год не в скобках ищем связку "цифра(цифра)", 3(8). Это том и номер журнала (номер в скобках).  Имеем дело с журналом формленным по требованиям Harward, или, если год был в скобках,  APA. 

Далее ищем элементы в соответствии со скринами

MLA  (понятные элементы не отмечал, название журнала везде будет курсивом)
![image](https://user-images.githubusercontent.com/18662965/123424949-2e30eb00-d5ca-11eb-9892-073d6d76fdd4.png)


APA 
![image](https://user-images.githubusercontent.com/18662965/123425371-bf07c680-d5ca-11eb-90fe-e0592bb50a86.png)


Harward (аналогично APA)

![image](https://user-images.githubusercontent.com/18662965/123425549-efe7fb80-d5ca-11eb-8f4a-4124ad87c265.png)

**Comment by GloomlySeth** [comment]
Пропадает номер тома.  Можно его не терять? 

Причём если в источнике нет № , а только том, то том тоже пропадает. 

![image](https://user-images.githubusercontent.com/18662965/127294304-5f5e792f-256a-45b5-9280-077d95f63135.png)


можешь тут прописать, как сейчас происходит определение элементов?

**Comment by freedom00000** [comment]
как тут написано https://github.com/GloomlySeth/Bugtreking-SGOST/issues/550#issuecomment-868468578

Исправил, теперь номер тома есть

**Comment by GloomlySeth** [comment]
куда смотреть? Обработал - тоже самое

**Comment by GloomlySeth** [comment]
сейчас находит. Но год втавляет не в то место. 

![image](https://user-images.githubusercontent.com/18662965/127644263-e7681726-bfbf-45c1-8a31-d3715f56a46c.png)

При этом, в файле "Литература 3" год вставляет, вроде, верно, но дублирует номер тома. 

![image](https://user-images.githubusercontent.com/18662965/127644607-f93a8f52-1b15-4732-a71a-9e86b531486f.png)


При этом элементы не попадают в правильные места

![image](https://user-images.githubusercontent.com/18662965/127644170-c4b3c5bc-a04b-40de-b8ca-ddad10f203f2.png)

![image](https://user-images.githubusercontent.com/18662965/127644410-0b4a4f3c-4dce-4e63-8068-3108a6b7ce8e.png)

**Comment by GloomlySeth** [comment]
файл "Литература 2" с парсингом тоже есть нюансы 

![image](https://user-images.githubusercontent.com/18662965/127645039-c5aaeca5-541e-4d19-9bf4-2176f8f38f47.png)
