### ISSUE TITLE
обработка документов на английском

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#552]
- [x] 1) Сделать английских вариант "Введения", "Заключения", "Список источников". (в англоязычных работах заголовком списка источников может быть как "Referenses", так и "Work Cited". Это нужно учесть)
- [x] 2) Сделать английские подписи для таблиц и рисунков (сейчас находит норм, но делает русским языком). - решается путём изменения настроек в требованиях. 
- [x] 3) Англ. вариант "продолжения таблицы n" и тому подобные русские вставки
- [x] 4) Подпись к формулам на английском (слово где и тд).
- [x] 5) Англ. содержание.

- [x] 6) Починить игнорирование заголовков капсом
- [x] 7)  Починить вписывание визио-рисунков в поля страницы
- [x] 8) исправить добавку ссылок на рисунки и таблицы в текст перед появлением рисунков и таблиц на англ язык.
- [x] 9) починить ссылки на рисунки и таблицы в плане нумерации

Сейчас определяю, что док на английском, по первому слову в документе.

**Comment by Lyzgarik** [comment]
8 Пункт работает норм, ловит с настройки на сайте 
![image](https://user-images.githubusercontent.com/18488089/106446778-b682e800-6491-11eb-980e-8568d6120a61.png)
....
![image](https://user-images.githubusercontent.com/18488089/106447029-0bbef980-6492-11eb-92e6-b3ace4ca10ea.png)

работает правда от теории идеальной ссылки, вроде как

**Comment by GloomlySeth** [comment]
Пункт 6 был  отмечен по ошибке

![image](https://user-images.githubusercontent.com/18662965/107113687-91b3b980-6871-11eb-9769-18452730f1e2.png)

![image](https://user-images.githubusercontent.com/18662965/107113728-d17aa100-6871-11eb-9aa8-50286b427c56.png)
