### ISSUE TITLE
Транслит пунктов Англ. документов

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#553]
Тут слова которые надо для англ документов, для точности, вынес их сюда

- [x] 1) "СОДЕРЖАНИЕ", "ВВЕДЕНИЕ", "ЗАКЛЮЧЕНИЕ", "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ", "СПИСОК ИСПОЛЬЗОВАННОЙ ЛИТЕРАТУРЫ", "БИБЛИОГРАФИЧЕСКИЙ СПИСОК", "ПЕРЕЧЕНЬ УСЛОВНЫХ ОБОЗНАЧЕНИЙ, СИМВОЛОВ И ТЕРМИНОВ", "ПЕРЕЧЕНЬ УСЛОВНЫХ ОБОЗНАЧЕНИЙ", "РЕФЕРАТ", "ОБЩАЯ ХАРАКТЕРИСТИКА РАБОТЫ"
- [x] 2) "реферат", "список сокращений", "аннотация", "общая характеристика работы", "перечень условных обозначений", "перечень условных обозначений, символов и терминов", "термины и определения", "перечень сокращений и обозначений", "список исполнителей"
- [x] 3)  "(обязательное)", "(рекомендуемое)", "(справочное)"

Некоторые могут повторяться, брал из методов в проге
может каких пунктов не хватает, тогда буду докидывать

**Comment by Lyzgarik** [comment]
в 4 :  (required), (recommend).  Спрачное - referential или просто reference?

**Comment by GloomlySeth** [comment]
для характеристики "Справочное"  используем два варианта: "informative" и "reference".

для характеристики "Обязательное" - "mandatory"

**Comment by Lyzgarik** [comment]
"СОДЕРЖАНИЕ" - CONTENT
 "ВВЕДЕНИЕ" - INTRODUCTION
 "ЗАКЛЮЧЕНИЕ" - CONCLUSION
 "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ" - list of reference или просто references
"СПИСОК ИСПОЛЬЗОВАННОЙ ЛИТЕРАТУРЫ" - reference list или просто references
"БИБЛИОГРАФИЧЕСКИЙ СПИСОК" - bibliographic list
"ПЕРЕЧЕНЬ УСЛОВНЫХ ОБОЗНАЧЕНИЙ, СИМВОЛОВ И ТЕРМИНОВ" - legend
"ПЕРЕЧЕНЬ УСЛОВНЫХ ОБОЗНАЧЕНИЙ" - тоже legend
"РЕФЕРАТ" - ABSTRACT, review или report
"ОБЩАЯ ХАРАКТЕРИСТИКА РАБОТЫ" - general description или general characterization

**Comment by Lyzgarik** [comment]
"список сокращений" - list of acronyms
"аннотация" - annotation или abstract;
"термины и определения" - terms and definitions или просто definitions
"перечень сокращений и обозначений" - list of abbreviations
"список исполнителей" - authors
