### ISSUE TITLE
Список обработался неадекватно

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#558]
Документ - Asinovsky_KS_Eng.docx 
Требования Бигдата

по логике обработки это простой список и маркеры должны были с цифр переделаться на тире. По факту получилось иначе 
![image](https://user-images.githubusercontent.com/18662965/106911147-f3a9dd00-6712-11eb-8351-a1a946eb36bb.png)

**Comment by GloomlySeth** [comment]
у меня не сработал фикс

![image](https://user-images.githubusercontent.com/18662965/107564610-b0101100-6bf3-11eb-885a-e25e806924aa.png)

и ещё в другой статье

![image](https://user-images.githubusercontent.com/18662965/107566495-0a11d600-6bf6-11eb-808a-e773a03561b6.png)

**Comment by Lyzgarik** [comment]
хм, я обрабатывал, было с настроечными всё. Проверю ещё раз
