### ISSUE TITLE
Проверить все требования. Применяются ли/ Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#566]
В требованиях заложено оформление рисунков и таблиц иначе чем на выходе 

речь про требования Big Data

**Comment by GloomlySeth** [comment]
напиши, какие требования провверил

**Comment by Lyzgarik** [comment]
> напиши, какие требования провверил

тип нумерации, знаки в нумерации, слова, добавляемые строки, курсив-жирность

**Comment by GloomlySeth** [comment]
где? В рисунках? таблицах? списки?

**Comment by GloomlySeth** [comment]
шрифт таблицы и шрифт шапки таблицы не применился в требованиях MLA

**Comment by GloomlySeth** [comment]
Этот момент мы не устранили? 

![image](https://user-images.githubusercontent.com/18662965/108822387-10c62300-75d0-11eb-869c-eabe2e47c781.png)
