### ISSUE TITLE
После списка литературы можно не применять никакие требования?  Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#569]
например не трогаем ничего после строчки написанной капсом

![image](https://user-images.githubusercontent.com/18662965/107828164-547f8800-6d99-11eb-920f-9fef35cc0941.png)

**Comment by GloomlySeth** [comment]
Сейчас отсутствие птички не помогло

![image](https://user-images.githubusercontent.com/18662965/107873822-7165a980-6ec6-11eb-97ec-0f2a9312efc2.png)

**Comment by Lyzgarik** [comment]
(для себя) 
![image](https://user-images.githubusercontent.com/18488089/107973719-9e998100-6fc6-11eb-83ac-c475c15dbfb3.png)
