### ISSUE TITLE
Убрать абзацный отступ под фоткой автора. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#570]
![image](https://user-images.githubusercontent.com/18662965/107873777-0025f680-6ec6-11eb-93e6-70f1049c0853.png)

**Comment by GloomlySeth** [comment]
Внимательнее проверяем перед тем, как поставить метку

![image](https://user-images.githubusercontent.com/18662965/108025183-1606f900-7037-11eb-90ae-d0bf7965e167.png)

**Comment by Lyzgarik** [comment]
> Внимательнее проверяем перед тем, как поставить метку

![image](https://user-images.githubusercontent.com/18488089/108030786-d513e200-7040-11eb-9e6c-c34c559c14f5.png)

присваиваю отступы отсюда, это как описание к автору

**Comment by Lyzgarik** [comment]
зачем тогда ставить, что авторы отступ на 1 см? :)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/108031110-4f446680-7041-11eb-9cea-bf225c9d0dfc.png)

убрал в настройках, вроде как надо всё применяет
