### ISSUE TITLE
Изменить язык в нумерации таблиц и рисунков. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#571]
Язык текста один. А нумерация с другим языком.

нужно сделать обработку хитрой нумерации рисунков формата "1 - рисунок"

![image](https://user-images.githubusercontent.com/18662965/107933530-e7821300-6f8f-11eb-9797-8fb31cb334ac.png)

**Comment by GloomlySeth** [comment]
Очень нужна. Копиться количество статей. Нужн их обрабатывать. Я не могу этого делать из-за этой таски

**Comment by Lyzgarik** [comment]
допилю перевёрнутые подписи, англ как я понял, уехала в требования
