### ISSUE TITLE
Обработка файла вызвала ошибку. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#573]
В чём причина? 

![image](https://user-images.githubusercontent.com/18662965/107936509-cd4a3400-6f93-11eb-8170-c1a07193978b.png)

**Comment by Lyzgarik** [comment]
не распознало UDC, поправил регулярку на поиск

**Comment by GloomlySeth** [comment]
изменил на UDK эффект тот же
