### ISSUE TITLE
Обработка вставляет лишние слова. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#576]
Kurbanov_S.docx

![image](https://user-images.githubusercontent.com/18662965/108334653-37a4e380-71e3-11eb-815a-3c5ea95f3023.png)

**Comment by Lyzgarik** [comment]
там невидимый текст в исходнике, прикол)
![image](https://user-images.githubusercontent.com/18488089/108373299-cd0a9c80-7210-11eb-8e7a-7bce54722f50.png)

**Comment by GloomlySeth** [comment]
невидимы текст это как? Где он храниться?
