### ISSUE TITLE
Вставка номеров рисунков и таблиц работает некорректно. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#581]
Если ссылка на рисунок или таблицу уже есть в тексте, но не нужно её повторять в конце абзаца перед текстом. 

![image](https://user-images.githubusercontent.com/18662965/108840924-0d3e9600-75e8-11eb-8c1b-59f6aa390b05.png)

Нужно перепроверить, работает ли эта функция при обработке по другим пребованиям

**Comment by Lyzgarik** [comment]
это вроде дублирующаяся таска, к появлению номера после упоминания в тексте
