### ISSUE TITLE
Ошибки в оформлении списков

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#583]
На входе очистил стиль списка. Потом применил кнопку список с нумерацией. После обработки получил такой нумерованный список

![image](https://user-images.githubusercontent.com/18662965/108842399-4546d880-75ea-11eb-883c-eec3cada870b.png)

В требованиях стоит настройка нумерации - "арабские цифры"

ф файле "Abdul-Azalova" - проблема повторяется

**Comment by Lyzgarik** [comment]
док?

**Comment by GloomlySeth** [comment]
st _Архипова 16_02_2021

**Comment by Lyzgarik** [comment]
остались проблемы со знаком после числа
