### ISSUE TITLE
Переделать алгоритм символов в строке

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#588]
Файл - Нгуен_Ланин

  По требованиям перед формулой должна быть пробельная строка

![image](https://user-images.githubusercontent.com/18662965/109351299-18b0ec00-788a-11eb-85f4-bff89e3f20ee.png)

**Comment by GloomlySeth** [comment]
проверил этот момент на требованиях "БГУИР". Формулы правильно обрабатываются....

**Comment by Lyzgarik** [comment]
дельты сейчас норм должны быть. Остальные символы в доработке

**Comment by GloomlySeth** [comment]
дублируется с 595. Но забывать про неё не стоит
