### ISSUE TITLE
Расшифровка формул по требованиям заложена в одну строку. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#594]
По факту в одну строку алгоритм не собирает

![image](https://user-images.githubusercontent.com/18662965/110164584-9af95d00-7e02-11eb-8a8d-2c7b0e0047f4.png)

**Comment by Lyzgarik** [comment]
она как-то интересно работает, раньше склеивало, т.к формулы были через ctrl+enter. 
А вообще был же алгоритм склейки какой-то?

**Comment by GloomlySeth** [comment]
Влад должен был делать. На дипломах проверяли. Работало. И склейка и расклейка
