### ISSUE TITLE
Символы в формулах пропадают. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#596]
Saskevich_A.docx

![image](https://user-images.githubusercontent.com/18662965/110446832-a7b2d500-80d0-11eb-8a9b-45eb08ef21d1.png)

**Comment by GloomlySeth** [comment]
а с пропадающими символами вопрос решается? 

![image](https://user-images.githubusercontent.com/18662965/110547377-e6807380-8140-11eb-889e-505294d23993.png)

**Comment by Lyzgarik** [comment]
в исходнике также, конкретно в этом доке

**Comment by GloomlySeth** [comment]
Сейчас с сайта должно приходить в требованиях, что нужно применять для формул шрифт Cambria Math. Для бигдата требований. Это требование не срабтывает. 

тестил на файле - "Levankov_Doudkin"

![image](https://user-images.githubusercontent.com/18662965/110851014-8cf38280-82c1-11eb-8f14-4194d68fb98e.png)

**Comment by Lyzgarik** [comment]
с формулой должно приходить, с номером ещё смотрю штуку

**Comment by Lyzgarik** [comment]
надо как-то вынести вопросы из этой таски, если они остались, в другую

**Comment by GloomlySeth** [comment]
1) В файле "Levankov_Doudkin" порядок. 

2) В файле Saskevich_A.docx проблема осталась. Символов нет шрифт в формулах по тексту остался таймс
![image](https://user-images.githubusercontent.com/18662965/111384447-8ea2b900-86ba-11eb-900f-fedb779363d2.png)
