### ISSUE TITLE
Формулы в строке не обрабатываем. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#600]
Файл - gabchenko_Sheleg_Doudkin.docx

Такой заложенный нами принцип работает не на все формулы... Или не всегда. 

![image](https://user-images.githubusercontent.com/18662965/111003322-f5149800-8397-11eb-92b7-a37b78302cdb.png)

**Comment by Lyzgarik** [comment]
Сейчас алгоритм такой, что не ловит формулы в строке, если суммарно остальных символов больше или 17

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/111151321-5909ad00-85a0-11eb-8dfe-78ff12663e14.png)
по типу такого, тут в пункте б вышло по итогу 20 символов считая с пробелами
