### ISSUE TITLE
Повторяющиеся запятые и точки в формулах

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#604]
![image](https://user-images.githubusercontent.com/18488089/112320829-733e3c00-8cc0-11eb-8e9f-064c36d40e7f.png)

док 

![image](https://user-images.githubusercontent.com/18488089/112320944-8c46ed00-8cc0-11eb-958e-61d4e74fd40b.png)

**Comment by GloomlySeth** [comment]
Одна из них внутри формулы, остальные почему плодятся не понятно

**Comment by GloomlySeth** [comment]
запятые сделал, а точку забыл 

![image](https://user-images.githubusercontent.com/18662965/112545872-c4862280-8dc9-11eb-8e9a-5ede224c12d7.png)

**Comment by GloomlySeth** [comment]
Перебор. Если в строке после формулы большая буква, то абзацный отступ оставляем. Сейчас он куда-то пропал.

абзацный отступ убираем только, если в следующей после формулы строке малая буква первая. 

![image](https://user-images.githubusercontent.com/18662965/112716430-8555ef80-8ef7-11eb-9a5d-63a2fcb86b96.png)

**Comment by Lyzgarik** [comment]
а, ок, я там проверку на все формулы вообще сделал. Поправлю сейчас
