### ISSUE TITLE
Требования к подрисуночной подписи не сработали. MLA

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#607]
![image](https://user-images.githubusercontent.com/18662965/113058006-6cc72d00-91b6-11eb-8c37-8abf03f6948a.png)

**Comment by Lyzgarik** [comment]
ещё со строками осталось сдружить

**Comment by GloomlySeth** [comment]
- [ ] что-то не так 159 страниц стало и 40 минут булькался

- [ ] где-то фигуре, где-то пиктуре, где-то фиг....

- [ ] метод, который лепит ссылку на рисунок в абзац до рисунка вставляет ссылку в подпись к рисунку.

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/113208795-e58fbd00-927a-11eb-9462-5dd5e0738eda.png)


![image](https://user-images.githubusercontent.com/18662965/113208654-bc6f2c80-927a-11eb-9b4c-df38e94fc2da.png)

**Comment by Lyzgarik** [comment]
прикол, не всё учёл в переносе

**Comment by GloomlySeth** [comment]
требования - MLA

Что-то недоконца работает. Это не единственный рисунок, который сплюснуло

![image](https://user-images.githubusercontent.com/18662965/128067985-39f8eadd-2feb-4869-8757-ac6b6c39ac7b.png)
