### ISSUE TITLE
Требования к слову ЛИТЕРАТУРА не сработали. MLA

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#610]
в требованиях прописан свой вариант

![image](https://user-images.githubusercontent.com/18662965/113058735-31792e00-91b7-11eb-8318-d72a8587da5f.png)

**Comment by GloomlySeth** [comment]
нужно не придумывать непонятно что, а применять значения заложенные в требованиях

![image](https://user-images.githubusercontent.com/18662965/113932986-b76f2780-97fc-11eb-9810-742f9bf7d82c.png)

**Comment by Lyzgarik** [comment]
через тест
