### ISSUE TITLE
Дополнительные уловия для поиска элементов в источниках

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#611]
Вводим дополнительную проверку на наличие курсива в строке. 

    если есть курсив в следующих источниках
  1)  журнале, то ещё проверяем текст курсивом в начале строки или в конце: если вначале - это название работы, если в конце  - это название журнала. 
  2)   книга, то текст курсивом - это название книги.
  3)   сборник конференций -  аналогично журналу, см п.1

**Comment by GloomlySeth** [comment]
есть подозрение, что не работает.  + есть проблемы с распознаванием элементов у статей и статей в сборниках работ

![image](https://user-images.githubusercontent.com/18662965/115691653-ec37be80-a366-11eb-8c1b-557c2d892672.png)

**Comment by GloomlySeth** [comment]
все источники после 133 слепило в один...

![image](https://user-images.githubusercontent.com/18662965/116863601-36465d00-ac0f-11eb-9424-357fcfeec522.png)

**Comment by GloomlySeth** [comment]
перенёс ссылк после [133] выше.  Всё опять слепило по непонятной системе

**Comment by freedom00000** [comment]
по каким это требованиям? если по дипломным, то (результат ниже). Если по удк - у Игоря своя система там
![image](https://user-images.githubusercontent.com/10418363/116865578-8e329300-ac12-11eb-9ea2-2fcd9366a332.png)

**Comment by GloomlySeth** [comment]
требования - "БГУИР". В своём скрине склеены 3 источника

Вот разложенная по полочкам публикация в сборнике конференции

![image](https://user-images.githubusercontent.com/18662965/116867124-334e6b00-ac15-11eb-8ebe-9b998f06d390.png)

**Comment by GloomlySeth** [comment]
- [x]  1) куда делись ещё 3 источника? + Лишние элементы с статье из сборника конференции

![image](https://user-images.githubusercontent.com/18662965/117075414-71df4500-ad3d-11eb-952b-e80dbafafa1d.png)

- [x]  2) 
![image](https://user-images.githubusercontent.com/18662965/117076295-d9e25b00-ad3e-11eb-95bf-5f4b3117f20c.png)

- [x] 3) 
![image](https://user-images.githubusercontent.com/18662965/117076691-7c024300-ad3f-11eb-8bc9-83e72d639503.png)

- [x]  4) Патенты неверно оформляются на выходе 

![image](https://user-images.githubusercontent.com/18662965/117077406-b6201480-ad40-11eb-8305-9ca77c8f71b9.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/117280566-6722ce00-ae6b-11eb-8df3-f8193c66c594.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/118183452-ccb22400-b442-11eb-95d2-5f8b70419020.png)

**Comment by GloomlySeth** [comment]
В комментарии от 6 мая пример сделан. Фамилия, потом инициалы. А У тебя как? 

![image](https://user-images.githubusercontent.com/18662965/118378171-8263ab00-b5da-11eb-99f6-dc702066ae3a.png)
