### ISSUE TITLE
Пропадает подпись к таблице после обработки. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#613]
![image](https://user-images.githubusercontent.com/18662965/114761468-2d2d4300-9d69-11eb-9be7-b3418ee9f508.png)

**Comment by Lyzgarik** [comment]
Переписал немного метод по подписям, тупило из-за отсутствия номера

**Comment by GloomlySeth** [comment]
а Ты помнишь в каком это документе?
