### ISSUE TITLE
Лишние элементы при переносе таблицы. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#615]
![image](https://user-images.githubusercontent.com/18662965/114998082-41785980-9ea9-11eb-87db-32de9a0903ff.png)

**Comment by Lyzgarik** [comment]
да, в требованиях бгуир приходит ставить 1 строку, проверил у себя

![image](https://user-images.githubusercontent.com/18488089/117144521-af35e800-adba-11eb-8ca8-2d2360bbf261.png)

![image](https://user-images.githubusercontent.com/18488089/117144574-c4127b80-adba-11eb-8e94-dd66f0de1748.png)

**Comment by GloomlySeth** [comment]
похоже придётся сегодня требования БГУИР в тринадцатый раз заново создать....
