### ISSUE TITLE
Склейка продолжения таблицы не произошла. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#618]
ДИПЛОМ_ПРОВЕРКА.docx

![image](https://user-images.githubusercontent.com/18662965/114999993-04ad6200-9eab-11eb-9a66-bbe36bb8c4ef.png)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/116896427-eaaaa800-ac3c-11eb-9d6a-8d53b6470399.png)
как обговаривали, так склеивает теперь

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/116896497-fa29f100-ac3c-11eb-8f17-498cec6c1ceb.png)
