### ISSUE TITLE
Лишние цифры добавляются. Big Data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#620]
borovikov_S.docx

![image](https://user-images.githubusercontent.com/18662965/115026089-bf992800-9eca-11eb-96a2-c81b6fb8b529.png)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/116406312-30c8cb80-a839-11eb-80a6-c5132c5741bc.png)

**Comment by Lyzgarik** [comment]
начальную десятку делает нормальным шрифтом вот она и вылазит
