### ISSUE TITLE
Ссылки на рисунки вставляются неверно. Big data

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#622]
Бранцевич_BIG_DATA_2021_04_15.docx

При обработке по требованиям БГУИР, работало нормально

![image](https://user-images.githubusercontent.com/18662965/115051358-68ed1780-9ee5-11eb-9c6a-5522dbd6dfab.png)

**Comment by Lyzgarik** [comment]
сейчас столько ссылок не лепит, но может сделать вариант 12-10, из-за перенумерации старых. Надо потестить такие моменты ещё

**Comment by Lyzgarik** [comment]
+если в тексте уже есть явное упоминание, не ставит новую. (ранее обговаривали)
