### ISSUE TITLE
обрезает кусок расшифровки формулы

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#624]
![image](https://user-images.githubusercontent.com/18488089/115299980-1cfdd500-a168-11eb-9420-b48ace30d4cd.png)

стало 

![image](https://user-images.githubusercontent.com/18488089/115300004-22f3b600-a168-11eb-9d78-453db2b32037.png)

![image](https://user-images.githubusercontent.com/18488089/115300092-3d2d9400-a168-11eb-8beb-171ea25fbc6f.png)

**Comment by GloomlySeth** [comment]
что за файл? Как проверять?
