### ISSUE TITLE
Лишние точки в конце формул

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#626]
Если в конце формулы уже была точка, всё равно добавляется ещё одна. Аналогичное не происходит с запятыми.
До
![изображение](https://user-images.githubusercontent.com/60774224/115448694-aa9dfb00-a222-11eb-8bc3-bc5e994a5f4f.png)
После
![изображение](https://user-images.githubusercontent.com/60774224/115448832-d7521280-a222-11eb-9912-9445cbd88eb3.png)

**Comment by GloomlySeth** [comment]
Дэйвидас, как файл называется в котором этот баг наблюдался? 

Отбой. Нашёл вроде

**Comment by Lyzgarik** [comment]
Теперь удаляются все знаки после формулы, а там видно будет, как я понял
