### ISSUE TITLE
Заголовок раздела с литературой оформлен не по требованиям. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#628]
После фокса проверить, чтобы в сборниках этот заголовок не "поехал"

![image](https://user-images.githubusercontent.com/18662965/115513412-b40f7d80-a28b-11eb-88b8-1f80a5538757.png)

**Comment by Lyzgarik** [comment]
Фикс через настройки
