### ISSUE TITLE
Некоторые требования  не сработали. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#631]
Пояснительная записка 34 (1)

- [x]  1) Требования "отступ от нумерации" в Списках

в сложных замного
![image](https://user-images.githubusercontent.com/18662965/117357015-189e1f80-aebd-11eb-8d62-cc2b13f719b5.png)

в простых замало
![image](https://user-images.githubusercontent.com/18662965/117357502-b1cd3600-aebd-11eb-96de-8ac268aa434d.png)

- [x] 2) Заголовок первого уровня
![image](https://user-images.githubusercontent.com/18662965/117357326-7b8fb680-aebd-11eb-92ce-1c1260bbc697.png)

**Comment by Lyzgarik** [comment]
приделал изменившуюся настройку для капса
