### ISSUE TITLE
Кусок формулы удалило. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#634]
Пояснительная записка 34 (1)

![image](https://user-images.githubusercontent.com/18662965/117540891-fa016b00-b019-11eb-8d02-414e92d08086.png)

![image](https://user-images.githubusercontent.com/18662965/117541020-91ff5480-b01a-11eb-87d5-1f205b0d0045.png)

**Comment by Lyzgarik** [comment]
у меня норм всё с ними. Дома ещё посмотрю на другом ворде
