### ISSUE TITLE
Нужен пробел между цифрой и тире в подписи к таблицам. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#635]
![image](https://user-images.githubusercontent.com/18662965/117567008-9c752900-b0c2-11eb-98ec-7157ed283e33.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/118052545-9c5b7e80-b38b-11eb-980e-b788f93b2da9.png)

**Comment by Lyzgarik** [comment]
на тесте норм должно быть, прод пока не заливал эту тему

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/118130130-b2a62080-b405-11eb-963c-3670c28b9f60.png)
