### ISSUE TITLE
Правим поиск элементов в источниках литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#637]
Файл -  "iteratura3"

- [ ] 1)  Конференция распозналась,  как книга

![image](https://user-images.githubusercontent.com/18662965/118295687-d5f3cd00-b4e4-11eb-8f61-237f6ba7f767.png)

- [x] 2)  журнал нашло, как книгу. На вхоже есть атрибуты журнала + курсив.  Все статьи после этой тоже 
![image](https://user-images.githubusercontent.com/18662965/118296638-de98d300-b4e5-11eb-9d7b-b6f397c7c76d.png)

- [x]  3)  Книга, заполненная неполностью 

![image](https://user-images.githubusercontent.com/18662965/118297934-777c1e00-b4e7-11eb-9d5a-be63742d8d28.png)

**Comment by freedom00000** [comment]
1\. А как понять, что это конференция? Нет интервала страниц и одной страницы. (Это условие для стати из сборника конференций)

3\.
![image](https://user-images.githubusercontent.com/10418363/118360294-9e8e2a80-b58f-11eb-886e-263efe7b7e8f.png)
Тут очень подходит под шаблон последние слова (с большой буквы и через запятую). Но по факту тут нет города, поэтому нужен совет, как определять, что название у книги окончено и нельзя брать из него элементы. Пробел - фиговый разделитель, сразу говорю

**Comment by GloomlySeth** [comment]
А куда название статьи делось?

**Comment by GloomlySeth** [comment]
1) В список распознаваемых городов хорошо бы добавить Курск и Казань

2) При оформлении англоязычных книг СТП допускает не прописывать и город и издательство
