### ISSUE TITLE
Остаются лишние элементы с подписи к рисунку. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#639]
Документ - Пояснительная записка 34 (1)

![image](https://user-images.githubusercontent.com/18662965/118938693-97806700-b957-11eb-8af8-8270beda939a.png)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/118983744-6e76cb00-b985-11eb-9fbe-87e4340fa60d.png)
исходник

**Comment by GloomlySeth** [comment]
начало названия рисунка с цифры это очень редкая штука, но возможная гипотетический, хоть я и не встречал. Оставляем.  

А вот начало с запятой - это уж совсем невероятная ситуация. Такое нужно фиксить.  

![image](https://user-images.githubusercontent.com/18662965/119036833-e363f800-b9b9-11eb-8a31-43f32028d2af.png)
