### ISSUE TITLE
Расшифровка формулы оформилась неверно. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#641]
Документ - Пояснительная записка 34 (1)

![image](https://user-images.githubusercontent.com/18662965/118939189-16759f80-b958-11eb-8549-6c0007e4f752.png)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/118975432-adece980-b97c-11eb-9436-1bbecbd7737b.png)
ещё 1 таблица внутри формулы в исходнике
