### ISSUE TITLE
Оформление формул-расчётов

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#643]
![image](https://user-images.githubusercontent.com/18488089/119031216-85ccad00-b9b3-11eb-8a82-99d1e138f11f.png)

![image](https://user-images.githubusercontent.com/18488089/119031171-751c3700-b9b3-11eb-9005-7e1ade04939c.png)

**Comment by DavZeus** [comment]
Не добавляет знаки препинания в конце формул
![изображение](https://user-images.githubusercontent.com/60774224/119151502-21175e00-ba58-11eb-90b2-dca580577758.png)

**Comment by DavZeus** [comment]
Могу предположить, что это связано с тем, что они были изначально в таблице.

**Comment by DavZeus** [comment]
Напомню, что расчеты не нумеруются.
Хотелось, чтобы и у других расчетов не было номеров
![изображение](https://user-images.githubusercontent.com/60774224/119153067-920b4580-ba59-11eb-8424-d3a2d7c61fa0.png)

**Comment by GloomlySeth** [comment]
По классике оформления научных работ приводят формулы и исходные данные. Потом приводят результаты расчётов в виде графиков или таблиц. 
В инженерных дипломах прописывают иногда числовые расчёты: складывают формулы цифрами. Но делают это типа так: буква - равно - и цифры.  
В данном случае это какой-то гибрид, который ближе к формулам, а не к расчётам. Если в этом случае есть повторение уже прописанной выше формулы, то по логике и всем правилам это повторение, тавтологию, нужно убрать.
