### ISSUE TITLE
Исчезают пояснения формул

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#644]
Было 
![изображение](https://user-images.githubusercontent.com/60774224/119238304-6caa3480-bb4a-11eb-87d6-eccb710a880b.png)
Стало
![изображение](https://user-images.githubusercontent.com/60774224/119238322-80ee3180-bb4a-11eb-93dd-c652d9f2e22a.png)

Ещё и запятая пропадает.

**Comment by DavZeus** [comment]
Такое ощущение, что удаляет предпоследнее
Было
![изображение](https://user-images.githubusercontent.com/60774224/119239674-518ff280-bb53-11eb-8ca1-987f8a0bab1b.png)
Стало
![изображение](https://user-images.githubusercontent.com/60774224/119239679-59e82d80-bb53-11eb-8d1a-cb7c735de630.png)

**Comment by GloomlySeth** [comment]
Дейвидас, если поправлен баг, закрывай его
