### ISSUE TITLE
Убирает знаки препинания из формул

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#645]
![изображение](https://user-images.githubusercontent.com/60774224/119239191-29eb5b00-bb50-11eb-9fd7-d750d99320eb.png)

![изображение](https://user-images.githubusercontent.com/60774224/119239196-37a0e080-bb50-11eb-8620-90c37722e2ea.png)

**Comment by GloomlySeth** [comment]
внутрь формул не залазим.

**Comment by DavZeus** [comment]
Но вот оно залазит. И много где это делает. На скринах знаки внутри формул были.
