### ISSUE TITLE
Не добавляет номер раздела в ссылке по тексту на таблицы и рисунки

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#646]
Было
![изображение](https://user-images.githubusercontent.com/60774224/119239237-6c149c80-bb50-11eb-8abe-e319b505e313.png)
Стало
![изображение](https://user-images.githubusercontent.com/60774224/119239245-78005e80-bb50-11eb-883f-58821bbdd65b.png)

**Comment by DavZeus** [comment]
Правильное ли это поведение?

**Comment by DavZeus** [comment]
Пример с рисунком
Было
![изображение](https://user-images.githubusercontent.com/60774224/119239323-ff4dd200-bb50-11eb-88ad-71dffc855fb3.png)
Стало
![изображение](https://user-images.githubusercontent.com/60774224/119239328-070d7680-bb51-11eb-989b-5a5f5fb924f1.png)

**Comment by GloomlySeth** [comment]
на тестовом, вроде, нормально перенумеровывает. 
Игорь, если обновить прод сможешь, дай сюда знать

**Comment by DavZeus** [comment]
Ещё такое было. Пропустило предыдущий абзац со ссылкой и добавило в предыдущий подраздел.
![изображение](https://user-images.githubusercontent.com/60774224/119243156-f5d26300-bb6c-11eb-8905-7115925ee6e1.png)

**Comment by Lyzgarik** [comment]
изначальная нумерация должна идти по возрастанию. Много раз повторяется в доке штука типа "Рисунок 1", повторно его не цепляет и не ставит перенумерацию в тексте, чтобы не сломать ссылки в других местах. (P.S. если сквозная, то надо по возрастанию, без обнуления на разделах)
