### ISSUE TITLE
Нет  реакции на изменение настроек для оглавления

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#65]
сверял с настройками в файле defaultMAGA.txt

выделил жирным настройки изменение, которых не приводит к изменению обработки
:{"main":{"levelhead":[2],"level":[H1],"spelling":[zaglavnye],"pattern":[Глава],"own":[null],"text":[null],"interval":[newpage],"after":[2 probelstring],"first":[otstup],_**"firstan":[0.00]**_,"second":[otstup],_**"secondan":[2.25]**_},"font":{"font":[ Times New Roman],"size":[15],"align":[centred],"typeface":[bold],"color":[null],"background":[null]},"number":[{"type":[null],"view":[null],"ownview":[null],"setting":[null]},{"main":{level":[H2],"spelling":[strochnye],"pattern":[null],"own":[null],"text":[null],"interval":[2 probelstring],"after":[2 probelstring],"first":[otstup],_**"firstan":[0.75],**_"second":[otstup]_,**"secondan":[1.5]**}_,"font":{"font":[ Times New Roman],"size":[15],"align":[left],"typeface":[solid],"color":[null],"background":[null]}, 

Расположение строк в оглавлении никак не реагирует на изменение настроек в файле "defaultMAGA.txt"
обновление оглавления не помогает. Настройки идентичны как для требований СТП так и для требований к магистерским.

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/50372712-7aa7a400-05e4-11e9-9f3e-f5b367f3cf1a.png)
а что это за настройки?
