### ISSUE TITLE
символы и слова в формуле отдельным типом шрифтов

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#650]
требуют часто слова в TNR, а символы в нём через прогу могут пропадать

**Comment by GloomlySeth** [comment]
а на прод запихивал? 

![image](https://user-images.githubusercontent.com/18662965/119894338-276c7500-bf45-11eb-8dfe-c41fee33e769.png)

**Comment by GloomlySeth** [comment]
файл рабочая комиссия-1

ещё такое бы учесть. 

![image](https://user-images.githubusercontent.com/18662965/119964415-de9ed580-bfb1-11eb-9f4d-885b669c7670.png)
