### ISSUE TITLE
Дефис в конце слова превращается в тире на названии раздела

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#663]
![изображение](https://user-images.githubusercontent.com/60774224/120076804-1ee47d80-c0b0-11eb-908d-f74cf4d554c4.png)

**Comment by GloomlySeth** [comment]
Дэйвидас, проверь во входном файле  есть ли пробел до дефиса? Если есть - обработчик не виноват. Таков алгоритм

**Comment by DavZeus** [comment]
Нет пробела.
![изображение](https://user-images.githubusercontent.com/60774224/120082745-4c8bef80-c0cd-11eb-8a80-4b811f42a082.png)

**Comment by GloomlySeth** [comment]
В пробел трансформируем дефис только если у него с двух сторон пробелы. Нужно перепроверить
