### ISSUE TITLE
В расшифроке фомкл появилась расшифровка формул. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#666]
файл - poyasnitelnaya (1)

![image](https://user-images.githubusercontent.com/18662965/120099343-944d5e00-c143-11eb-89c9-86e2a99afca1.png)

**Comment by Lyzgarik** [comment]
Невидимые слова где, если присвоить пустому месту перед словами любой стиль, то они появляются.

![image](https://user-images.githubusercontent.com/18488089/120199884-5d06ac00-c22c-11eb-9582-f6c7e3361d06.png)
