### ISSUE TITLE
Пропали границы у таблицы. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#667]
Файл - poyasnitelnaya (1)

![image](https://user-images.githubusercontent.com/18662965/120099425-058d1100-c144-11eb-97b5-ba8a4c590b47.png)

**Comment by Lyzgarik** [comment]
куча вписанных таблиц

![image](https://user-images.githubusercontent.com/18488089/120193223-d4d0d880-c224-11eb-85cc-d75570ba43e8.png)
