### ISSUE TITLE
Странное форматирование содержания

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#671]
1. Съезжают номера страниц. 
2. Есть строки, на которых присутствует только номер страницы. Наверное, там должно быть хотя бы одно слово.
![изображение](https://user-images.githubusercontent.com/60774224/120999272-9b065180-c791-11eb-9e09-7a9e4739ac0b.png)

**Comment by GloomlySeth** [comment]
Это ворд виноват. Добавь пробелв между словами цифра перескочит на другую сроку и станет, как нужно

**Comment by DavZeus** [comment]
Смысл же в том, чтобы это автоматически происходило.
