### ISSUE TITLE
Замена знака в списке

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#672]
Двоеточие было заменено на точку.
![изображение](https://user-images.githubusercontent.com/60774224/121000503-f7b63c00-c792-11eb-937e-dbd10438b52d.png)
![изображение](https://user-images.githubusercontent.com/60774224/121000546-03096780-c793-11eb-997b-360a7720fb96.png)

**Comment by GloomlySeth** [comment]
Всё верно было заменено. С точки зрения русского языка после двоеточия нужно писать с маленькой буквы. А при нумерованном списке следующая строка начинается с большой буквы

**Comment by DavZeus** [comment]
Однако в СТП написано по-другому.
![изображение](https://user-images.githubusercontent.com/60774224/121066214-4cc57280-c7d2-11eb-87fd-78d47a34b698.png)

**Comment by GloomlySeth** [comment]
Знаю. Там ещё много логических противоречий. В том числе и с самим СТП

**Comment by DavZeus** [comment]
Ладно. Пусть будет по правилам языка.
