### ISSUE TITLE
Разные отступы в расшифровках формул

### ISSUE THREAD

**Issue by DavZeus** [GloomlySeth/Bugtreking-SGOST#673]
На разном расстоянии находятся как расшифровываемые символы, так и их описания.
![изображение](https://user-images.githubusercontent.com/60774224/121000958-74e1b100-c793-11eb-9e47-908e20efa293.png)

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/121067501-cf026680-c7d3-11eb-934b-cdd59009d55c.png)
