### ISSUE TITLE
ошибка в методе содержания 

### ISSUE THREAD

**Issue by Lyzgarik** [GloomlySeth/Bugtreking-SGOST#674]
док 
![image](https://user-images.githubusercontent.com/18488089/121945637-a8f13f00-cd5c-11eb-8d6a-fd84a09095d8.png)

последний элемент / много ранов 

![image](https://user-images.githubusercontent.com/18488089/121945575-96770580-cd5c-11eb-9c89-4cbd40134769.png)

**Comment by freedom00000** [comment]
была ошибка не там. Приходил же заголовок только с номером, без названия. Поправил заголовок - все ок. Заодно цвет из настроек применил, а то был красный почему-то
