### ISSUE TITLE
Можно ли учесть вертикальное расположение теста в таблице? БГУИР 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#678]
Файл - DiplomKristinaDOobrabotki

![image](https://user-images.githubusercontent.com/18662965/122290390-59e21000-cefc-11eb-9930-d8a0d2d7f258.png)
слева результат обработки. Справа, как хотелось бы получить

**Comment by freedom00000** [comment]
можно.
