### ISSUE TITLE
Интернет источники в скиске литературы неверно оформляются. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#680]
файл - DiplomKristinaDOobrabotki

![image](https://user-images.githubusercontent.com/18662965/122393637-c18c6f80-cf7d-11eb-8153-ab79a591c225.png)

**Comment by freedom00000** [comment]
какая-то фигня с буковой "й". Она не из русского алфавита. Даже ворд подчеркивает "Электронны", а буква "й" как бы обособлено без подчеркивания.
Вот на сайте сравнил (где желтый - из документа, а зеленый - сам написал)
![image](https://user-images.githubusercontent.com/10418363/122398474-97897c00-cf82-11eb-99b3-cf6c2fe08296.png)

Фикс был такой: проверяю чтобы было "[элект(тут любые буквы) ресурс]". Чтобы как-то исключить в будущем буквы английского: p, o.

**Comment by GloomlySeth** [comment]
я думаю, почему половина источников нормально, а вторая какая-то кривая.
