### ISSUE TITLE
Требования к расшифровке формулы не сработали. БГУИР

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#681]
Файл - DiplomKristinaDOobrabotki

![image](https://user-images.githubusercontent.com/18662965/122470323-99752e80-cfc6-11eb-85d0-cdec3b589928.png)

**Comment by GloomlySeth** [comment]
Где смотреть? На тесте не срабатывает

**Comment by freedom00000** [comment]
Вроде это просто старая копия обработчика была на компе Игоря запущена. Он выключил, я обработал еще раз, работает.
