### ISSUE TITLE
Нужно скорректировать поиск элементов источников литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#688]
файл - literatura_3

- [x]  1) 

![image](https://user-images.githubusercontent.com/18662965/125796576-358ab78d-99c4-41e7-a2bb-8d4e99b3422d.png)

- [x]  2) 
![image](https://user-images.githubusercontent.com/18662965/125798061-726d3a97-6b7b-4390-b5bf-e6235d2e4340.png)

**Comment by freedom00000** [comment]
2 - если это сборник, то как это понять? там нет диапазона страниц

**Comment by GloomlySeth** [comment]
добавил интервал страниц - стало ещё хуже
![image](https://user-images.githubusercontent.com/18662965/126980589-8881d9df-59df-42a1-b1e7-1ef92e2053e1.png)

**Comment by GloomlySeth** [comment]
а точно тестовый сервер обновлён? Что-то ничего не поменялось

![image](https://user-images.githubusercontent.com/18662965/127174719-6f88f5b3-6307-4933-8c4e-db31654cce12.png)
