### ISSUE TITLE
Рисунок безосновательно оторвало от текста

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#692]
![image](https://user-images.githubusercontent.com/18662965/126754314-d29d2394-eab2-4578-a5db-b63076afc1d4.png)

**Comment by Lyzgarik** [comment]
пока замечено на доке 
![image](https://user-images.githubusercontent.com/18488089/127029900-70ab0abb-ae03-4faf-9d36-f0564196df6c.png)
при обработке на офисе 2016 и открытии с 2013 ворда. 
Если открывать в 16ворде или пдф, то будет норм
