### ISSUE TITLE
Не нашло элементов в источнике литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#694]
Файл - Титул, реферат, содержание 2

Журнал был помечен курсивом (см.  скрин). И тем не менее его не нашло при обработке + пропали фамилии. 

тут, конечно интервал страниц указан криво. Из-за этого криво на выходе он получился. Этот косяк игнорируем. 

![image](https://user-images.githubusercontent.com/18662965/127295564-9acf544d-7691-4cfc-bbce-d78aba06de3a.png)

**Comment by freedom00000** [comment]
проблемка немного в другом
![image](https://user-images.githubusercontent.com/10418363/127317075-acc7bee5-4a5a-4460-8a51-1908ac6cef2a.png)

2 почти одинаковых источника, только в одном помечен журнал, в другом нет.
