### ISSUE TITLE
Подпис к рисунку оторвало от рисунка. MLA

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#696]
Файл - EnglishRorTestPicUp

![image](https://user-images.githubusercontent.com/18662965/128553319-208f2880-77ec-4721-8177-f48c4e07fa54.png)

**Comment by freedom00000** [comment]
В оригинале снизу есть абзац, который начинается как подпись, а вот сверху просто предложение, по которому никак не понять, что это рисунок.
Оригинал:
![image](https://user-images.githubusercontent.com/10418363/128691275-8f1468f0-6921-4785-a2a0-b3f7b637627b.png)

**Comment by GloomlySeth** [comment]
Абзац в котором есть несколько предложений, даже если он начинается со слова "Fig."  и номера рисунка, - это просто абзац, а не подпись к рисунку. Всегда думал, что у нас есть эта проверка.
