### ISSUE TITLE
Слепить абзац

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#7]
если абзац закончился: есть переход на следующий абзац или значок ввода. И следующий абзац начинается с малой буквы но нужно содержимое этого следующего абзаца "затолкать" в предыдущий абзац.

**Comment by Lyzgarik** [comment]
тут можно писать уже *Я ТУТ БЫЛ*

**Comment by Lyzgarik** [comment]
Done
