### ISSUE TITLE
Нюансы поиска элементов источников литературы

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#700]
Файл - "Титул, реферат, содержание 2"

![image](https://user-images.githubusercontent.com/18662965/128892772-e925cce9-240e-4880-8460-17b6862d0ee4.png)

**Comment by freedom00000** [comment]
попробовал исправить

**Comment by GloomlySeth** [comment]
вроде находит. Только при оформлении точку нужно после номера тома вставить

![image](https://user-images.githubusercontent.com/18662965/129263305-487b7382-77b9-44c7-8201-65f87d2f6297.png)

**Comment by GloomlySeth** [comment]
Файл - Литература 3

Нюанс такой. Тока между томом и номером в журнальной ссылке  не ставиться. Но если есть том, а номера нет, то точка стаивться после тома. Если есть номер без тома, то точка ставится после номера. 

![image](https://user-images.githubusercontent.com/18662965/129597781-f99e0dc9-c43d-4479-a7eb-61dcf3408abb.png)
