### ISSUE TITLE
Недочёты в json по APA

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#701]
- [x] много точек после автора при парсинге тега SNAME_IN

![image](https://user-images.githubusercontent.com/18662965/193444535-2ae2642c-4e1e-4ca4-a1ec-68aeda6ddcdc.png)

- [x] есть источники, где авторы не попали в json

![image](https://user-images.githubusercontent.com/18662965/193444638-8dcf3063-41ff-4964-be06-d81ac3759aad.png)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/193877455-4d878d13-1a2d-40ff-8b3b-c80af06434c0.png)
всё же странная штука у APA требования. Само сокращает и доставляет точки, особенно у двойных-полных имён

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/193877792-86552e1e-1e2a-4664-823f-ff5ce99afec2.png)
исходное имя, которое приходит) и получается требование само себя кривит. ИЛи не умеет в полные-двойные имена

**Comment by GloomlySeth** [comment]
Умный инструмент. Я в курсе про это свойство диспетчера

**Comment by GloomlySeth** [comment]
![image](https://user-images.githubusercontent.com/18662965/194397769-955f42b5-d394-412d-b510-2b3069f74edc.png)

+ 

 ниже сразу ещё один раз такая же ситуация


+

![image](https://user-images.githubusercontent.com/18662965/194398104-3e10c96e-5dc6-4d96-b6cd-2ebd70701701.png)

**Comment by GloomlySeth** [comment]
в MLA с этой фамилией тоже беда
