### ISSUE TITLE
Недочёты в json по Harvard

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#704]
- [x] не все фамилии авторов спарсились в теги

![image](https://user-images.githubusercontent.com/18662965/193445724-2965f507-6818-4c43-8a32-69542581dc4d.png)

![image](https://user-images.githubusercontent.com/18662965/193446532-f254df13-ee4e-47e3-a287-bb19b5482968.png)

- [ ] будем делать ли дополнительный тех для et al?

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/193888089-ffffca70-aeae-4f7a-b7d4-9ebd9b922236.png)
требование выкидывает инициал)

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/193888828-2bf20844-301f-456a-82ef-a161b0ef1c56.png)

**Comment by Lyzgarik** [comment]
а надо ли et al? +в некоторых требованиях я так понял, он по другому может выглядеть. (как например вариант с кучей точек был)

**Comment by GloomlySeth** [comment]
> ![image](https://user-images.githubusercontent.com/18488089/193888089-ffffca70-aeae-4f7a-b7d4-9ebd9b922236.png) требование выкидывает инициал)

это нормльно. Оставляем, как делают требования


> ![image](https://user-images.githubusercontent.com/18488089/193888828-2bf20844-301f-456a-82ef-a161b0ef1c56.png)
это типа поянение к верхнему скрину? 




> а надо ли et al? +в некоторых требованиях я так понял, он по другому может выглядеть. (как например вариант с кучей точек был)

 да. Иногда по другому. Но нам нужно знать есть в источнике другие авторы, чтобы при формировании своей строки добавить этот момент.
