### ISSUE TITLE
Правильно ли работают настройки для отступов в содержании ?

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#77]
![image](https://user-images.githubusercontent.com/18662965/50713557-808e9200-1086-11e9-9c99-268647c3d9db.png)

или я не туда смотрю?

**Comment by freedom00000** [comment]
![default](https://user-images.githubusercontent.com/10418363/50726999-d108fc80-1125-11e9-97d8-7a8559bf0b30.JPG)
я так понимаю оно работает

**Comment by GloomlySeth** [comment]
понятно - значит нужно мне мозг перевернуть и разобраться как правильно эти настройки прописывать. 
Или, может, ты заберёшь как я понимаю и переведёшь в нужный формат?

**Comment by freedom00000** [comment]
а так не правильно?
