### ISSUE TITLE
Оформление таблиц и стили внутренностей

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#8]
![image](https://user-images.githubusercontent.com/18662965/32679981-b0c7e00a-c679-11e7-96ac-2905abfcc316.png)

  Красное замечание это для Влада.

  Синее замечание для Игоря и Ильи.

**Comment by GloomlySeth** [comment]
Игорь с Ильёй баг пофиксили. Работает. Ждём Влада.

**Comment by freedom00000** [comment]
Я сделал для таблиц, только нужно в проект основной занести.

**Comment by GloomlySeth** [comment]
Ты заешь кому отправлять

**Comment by GloomlySeth** [comment]
Поправка, Игорь с Ильёй сделали так, что подпись к таблице становиться поцентру. Она, подпись должна быть по ширине страницы и начинаться без абзацного отступа

**Comment by Lyzgarik** [comment]
up?
