### ISSUE TITLE
Перенумерация таблиц работает не адекватно

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#84]
obschiy.docx

![image](https://user-images.githubusercontent.com/18662965/55029175-74c5c280-501a-11e9-8de5-28e0cc78c212.png)

Создаётся впечатление, что ходим по замкнутому кругу и никогда из него не вырвемся....

**Comment by GloomlySeth** [comment]
Нет ссылки на таблицу....

![image](https://user-images.githubusercontent.com/18662965/55030820-3205e980-501e-11e9-82c5-e2142ab8fd30.png)

В исходном файле на рисунок есть ссылка в тексте и она соотносится с номером рисунка в подписи. На выходе - расходняк.  Проверить причину. 

![image](https://user-images.githubusercontent.com/18662965/55030912-772a1b80-501e-11e9-8081-b1c6d00649f9.png)

**Comment by freedom00000** [comment]
случайно поломал эту фичу когда переделывал, не работает на половину
