### ISSUE TITLE
Год переобразовался в цифры

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#88]
![default](https://user-images.githubusercontent.com/18662965/51981028-caf70900-24a2-11e9-8aac-22626d3d3dfb.png)

**Comment by GloomlySeth** [comment]
Причём в том же месте

**Comment by freedom00000** [comment]
![image](https://user-images.githubusercontent.com/10418363/52149281-43192680-267d-11e9-86f5-bb52b34e5b9f.png)
бред какой-то ...

**Comment by GloomlySeth** [comment]
проверить в какой версии ворда будет работать корректно, прописать в "Возможности"

**Comment by freedom00000** [comment]
теперь во всех версиях должно
