### ISSUE TITLE
Файл СТАТЬЯ1

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Bugtreking-SGOST#9]
Исчезли все рисунки
такблицы имеют погрешности в оформлении, подпись  таблицы по центру, в подписи остаётся цифра  от исходной нумерации таблиц

**Comment by Lyzgarik** [comment]
что там с ним сейчас

**Comment by Lyzgarik** [comment]
![image](https://user-images.githubusercontent.com/18488089/33678506-f4dffc8e-dacc-11e7-96ab-cff64183149e.png)
![image](https://user-images.githubusercontent.com/18488089/33678513-ff0d0c42-dacc-11e7-867d-9b1d019a2946.png)
такая ботва в таблицах там
